### ISSUE TITLE
[Bug]: Fabric v6 failing to load SVG

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#10037]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/hamzawain7/t856sjzn/

### Steps To Reproduce

1.  Open loadSVGFromURL from fabric v6: https://jsfiddle.net/hamzawain7/t856sjzn/  .There are no objects in response in console
2. Open loadSVGFromURL from fabric v4: https://jsfiddle.net/hamzawain7/5nzqomhw/ . Objects are correctly extracted from the svg.

### Expected Behavior

loadSVGFromURL of fabric v6 should have returned objects parsed from the svg

### Actual Behavior

no objects in response

**Comment by gloriousjob** [comment]
The issue seems to occur where the svg has "a.11.11,0,0,0,0,0". Oddly, it has numbers after that, which I'm not sure is normal (I would've thought there's a command).

But either way, what seems to be going on is toX and toY are 0 when this is parsed, that makes px and py 0, which then makes root an NaN and things cascade from there and blow up.
https://github.com/fabricjs/fabric.js/blob/master/src/util/path/index.ts#L110

I'm not sure what the proper solution is here. The parsing of commands is a bit different compared to fabricjs 4 so some setting of the current values might have been different then (probably fixed bugs but now is revealing other problems).

**Comment by asturur** [comment]
if it was working in fabric  5 we broke the parsing logic and we need to restore

**Comment by asturur** [comment]
Those should be 2 concatenated a commands.

**Comment by asturur** [comment]
Works fine in fabric 5
<img width="760" alt="image" src="https://github.com/user-attachments/assets/5dfe74e0-c108-435e-bf90-9bd49b1aad2e">

**Comment by asturur** [comment]
The PR fixes it

**Comment by gloriousjob** [comment]
Wow, that’s tricky. Not the way I’d like to handle it since it relies on js oddness but seems to get the job done. Nice work figuring it how it worked before! I never would’ve figured that as the cause.

**Comment by hamzawain7** [comment]
Thanks for fix 🙂

**Comment by asturur** [comment]
I do not like that thing anyway, but i do not have a reliable way to say 'this arc path will be converted to 0 segments.
I could say 'if it starts and ends in the same point and is taking the small arc then is a zero segment.
But i m not sure the same path was passing for the large arc flag. i should test.

Being a real regression, i just restored the old code.
