### ISSUE TITLE
[Bug]: almost all demos broken due to broken fabric import URL

### ISSUE THREAD

**Issue by theranajayant** [fabricjs/fabric.js#10126]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

http://fabricjs.com/import-pdf

### Steps To Reproduce

1. Open http://fabricjs.com/import-pdf
2. The file isn't loading 
3. See console: fabric doesn't exist
4. Happening with a lot demos 

### Expected Behavior

The demo should work on codepen. In this case pdf should be imported. 

### Actual Behavior

![Screenshot_20240904_214854_Brave](https://github.com/user-attachments/assets/16669cdf-bf86-43e9-adf5-835e6c92e1ef)

### Error Message & Stack Trace

```bash
Fabric is not declared
```

**Comment by asturur** [comment]
Yes this is a known issue.
I m working on fabricjs.github.io and i'm slow because i m also working on fabricJS and also an actual job.
The demos on the old website do not work and it would be a huge waste of time to update them there.

You can find the working demo here:
https://fabricjs.github.io/demos/import-pdf/

and you can find the code here:
https://github.com/fabricjs/fabricjs.github.io/tree/main/src/content/demo/import-pdf
