### ISSUE TITLE
Some fonts rendering outside the selection box

### ISSUE THREAD

**Issue by paulcanning** [fabricjs/fabric.js#1326]
I am getting issues with various fonts rendering outside the selection box.

![google_font_issue](https://cloud.githubusercontent.com/assets/1275739/2957296/58beedca-da9d-11e3-9764-d506a999e384.png)

As you can see, the text appears to be push upwards, outside of the orange selection box.

It only happens with some fonts, in this example, the Google font, Oswald. I cannot find any reason why some fonts would do this.

I need to remedy this as my application requires accurate placement of text and whilst the user sees the text on the canvas, when I re-render the text using CSS, it is in place where the orange box is (as it should be?!)

**Comment by Shmacked** [comment]
So a while ago, I was trying to recode parts of fabric.js because of a bug I couldn't initially fix (then found out why it was happening and fixed it - mainly due to improper initialization of canvas... anyways...) and led me to have to come up with a creative solution to solve this problem. I know that canvas can load svgs... so why not create a text svg that is centered inside of itself (doable solutions are found on stackoverflow.com) and then you can also resize the canvas of the svg element to fit around the text (also doable - stackoverflow has a question related to svgs and playing cards). The trade off is that the text wouldn't be editable as it usually would be inside of fabric.

**Comment by asturur** [comment]
This can already be done, you create your fabric standard text, you use `toSVG()` and import back the result as image.
Having multi line and styling and correct spacing will still you bring to the same exact problem anyway, understand how big the text is and run some logic on the size.

**Comment by ab-etemadi** [comment]
I have this issue with both text and SVG objects. For SVGs, it happens intermittently and is hard to reproduce.
<img width="460" alt="Screenshot 2024-11-04 at 10 22 43 PM" src="https://github.com/user-attachments/assets/d37f6d00-47b4-4797-8b9b-4d9c78867b1e">
