### ISSUE TITLE
Resized images pixelated - option for better downsampling available? [$300 awarded]

### ISSUE THREAD

**Issue by NewsteadEric** [fabricjs/fabric.js#1741]
Regarding https://groups.google.com/forum/?hl=en#!topic/fabricjs/N5LOujX-qMA it would be great to have an option for better resampling when scaling images with fabric:

It looks like fabric.js currently uses only the browser's native/default (bilinear?) resampling capabilities, which usually result in very pixelated, low-quality images when scaling down.

I would like to request a feature that avoids pixelation and resamples images to a higher quality especially when scaling down (similar to http://jsfiddle.net/qwDDP/), e.g. when the user uses the scaling handles on an image element in a fabric.js canvas, or when the scaleX/Y or width/height properties are used.

Depending on performance impact, this could happen during scaling, or when scaling has completed, but should yield a high quality scaled image in any case.

Addendum: As far as text resampling suffers the same issue (which it may not), it would be ideal if that was addressed as well.
##

**Comment by lionellei** [comment]
Hi guys, when the canvas is serialized by calling JSON.stringify(canvas), the filters object did not serialize all of its parameters. For example, a resize filter has parameters: type, scaleX, scaleY, rcpScaleX, rcpScaleY, but after converting to JSON or toObject, only the type is there. And when load such JSON back to the canvas, the image's width and height becomes 0.

**Comment by asturur** [comment]
thanks for reporting, i m gonna check it.

**Comment by lionellei** [comment]
Hi @asturur any update? I am pretty new to this so I am not much a help but reading the documentation, it looks like JSON.stringify(canvas) will call each of its object's toJSON method. So is it this resize filter object's toJSON method not correct?

**Comment by lionellei** [comment]
Hi @asturur, I am sorry to bug you again, but we really would like to have this issue fix for our release. I would post bounty if need be (have not figured out how to yet, or if only certain people could post bounty). 
Also, text is pixelated too.

**Comment by asturur** [comment]
i m sorry i got other issues. if you mamage to make a jsfiddle for me, so i have the code causing the problem, i will look into it today.

**Comment by lionellei** [comment]
Hi, I did not manage to get a jsfiddle, I am not too familiar with that but it will be a quick test to just try to load this JSON:
"{"objects":[{"type":"image","originX":"left","originY":"top","left":7.64,"top":11.36,"width":880,"height":942,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.31,"scaleY":0.31,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","src":"http://teeyeah-images.b0.upaiyun.com/1430384957/I_love_bipolar_black.png","filters":[{"type":"Resize","scaleX":0.3,"scaley":0.3,"resizeType":"hermite","lanczosLobes":3}],"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet"}],"background":""}"

once you load it, you will see that the canvas has one object and that object has width and height of 0. 

Also once the resize filter is applied, and then if you serialize the canvas, the original image's width and height is changed. 
For example, if original image is 1000 x 1000, and you apply a filter of scaleX and scaleY both are 0.5. And then you serialize the canvas, the JSON contains an image object of size 500 x 500, and a filter of scaleX and scaleY being 0.5. So what happen if you load canvas from this then? will the newly loaded image be 250 x 250? I can not try that since when I load it I get an object of size 0x0.

**Comment by asturur** [comment]
hi @lionellei,
i thought the issue was fixed.
i m out some days, i ll be back sunday and a i will check this situation.

which of the filter are you using? static resize on image load or dynamic resize or both?

**Comment by lionellei** [comment]
Hi, @asturur , no the issue was there for quite some time, I am just busy with other part of the project that I put off this by tolerating a pixelated scaled down image. 

I was using static resize filter. The easiest reproduction will be to just load the json I provided above into a canvas and you will see nothing.

So just to summarize, the problem is two fold:
1) Resizing filter changes the original image's dimension, and serialization will save the resize filter in the image's filters property. If everything works accordingly, upon loading, will the original image be resize again? i.e., the filter be applied to the already scaled image? I tried removing the filter from the image after the first static resize, then serialize, but when I loaded back the image, the size is the pixelated scaled down version.

2) Loading a canvas containing an image from URL and with resize filters will yield a canvas object with dimension 0x0

**Comment by lionellei** [comment]
It's also possible that I maybe doing something wrong. So it will be nice if you could provide some example code, I am sure you must've done some testing when you implemented this. Thanks in advance.

**Comment by asturur** [comment]
as soon as i m back ( sunday ) i will make a demo with the functions. so we
find the bugs.
Il 30/apr/2015 04:57 PM, "Lionel Li" <notifications@github.com> ha scritto:

**Comment by asturur** [comment]
@lionellei i checked the code and i found those errors:

- the filter of typer resize was not considering options when restored from object
- the exported option had a mispelled scaley instead of scaleY
- the filters at image initialize where applied twice
- the resizeFilters ( used for dynamic filtering on resize ) where not exported nor enlived from object.

now everything looks like it is working, as soon as i can i push a PR

i have also to check interaction with cropping as a separate issue of course.

**Comment by lionellei** [comment]
@asturur very nice. I was about to report the last bullet point and you beat me to it :)

**Comment by lionellei** [comment]
Hi @asturur, is there any fix to this issue? Thanks.

**Comment by asturur** [comment]
it has been merged recently.
it looks like it works good.

If you want to have a look, another check is even better.
Download the latest source and build it to test it.

**Comment by lionellei** [comment]
Hi @asturur, yes it works good in terms of now the filter is saved and could be reloaded. The image quality is better but still not very crisp when scaling down though.

**Comment by asturur** [comment]
which is a good filter? do you know.some? lanczos with 8 lobes? filters do
not do miracles anyway, it depends what do we expect.
Il 06/giu/2015 20:11, "Lionel Li" <notifications@github.com> ha scritto:

**Comment by jitendrapawar** [comment]
hello

**Comment by jitendrapawar** [comment]
I tried this but it really affects performance, browser gets crashed.
I am using "lanczos 3". Can anyone help?

**Comment by asturur** [comment]
it is taxing yes. use a simpler one, bilinear or slice hack. are way faster.

**Comment by jitendrapawar** [comment]
yes right, but that does not provide same accuracy as "lanczos 3". There is another issue

**Comment by jitendrapawar** [comment]
yes right, but that does not provide same accuracy as **"lanczos 3"**. 
Sorry to say, but I found another issue, if we use this filter, it gives error on using dispose function of canvas.

canvas.dispose();

**Comment by asturur** [comment]
can you create a jsfiddle with the problem?

2016-05-06 11:41 GMT+02:00 jitendrapawar <notifications@github.com>:

**Comment by jitendrapawar** [comment]
sorry @asturur, I found that, I called canvas.dispose(); two times. Sorry for the trouble. But can we optimize the "image filtering". Or can you guide me to make it more optimized.

**Comment by asturur** [comment]
I'm pushing some control customization this weekend, polishing Itext regressions.From next week i'm gonna watch for general speedup with webgl filtering, i hope i can do something good/cool/performant.

**Comment by jitendrapawar** [comment]
Can anyone please explain me how image filter **lanczos** works ?

**Comment by vxrai** [comment]
@kangax  To fix the pixelation of images on resize i used the sliceHack resize filter. After applying them, i resized the image to approx half of its original size and this time the image din’t pixelate. Everything worked perfect, life was awesome before I saved the canvas using Canvas.toJson and the next time when i reloaded the saved backup again on canvas using Canvas.loadFromJson the same resized image is now pixelated. It will be really great if you could help with this. If i resize the image again, anti aliasing will work as expected, but not sure why the anti-alised state was not retained when the images reloaded on canvas using LoadFromJson

**Comment by vxrai** [comment]
And here's the fiddle that replicates the issue - http://jsfiddle.net/varun598/jagfhh8d/22/

**Comment by Godweed** [comment]
I am facing this problem in dynamic patterns. I am attaching a high resolution image as pattern to object. And when trying to create a print version in node the pattern looks in small  resolution.

**Comment by leesc81** [comment]
When applying resizeFilter with multi-touch on touch device, lag occurs severely.

It is a burr when performing multi-touch scaling and rotating.

The js file hosted in https must be imported into jsfiddle,
I can not host the js file that contains the Gestures module because I do not have an https server.

Below is the source I used.

  fabric.Image.fromURL(img_url, function(img) {
    img.setOptions({
      scaleX: 0.25,
      scaleY: 0.25
    });

    img.resizeFilters.push(new fabric.Image.filters.Resize({
      resizeType: 'hermite',
    }));

    canvas.add(img);
    canvas.centerObject(img);
    
    img.setCoords();
    }, {
      crossOrigin: 'Anonymous'
    }
  );
