### ISSUE TITLE
Page Doesn't Scroll on Mobile

### ISSUE THREAD

**Issue by TimHarker** [fabricjs/fabric.js#1864]
When you're on a mobile device and multi select is turned off on the canvas you can't drag on the canvas to scroll the page.
##

**Comment by michalbe** [comment]
How about using 'fabric.Canvas#allowTouchScrolling' ([announced in 2013](https://twitter.com/fabricjs/status/371934651772059648))? I met the same problem and with small fix it solved my problem. The issue was that after setting it to `true` the page was scrolled even when I wanted to modify an item (scale, rotate, move, etc). I fixed it with:

```javascript
  var disableScroll = function(){
    canvas.allowTouchScrolling = false;
  };

  var enableScroll = function(){
    canvas.allowTouchScrolling = true;
  };

  canvas.on('object:moving', disableScroll);
  canvas.on('object:scaling', disableScroll);
  canvas.on('object:rotating', disableScroll);
  canvas.on('mouse:up', enableScroll);
```

It's not perfect but works way better than the default behavior - when the object is selected we disable touch scrolling and enable it on `mouse:up` event that fires also after `touchend`.

**Comment by rekrah** [comment]
Your timing was uncanny.  I mean, I'd just picked up the project again since having a manufacturing issue for the past 6 months.  Literally just picked it up again, and thought to myself, where did I put this issue, where did I leave off, I remembered receiving some great suggestions but where was that forum again?  And POW, @michalbe posts a real solution/possibility and I'm up and running...  I'm sure I'll need to refine, but I'm up and running again...  I truly believe that with enough creativity, anything is possible.  Happy coding...

**Comment by michalbe** [comment]
@rekrah You're welcome :)

**Comment by DawnPaladin** [comment]
Great solution, @michalbe! Next person who finds this, be sure to put `object:moving`, not `object: moving` like I did. Doh!

**Comment by idenlos** [comment]
If you are using multi touch gestures add 

`canvas.on('mouse:down', disableScroll);`

then scrolling is really disabled if you do something in your canvas

**Comment by fendorio** [comment]
@michalbe Great solution, I am however running into issues with the workaround on chrome mobile. Getting the following error:

`Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

Mobile chrome pauses javascript execution whilst the user is scrolling... Anyone else come up against this?

**Comment by Taral-Patoliya** [comment]
The scroll in mobile device does not work,even if i use `allowTouchScrolling`

**Comment by stikks** [comment]
I'm having this same problem right now and i've tried all the methods mentioned above to no avail

**Comment by raphaelbeckmann** [comment]
@idenlos 

> If you are using multi touch gestures add
> 
> `canvas.on('mouse:down', disableScroll);`
> 
> then scrolling is really disabled if you do something in your canvas

You are my hero! Thank you very, very much.

**Comment by TiagoSilvaPereira** [comment]
Worked better for me (because when I start to drag out of selection, the selection is cleared and automatically the scroll is enabled):

```
this.canvas.on('selection:created', this.disableScroll);
this.canvas.on('selection:cleared', this.enableScroll);
```

**Comment by mh5** [comment]
I'm using a fabric.js 3.5.0 build with gestures support. To get the scrolling and the scaling (via the controls) work well together, I had first to manually incorporate the patch #5904 in my installation. After doing so, what seemed to be working fine for me was to set `allowTouchScrolling` to true when the canvas is instantiated and to call `event.preventDefault()` whenever an `object:scaling` is fired.

```
canvas.on('object:scaling', function() {
    event.preventDefault();
};
```

**Comment by sponno** [comment]
I had issue with this exact problem. 
From what I have found, you must set 'allowTouchScrolliong:true' in the constructor argument.

```
var canvas = new fabric.Canvas('your-canvas-id', {
    backgroundColor : '#000',
    height: 400,
    width: 400,
    allowTouchScrolling: true, // <-- this is what you're after
});
```
this doesn't work
`canvas.allowTouchScrolling = true;  // has no effect after the canvas has been created.`

**Comment by optprojects3** [comment]
If any issue with page scrolling.
Use this one in your CSS file : 

canvas{ 
    z-index: -1111;
}

**Comment by adilmallick** [comment]
If any issue with page scrolling, use this one in your CSS file : 

canvas { 
    z-index: -1111;
}

**Comment by adilmallick** [comment]
> I had issue with this exact problem. From what I have found, you must set 'allowTouchScrolliong:true' in the constructor argument.
> 
> ```
> var canvas = new fabric.Canvas('your-canvas-id', {
>     backgroundColor : '#000',
>     height: 400,
>     width: 400,
>     allowTouchScrolling: true, // <-- this is what you're after
> });
> ```
> 
> this doesn't work `canvas.allowTouchScrolling = true; // has no effect after the canvas has been created.`
Use this one :
canvas { 
    z-index: -1111;
}

**Comment by timfrio** [comment]
v5.1.0 - 'upper-canvas' blocks page scrolling on the phone

there is an option to hide the problem, but it can affect the entire functionality of the group, for example, dragging elements does not work, but scrolling will work

```
.upper-canvas {
    touch-action: initial!important;
    z-index: 1;
}
.lower-canvas {
    z-index: 2;
}
```
or `document.querySelector('.upper-canvas').remove();`
this is not a solution to the problem, just when the phone is allowed to perform these actions
