### ISSUE TITLE
TextArea Ipad little bug

### ISSUE THREAD

**Issue by abraham63** [fabricjs/fabric.js#3826]
I have found a strange behaviours with Textarea and Ipad. When i double tap on a fabric textarea to edit it on my Ipad I have the following behaviours : 
1)- A scroll down on the page
2)- when I type some texte : a cursor appears at the middle of my arround HTML and moove when I write without display any caracter.

This is not very important because textarea is modified as well but it's a little mistake.

**Comment by asturur** [comment]
i think it depends on the zoom level of the ipad. what version of fabric?

**Comment by timmy63** [comment]
version 1.7.9
 if someone else can try it. Maybe it's my application but not sure.

**Comment by asturur** [comment]
i have no ipads at all nor iphone.

**Comment by CristiScorteanu** [comment]
1. I can confirm that a wild cursor appears: 
![bug](https://cloud.githubusercontent.com/assets/17610624/24903767/0c57d65c-1eb7-11e7-8845-45f59b6794b6.jpg)

2. There is a problem with the fix for #3798, when I type a word, insert a space, then nothing happens. From what I saw it's because of the `white-space: nowrap;`. So it fixes chrome 57, but bugs safari.

**Comment by AlexanderIstomin** [comment]
for me it works at least in safari on mac

**Comment by AlexanderIstomin** [comment]
sorry, i forgot to mension: i added this little hack to my css file to fix spacebar issue only in chrome:
/* temporary fix for chrome spacebar bug */
@media screen and (-webkit-min-device-pixel-ratio:0) and (min-resolution:.001dpcm)
{
  textarea[autocapitalize='off'] {
    white-space: nowrap !important;
  }
}
