### ISSUE TITLE
obj.getBoundingRect returns old value after modifing selection

### ISSUE THREAD

**Issue by nag5000** [fabricjs/fabric.js#4540]
## Version
Tested on 1.7.20, 2.0.0-rc.3

## Test Case
http://jsfiddle.net/w1uk1r8j/

## Steps to reproduce
1. Add 3 rectangles to canvas.
2. var A = canvas.getObjects().map(o => o.getBoundingRect(true, true));
3. Select 3 rectangles.
4. Resize selection.
5. var B = canvas.getObjects().map(o => o.getBoundingRect(true, true));

## Expected Behavior
B differs from A.

## Actual Behavior
B[i].width === A[i].width; B[i].height === A[i].height

If it is not a bug, how can I get new bounding rects?

**Comment by blobinabottle** [comment]
For what I understand it's the logic of fabric: activeSelection apply its transform only when you deselect. That's the same for a group, you'll only apply transforms to child of a group when ungrouping.

You need to apply the transform of the activeSelection itself to the objects into the selection. `objRects.map(o => o.width * sel.scaleX)`

**Comment by asturur** [comment]
So activeSelection is just a facade to be able the code of a single object to move around multiple objects without going crazy with code changes.

Is also comfortable because the activeSelection transform is going to transform the canvas and give us the illusion of transforming the objects.

There is no a method to calculate the bbrect outside of a group of an activeSelection, i think we should just make it.

Now going to naming, as always, that is not easy.

We are using the word absolute for getting a bbrect that represent the bbrect in canvas coordinate when the zoom and padding are neutral, and skipping the control padding.
This in opposition to the old bbrect that was just based on control ( and maybe should have been removed before 2.0 transition )

using a third boolean looks terrible to me, any other idea?

**Comment by ShaMan123** [comment]
http://jsfiddle.net/2wnx60za/1/
Seems fixed by #7669
