### ISSUE TITLE
SVG with only one element is not rendered after toJSON/loadFromJSON

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#4718]
## Version
2.0.1

## Test Case
http://jsfiddle.net/6d5YC/30/

## Steps to reproduce
Press the button in the jsfiddle and you see the "empty" object.

**Comment by asturur** [comment]
Took me  while to figure out what is going on.
After loading the SVG you are assignigng type=group to the object. Making it becoming a Path, with a group type. When serialized, is not desiarizabile.

Why are you assigning type=group?

groupSVGElements had the weird behaviour of NOT GROUPING if is just one object only, and i left it like that because i did not understand the meaning and i did not want to break people's app.

**Comment by asturur** [comment]
Do you think this bebaviour should be changed, or just documented?

**Comment by panthar1** [comment]
I ran into this bug a while ago, but never reported it, as it's not a major part of my requirements. But, the reason you assign group, is when there is multiple SVG elements it parses through, there is no easy way to know what each individual canvas object's type is.  The same problem exists when you load objects one by one, because there is no easy way to know "this is a path" or "this is a line", without looking at the raw SVG that created that canvas object that just got imported.  What would be an ideal solution would be for fabric.js to predict object-type of the SVG objects returned from loadSVGFromString(). If that's too difficult, making a grouped objec just like the jsfiddle to work like how a jpeg image would work fine for me too.

**Comment by asturur** [comment]
Well you cannot change object type.
You can know what object you get looking at the type from it.
The point here is that in case of SVG with a single object, the groupSVGElements returns the same object and that is at least weird. I m not sure if is a behaviour that should be removed.

**Comment by panthar1** [comment]
Look at this jsfiddle http://jsfiddle.net/8x4fa9uq/ , I modified to have 2 SVG objects in it. Look at the console.log(objects), the "type" on the objects are not passed into the callbacks(s) on that function, so fabric.js is not doing any object prediction, or at least not updating the "type" of the object.

**Comment by asturur** [comment]
@panthar1  http://jsfiddle.net/8x4fa9uq/2/ please be careful of inspecting the prototype.
object.type is there and is path for both objects.

**Comment by panthar1** [comment]
Apparently the 'type' is there, wonder why the "type" does not show up unless you do a foreach, never ran into that,  my bad... But, okay, so lets say I import it, the 'type' is now a group after calling fabric.util.groupSVGElements(objects, options);. That group still won't behave like a jpeg image imported would http://jsfiddle.net/krxr8ujr/2/ , I can't set any type of border on that, it is drawing the right bonding box dimensions, but the stroke is not being displayed.

Basically, all I am trying to do, is make a "SVG image import" behave like how a JPG image import would, or at least close, and I imagine this is the use-case of most people. I don't care about image filters (although that would be nice), what I care about is, if I group all the SVG elements into one, I should be able to style the whole group with a border like I would a jpeg image, having the imported objects in a group, this does not work (see jsfiddle). Any idea on how to fix that?

**Comment by asturur** [comment]
@Kienz  any comment?

**Comment by asturur** [comment]
@panthar1 in your case just use the image object and pass the svg src as image src. You do not need the whole importSvg process.

**Comment by panthar1** [comment]
So if I used it as a image object, would it scale on resize like how a SVG would? Grouping initially seemed like better option for me, because you can let users un-group it into it's individual SVG objects (and export as SVG) as opposed to a bitmap layer in the SVG.
