### ISSUE TITLE
Custom Build - Additional Module Filters Request

### ISSUE THREAD

**Issue by brenley** [fabricjs/fabric.js#4884]
The custom build feature is very handy for avoiding loading lots of code that is not needed in all situations. 

The [web version](http://fabricjs.com/build/) contains options to not include shapes such 
Circle, Triangle, etc. However, the web version is always set to the latest version of fabric and when running in production, we do not always want to upgrade the version when deciding to handle a new shape because of the need to perform full regression testing. 

The [custom build](https://github.com/kangax/fabric.js/blob/master/build.js#L192) includes the ability to include / exclude some modules dynamically but does not include the full control offered by the website in that it automatically pulls in all shapes. 

I believe the only step needed is to add the same logic already present in the webview to the `build.js` script:
![website-controls](https://user-images.githubusercontent.com/4406712/38204810-281a306e-3659-11e8-9861-a5f68d202d45.png)

**Comment by asturur** [comment]
That can be an addition to the build.js script.
Do you feel like making a PR?

This would not solve operating on the older version, you would have to manually checkout the file from the latest version in the old commit you want in order to build with the new script.

We also need more information on what is a needed dependency over others.
For example if you have Interaction module, Group is mandatory. But no one knows.
