### ISSUE TITLE
Emojis don't render with StaticCanvas, limitation or bug?

### ISSUE THREAD

**Issue by acemtp** [fabricjs/fabric.js#4928]
I have a basic TextBox. If I enter a normal text, it renders correctly with fabric.Canvas and fabric.StaticCanvas

But If I add an emoji in the text, it renders correctly with fabric.Canvas but the whole text (emoji + normal text) is not rendered with fabric.StaticCanvas.

Is it a limitation of StaticCanvas or a bug?

I'm on Mac with latest fabric.

render with Canvas: http://prntscr.com/jahvsd
render with StaticCanvas: http://prntscr.com/jahw3o

**Comment by acemtp** [comment]
I just would like to know if it's an issue or a normal behavior. If it's normal, there's no need to spend time on it. If it's a bug, I'll post a proper template.

**Comment by acemtp** [comment]
Here is the jsfiddle:

http://jsfiddle.net/eA3xH/614/

As you can see, it works with Fabric & StaticFabric on browser.

But if you save the js file as "main.js" in an empty directory

> npm install fabric --save
> node ./main.js

Open img.png and you'll see no emoji.

**Comment by asturur** [comment]
This may be a cairo bug not supporting color fonts.

**Comment by asturur** [comment]
Still a problem with nodecanvas 2

**Comment by lukasondrej** [comment]
@asturur Is there any way to replace all emojis with svgs so that they render correctly? I've been trying to get color emojis in node but no luck.

I'm happy to help fix this but I'd really help if you could point me in the right direction.

P.S. Perhaps a subclass of Textbox that would do this?

**Comment by asturur** [comment]
In some application i decided to subclass rendering of text to detect emoji and draw them as images, but that is a complicated solution.

You have to have all emoji assets of some kind ( i use the googlenoto emoji that i published in a package here: https://www.npmjs.com/package/asturur-noto-emoji )

You have to detect emoji in your text with something like
https://github.com/mathiasbynens/emoji-regex, so that you know when is time to switch drawing from normal text to image.

Then you have to do the fabric work modifying the graphemeSplit function in order to split correctly every emoji 

There is much to do, i do not think i can show or release my code, but those are some tips.

**Comment by asturur** [comment]
I'm also very not sure i interpreted the issue correctly the first time. This speak of some difference between static canvas and canvas. But then is flagged as node.

**Comment by sebastianfast** [comment]
For anyone stumbling across this issue, check out [my reply here](https://github.com/Automattic/node-canvas/issues/760), where I'm overriding `fabric.Textbox` to render [twemoji-emojis](https://www.npmjs.com/package/twemoji-emojis) as SVGs

**Comment by mengsumin** [comment]
@tsafs  hey，brother, i happend the same problemn with node renderer emoit by fabricjs..  could you help me ? i use loadfromjson to renderer emojs in canvas, how to code that i can use fabri to renderer emoji. it is very important .  thanks. very much.
