### ISSUE TITLE
canvas mouse:out event

### ISSUE THREAD

**Issue by durga598** [fabricjs/fabric.js#4930]
## Version
2.2.3

## Test Case
[jsFiddle](http://jsfiddle.net/Da7SP/1584/)

## Steps to reproduce
Do a mouse out on an object.
## Expected Behavior
As I am binding `mouse:out` event to canvas, so it shouldn't fire for object.

**Comment by samael205** [comment]
Hi,
I updated your fiddle, now it only fires when you out of the canvas. [Fiddle Mouse Out Only Canvas](http://jsfiddle.net/Da7SP/1586/)

**Comment by durga598** [comment]
No as a behaviour of our events, it should only fire for canvas, as I added to it. Not for objects, right?

**Comment by samael205** [comment]
I think that the event is as valid for objects as for the canvas. Although they should be separated, one for objects and another for canvas.

**Comment by asturur** [comment]
Hi,
this is an updated fiddle with just more info on the event
http://jsfiddle.net/Da7SP/1589/

I understand your expectations, but events in fabric are fired for both object and canvas togheter just to give you more options on how to bind them

on the canvas, having a possible target in the arguments, or on the single object, ignoring all the other objects.

Also mousedown, attached to object gets fired on both ways.

As you see in the fiddle when exiting the canvas you get an opt.target that is null, while when exiting from the circle you get the circle in your options.

**Comment by durga598** [comment]
`mouseout` is there for object, and `mouse:out` should only for canvas. [fiddle](http://jsfiddle.net/Da7SP/1592/)

**Comment by asturur** [comment]
No, this may be a reasonbale way to see things, but this is not how fabricjs is built.
Both events are fired.

You register mouseout to 100 circle, you mouse out from the canvas ( but not hovering from the object ). there is no active hovered object, mouse:out gets fired with no target, there is no listener registered to it, you do not see nothing.

you register mouse:out and mouseout on 100 circles, you go out from the canvas, no objects hovered, you get your mouse:out callback with no target information

you over out from one of the 100 circles, mouseout fires calling the callback that you add to that object, and mouse:out fires having in the argument a target property that reference to the object.

This allows you to have a generic mouseout event, and something specific of objects.

Is just made like this, you should not search a parallelism with other event emitters or too strong logic, because you many not find it

**Comment by menelike** [comment]
While I understand the concept behind the `mouse:out` handler, it is flawed if used to detect if, for example, a line has started in the canvas, but left the canvas and drawing should be stopped then. It just *sometimes* works. Without digging into the code I suspect that there might be race condition with the state of `this._hoveredTarget` https://github.com/fabricjs/fabric.js/blob/244e46c00ff8171084011bdf6e9b13fdc6936087/src/mixins/canvas_events.mixin.js#L148

![jun-22-2018 11-26-18](https://user-images.githubusercontent.com/4238881/41769384-676b19cc-760f-11e8-8b42-10e06c332f7b.gif)
http://jsfiddle.net/wLna97mf/

There is no clear way to tell if the event is coming from the canvas or not. The current workaround is to subclass [_onMouseDown](https://github.com/fabricjs/fabric.js/blob/244e46c00ff8171084011bdf6e9b13fdc6936087/src/mixins/canvas_events.mixin.js#L147-L159).

**Comment by asturur** [comment]
are you drawing the line with mousemove?
in that case, what options.e.target is giving you as element?

That could give you an idea if you are in the canvas or outside

**Comment by menelike** [comment]
`mouse:move` also passes `pointer` which can be used to determine if the drawing is within the canvas (e.g. `(pointer.x < 0 || pointer.x > canvas.width || pointer.y < 0 || pointer.y > canvas.height)`)

Imho `mouse:out` needs to be fixed anyway, I *think* that also `opt.target === null && !('nextTarget' in opt)` could used as a workaround as well. If the API should stay the same the proper fix needs to handle `target === null` upon `mouse:out` which isn't always the case.

I don't want to start a discussion, I'm absolutely thankful for all the work that has been going into this project, but IMHO mixing canvas and object events into one event made things unnecessarily complicated. If I want to listen to both, I should have to hook on two events, one explicitly used for canvas, one for all objects.

**Comment by asturur** [comment]
for target i was meaning options.e.target.
That should five you the HTML element that generated the event, that should NOT be canvas.upperCanvasEl, that is a proof you are not hovering the upperCanvas.

While opt.target is a fabric  thing, opt.e is the native javascript event.

What else is wrong about mouse:out? mouse out is a fake event since is generated by mouse move and not real mouseout. ( i have to check, i may be wrong)

Anyway i m always happy to follow discussion about how things should be or not be.
I prefer coherence when other things can be fixed with documentation.

So what is wrong with mouse:out? i did not get it.

**Comment by menelike** [comment]
Sorry, @asturur I totally misunderstood your hint. 

> That should five you the HTML element that generated the event, that should NOT be canvas.upperCanvasEl, that is a proof you are not hovering the upperCanvas.

Indeed the native event can be used to determine if the mouse has moved out of the canvas (e.target would not be `canvas.upperCanvasEl` then). I've updated the fiddle http://jsfiddle.net/rnjet9md/5/ if anyone else faces this issue.

> What else is wrong about mouse:out? mouse out is a fake event since is generated by mouse move and not real mouseout. ( i have to check, i may be wrong)

Since there is a way to determine to which target the event belongs to I don't see any other issues.

> So what is wrong with mouse:out? i did not get it.

Nothing is wrong, it was me not taking the native event into account.

**Thanks a lot for your patience and help, highly appreciated. And sorry for the false alarm.**
