### ISSUE TITLE
Fuzzy edges when there is no bg fill

### ISSUE THREAD

**Issue by Jonesie** [fabricjs/fabric.js#4976]
## Version
2.2.4
## Test Case
http://jsfiddle.net/jonesie/1pvq7bkn/1/

## Steps to reproduce
See, here's the problem.  I don't get the problem except in my main app.  The above jsfiddle looks fine but in my app I get weird dots around the edges of shapes if there is no filled object behind them.  See the attached screenshot.

![capture](https://user-images.githubusercontent.com/3420249/40212679-5d08d78a-5a7b-11e8-8cd9-1edb55ef12ca.PNG)

The circle on the left is on the canvas directly whereas the one on the right has a filled rectangle behind it.

**Comment by Jonesie** [comment]
Never mind.  Just noticed that this only happens on an external monitor.  Must be a driver issue.

**Comment by asturur** [comment]
usb? or normal?

in case try to disable hw acceleration in browser, just to understand what is going on

**Comment by Jonesie** [comment]
HDMI.
Turning off HW acceleration in Chrome fixed it.
Interesting.

**Comment by Jonesie** [comment]
FF & Edge are both ok.  Sad to see the slow death of Chrome before our eyes.

**Comment by asturur** [comment]
chrome move fast, break things.
They do not have a good regression testing for canvas in my opinion. They concentrate on v8 performances and sometimes break canvas with code refactors or backend changes.

Since i work professionally with fabricjs for 2 years i noticed 3 major breakage.

It can also be just a driver problem in this case
