### ISSUE TITLE
[Question] Scale paths with recalculation of points in fabric.js

### ISSUE THREAD

**Issue by AlexSergey** [fabricjs/fabric.js#5022]
Hello!

I'm trying to rework default scale logic in Fabric.js to scale shapes in current selection by recalculation of path points (scaleX/scaleY are always 1 in this case).

I recalculate points with Paper.js on object:scale. My approach works fine for single path scale, BUT fails with selection of paths. I'm having problems when paths in selection have their own angels. I can't determine correct top/left for each path and because of it objects are not correctly located relatively to each other, and I don't understand why...

In order to visualize the problem, I've create a simple fiddle with this problem. 
https://jsfiddle.net/nb10hs0s/
Here we binded canvas of Fabric.js to the canvas of Paper.js to display that objects from Paper are perfectly placed, but in Fabric.JS we have alignment problem with the same objects...
I have a feeling that I don't understand something in logic how Fabric renders updated pathes, or something like that...

Please take a look at attached screenshots.

**wrong transform**
http://joxi.ru/krDzb7XCEMWYM2

**correct transform**
http://joxi.ru/eAOzb5QCxwQPn2

Any help or suggestions would be appreciated.

**Comment by AlexSergey** [comment]
asturur, this will be great! I made few methods for update path but I setted angle to 0. This is work fine.

For example:

```jsx
function updateAfterEdit(obj, pathData, opts = {}) {
    obj.path = obj._parsePath.call({
        path: pathData.match(/[mzlhvcsqta][^mzlhvcsqta]*/gi)
    });
    let calcDim = obj._parseDimensions.call(obj);

    obj.set({
        angle: 0,
        width: calcDim.width,
        height: calcDim.height,
        left: calcDim.left,
        top: calcDim.top
    });

    obj.pathOffset = {
        x: calcDim.left + obj.width / 2,
        y: calcDim.top + obj.height / 2
    };

    fabric.cleverbrush.objects.updateGradient(obj);

    if (obj.textPath && !opts.ignoreTextPath) {
        obj.textPath.update(opts);
    }

    if (obj.canvas) {
        obj.canvas.fire(fabric.cleverbrush.events.pathEdited, { target: obj });
    }

    return obj;
}
```

But it work fine only one path. Now, I want to make it for activeSelection with save figure angle. This angle made offsets on top and left for figures. Could you help us to do that correct way?

**Comment by AlexSergey** [comment]
If I update my scaled paths without shape (only top * scaleX, left * scaleX) it will be strange offsets too

http://joxi.ru/DmB8w7OTwdvOzA

```jsx
f.set({
    top: f.top * scaleY,
    left: f.left * scaleX
})
```

**Comment by AlexSergey** [comment]
Why are objects incorrect places on canvas when we set top/left/angle/path/pathOffsets in activeSelection?

**Comment by andrewzolotukhin** [comment]
It looks like an issue with Fabric. It seems that Fabric is adding some offset when you grab resized paths from Paper.js and update fabric objects with correct coordinates. @asturur, do you have any ideas why this is happening? May be there is some need to be done in the updatePath function in fiddle?

**Comment by asturur** [comment]
fiddle is too complicated to be a minimal use case. Probably wrong math or not recreating the path correctly

**Comment by andrewzolotukhin** [comment]
@asturur, here is more simplified example:
https://jsfiddle.net/w8fy2p07/4/

**How to reproduce the issue:** select both objects and scale them, then click "Recalculate scale" button.

What's happening inside:
I go through all objects and transform their pathes by Paper.js (any other SVG path manipulation library could be used, doesn't matter) applying transformMatrix from object to path. Then I rotate each path to -angle around the path center in order to compensate fabric's angle.
Then I update objects with new paths, set them scaleX/scaleY=1 and skewX/skewY=0 and also recalculate pathOffset.

This operation lead to object jumping, which seem to be wrong, becuase I checked that pepper,js returned me correct modified paths.

I conclude that there is some additional magic required to update path on the fly (may be @asturur can suggest something) or there is an issue in framework...
Any suggestion why it's happening?
