### ISSUE TITLE
Binding "selected" event to object has an issue

### ISSUE THREAD

**Issue by njofce** [fabricjs/fabric.js#5026]
## Version
2.3.1

## Test Case
https://jsfiddle.net/njofce/p8ejLra1/1/

## Steps to reproduce
When a "selected" event is bound to the object, I am trying to access the object with **e.target**

## Expected Behavior
Calling **e.target** within the callback function should return the selected object.

## Actual Behavior
**e.target** is undefined. Check the console for output

**Comment by asturur** [comment]
you can use THIS keyword in object bound events

**Comment by nickensoul** [comment]
@asturur it's a bug, not a big/urgent deal, but it's a 🐛.
Just for your clarity and other developers ran into this.

Of course, we can use Function context in handler (`this` keyword), but there are cases we wouldn't like to. For example, it's not too convenience to use classic Function instead of arrow-style and define another parent context (`_this`, `_that`, etc.).

[Here](https://github.com/fabricjs/fabric.js/blob/master/dist/fabric.js#L10702) you fire event. But later, [here, for example](https://github.com/fabricjs/fabric.js/blob/master/dist/fabric.js#L10711) you add target property into `event` argument.

I feel you should check these lines and fire events even its arguments are formed.
[See modified jsfiddle with simple async timeout.](https://jsfiddle.net/4wayhk5g/)
Here we can see that `e` argument in handler being expanded with `target` property in next tick of the Javascript Event Loop.

Would be nice to be fixed, or, maybe, I'll got some time to make a PR. Thanks!

**Comment by asturur** [comment]
Is not exactly the same issue.
When you call an event from the object itself you do not get e.target that is how the code is done. The e.target is the object itself.

We should clarify in the docs that since even handler are bound to the object context, lambdas are maybe not supported ( i need to verify this ), since i think they miss the bind method

While using a setTimeout is weird, i understand you do not want the argument to mutate, and that should be fixed somehow, maybe creating 2 objects instead of 1.

**Comment by nickensoul** [comment]
@asturur okay, thanks for the paying attention.
