### ISSUE TITLE
Stairs effect on exported image

### ISSUE THREAD

**Issue by DangerD256** [fabricjs/fabric.js#5051]
Editor:
![image](https://user-images.githubusercontent.com/17032489/41561817-95667b8c-7353-11e8-955c-80c57545ae9a.png)
Exported image: (100%)
![image](https://user-images.githubusercontent.com/17032489/41561846-a63545c4-7353-11e8-8e49-9b6a5e1d15e8.png)
Exported using:
`canvas[i].toDataURL({format: 'png', multiplier: 3});`

Is there any way to fix that?
![image](https://user-images.githubusercontent.com/17032489/41561933-da2cb98e-7353-11e8-99f3-a6c4fb4ed15e.png)
![image](https://user-images.githubusercontent.com/17032489/41561956-e6c5328e-7353-11e8-92c0-899edf569e28.png)

Exported image:
http://mediatours.ca/tmp/flyer/0-300.png

**Comment by DangerD256** [comment]
close it, seems like its just small image

**Comment by asturur** [comment]
If you resize an image from BIG BIG to small, those artifacts will happen unless you use:

pica library: https://www.npmjs.com/package/pica
or a resize filter in fabricJS ( like the webgl lanczos ) but the implementation to run it when needed is up to you.

Also since it looks like you may be in printing, if you need to change DPI of exported images you can check this library i did recently:
https://github.com/shutterstock/changeDPI   thast is just about printing size and not quality of the image itself.
