### ISSUE TITLE
throw error while exec Object.fabric.parseSVGDocument

### ISSUE THREAD

**Issue by chenwei979** [fabricjs/fabric.js#5052]
Our project select fabricjs as the graph library, but some svg file can't dispaly in canvas:

throw error while exec Object.fabric.parseSVGDocument
![image](https://user-images.githubusercontent.com/19570496/41570357-0a7bcf4c-73a1-11e8-904a-22521f7edcbd.png)

Same error evan fabricjs.com/kitchensink.

The demo svg file: https://drive.google.com/open?id=1FnHkYoJU_vBDHeKKPD5edPUNhaTD9dbp

**Comment by asturur** [comment]
can you make a failing fiddle?

On 20 Jun 2018 8:24 am, "Charlie Chen" <notifications@github.com> wrote:

I have similar issues with nearly all SVG files which have text inside, the
text is either in wrong position or in different size, for double-byte
character string it's totally a mess.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fabricjs/fabric.js/issues/5052#issuecomment-398637840>,
or mute the thread

**Comment by durga598** [comment]
You are using `xlink:href="#path3997"` in svg but there is no id containing `path3997`

**Comment by asturur** [comment]
if the Svg is valid and open in browser, i would be happy that fabricjs can read it.
