### ISSUE TITLE
Canvas Alpha Mask Feature

### ISSUE THREAD

**Issue by aggrosoft** [fabricjs/fabric.js#5057]
Currently there is no support for setting an alpha mask on the canvas - I made a custom implementation and wanted to ask if you think it would be useful to add this to the core. This is my extension, I know this could be improved in terms of readability and maybe performance. Also I do not know if this would be possible for SVG export. This will allow you to provide a fabric.Image instance for the maskImage property:

```javascript
/**
 * AlphaMaskCanvas class
 * @class fabric.AlphaMaskCanvas
 * @extends fabric.Canvas
 * @return {fabric.AlphaMaskCanvas} thisArg
 */
fabric.AlphaMaskCanvas = fabric.util.createClass(fabric.Canvas, /** @lends fabric.Canvas.prototype */ {

  _maskCachingCanvas: null,
  _objectCachingCanvas: null,
  maskImage: null,

  /**
   * Modified to clip objects to alpha mask if any given
   * @private
   * @param {CanvasRenderingContext2D} ctx Context to render on
   * @param {Array} objects to render
   */
  _renderObjects: function (ctx, objects) {
    var octx = ctx;

    // Create a special canvas on which we can draw the objects if there is a mask
    if (this.maskImage) {
      var canvas = this._objectCachingCanvas || fabric.util.createCanvasElement();
      canvas.width = ctx.canvas.width;
      canvas.height = ctx.canvas.height;
      ctx = canvas.getContext('2d');
      this._objectCachingCanvas = canvas;
    }
    // Default of what fabric.js does, draw all objects
    var i, len;
    for (i = 0, len = objects.length; i < len; ++i) {
      objects[i] && objects[i].render(ctx);
    }
    if (this.maskImage) {
      ctx.save();
      ctx.globalCompositeOperation = 'destination-in';

      // If some object is active we will create 0.5 opacity background for the mask
      // otherwise we will just use the raw mask
      if (this._activeObject) {
        if (!this._maskCachingCanvas) {
          var maskCanvas = this._maskCachingCanvas || fabric.util.createCanvasElement();
          maskCanvas.width = ctx.canvas.width;
          maskCanvas.height = ctx.canvas.height;
          var mctx = maskCanvas.getContext('2d');

          mctx.globalAlpha = 0.5;
          mctx.fillStyle = 'white';
          mctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
          mctx.globalAlpha = 1;
          mctx.drawImage(this.maskImage.getElement(), 0, 0);
          this._maskCachingCanvas = maskCanvas;
        }
        ctx.drawImage(this._maskCachingCanvas, 0, 0);
      } else {
        ctx.drawImage(this.maskImage.getElement(), 0, 0);
      }
      ctx.restore();

      // Draw our clipped objects to the main context
      octx.drawImage(ctx.canvas, 0, 0);
    }
  }
})
```

**Comment by asturur** [comment]
Hi!
So as of i m working on the clipPath feature and i hope to reuse the same exact code for masks.
The difference being that clipPath are hard alpha masks based on fill, while the masks are more flexible.

The idea is the same, but instead of creating a new class i m creating a group of objects and using as clipPath their cache canvas.

Your idea is good too.
Would you like to check the current clipPath code and see what you think? is here:
https://github.com/fabricjs/fabric.js/pull/4786/

most of the work is in this file, the rest is SVG parsing stuff:
https://github.com/fabricjs/fabric.js/pull/4786/files#diff-840d0c62989de96492c73f1de1f574d0

**Comment by aggrosoft** [comment]
Your solution is truly more flexible - I did not think of using a fabric.Object for the clipping path. Seems to work fine from what I see there.

I would still love to see my little helper implemented which makes the clipping only 50% opaque for as long as you select an object. But this could be done easily in userland as clipPath is a fabric.Object which could just draw a half opaque Rect behind itself.

**Comment by asturur** [comment]
so now the idea is to implement clipPath, clipPath force no stroke and black fill.

Later it can be filled with a different color with opacity, or an image too, and should work as your code does.
in your case you used destination-in, i m not entirely sure which is the right one to use. The important is that the final code can emulate SVG masks, so that we can import them.

The problem in implementing your solution too, is that is missing SVG export, and it can't be used per object to obtain particular effect on an image only.

**Comment by aggrosoft** [comment]
Okay, I do not think the masks I'm currently implementing will be usable in SVG - as SVG uses black/white and I'm only using the alpha channel. What SVG does with masks looks more like some custom operation, or can you think of a globalCompositeOperation that will work?

**Comment by asturur** [comment]
it works similarly, i have no idea what alghoritm it uses, but i bet is some kind of destination-in or similar. Where the mask is opacity 1 object is displayed, where is less is not displayed.

Maybe is a multiply

**Comment by blobinabottle** [comment]
I think SVG is using globalCOmpositeOperation from what I can read in the specs (but maybe I'm not following correctly your discussion): 

> For any graphics object that is used as a mask, the mask value at any point is computed from the color channel values and alpha channel value as follows. First a luminance value is computed from the color channel values:
> 
> If the computed value of ‘color-interpolation’ on the ‘mask’ element is linearRGB, first convert the original image color values (potentially in the sRGB color space) to the linear RGB color space (see Rendering properties). Then, using non-premultiplied linear RGB color values, apply the luminance-to-alpha coefficients (as defined in the ‘feColorMatrix’ filter primitive) to convert the linear RGB color values to linear luminance values.
> If the computed value of ‘color-interpolation’ on the ‘mask’ element is sRGB then the luminance value is calculated by taking the non-premultiplied RGB color values, applying the luminance-to-alpha coefficients (as defined in the ‘feColorMatrix’ filter primitive) to convert the RGB color values to luminance values.

https://www.w3.org/TR/SVG11/masking.html#Masking

**Comment by aggrosoft** [comment]
Looks more like some kind of multiply or luminance masking to me - topic seems pretty hard to grasp, I can provide the code if we work out the details on how it should be implemented first. Any SVG pro here that can shed some light?

**Comment by asturur** [comment]
i do think is a multiply but is easily verified making some colored svg and some colored mask and just... try.
This is how i reversed the svg things that were not specified easily around.

ClipPath code is getting out today or tomorrow, i would immediately start to think how to reuse it for mask, since that was the purpose of having one code capable of handling both

**Comment by aggrosoft** [comment]
Yeah maybe you are right, I will try to create some example files and see what I can come up with

**Comment by asturur** [comment]
if you can share the files here i ll help too.

**Comment by blobinabottle** [comment]
I can't find the examples I did with the svg mask, but it's already quite powerful. Much more than a basic multiply. Works with gradients, images, etc.

**Comment by ncou** [comment]
hi, here is an example using SVG mask i made a long time ago :
http://jsfiddle.net/fmgXt/817/

I use the svg as a background overlay with a 0.2 opacity. And a rect in the center who is masked.
This only work on Chrome (not on FF or IE11). Looks like the @aggrosoft example bu perhaps i was not understanging this topic.

I will wait the ClipPath release to test the fabric version.

**Comment by asturur** [comment]
because this is a clippath.

Otherwise of it has to take in account alpha and other things is a mask.

Is just an svg concept we try to respect in order to make import and export possible.

Once implemented masks, you can also just use masks and leave clippaths out, unless you need both of them together.

**Comment by aggrosoft** [comment]
alright, thanks for clarifying - you said you want to reuse the code for masks as well. Are you interested in a PR that implements masking? Can you explain a little bit more on how you are planning to reuse it?

**Comment by asturur** [comment]
So the code would be more or less the same.
What would change would be the final global composite operation and not calling `setClippingProperties(ctx)`

Said so, while this is the concept, the hard work is doing it for an object with both cliPath and mask.

And to do in a way that is sort of nice.

We could end up with code duplication if there is no way around.

What clipPath does, with a full text search in the source code, is showing where the clipPath is considered in the process. ( cache invalidation, toObject export, ... ... )

The hardest part is the svg-import, that you do not have to look at, but knowing that if necessary to support it some changes will be made at whatever code we may end up with.

Actually clipPath is not released yet because i wanted to write more tests, but i have no time for now, i  could just release and gather feedback.

I would be open to have an hangout and check togheter, but i m really busy those days.

**Comment by aggrosoft** [comment]
IMHO: just release it and mark it as beta - I think user feedback would help a lot, especially when it comes to SVG im/export testing. Also this would make it easy to just install via NPM and check if it works in real world projects.

Just drop me a message when you have some more time and we can discuss about the masking stuff.

**Comment by asturur** [comment]
What timezone are you?

**Comment by aggrosoft** [comment]
Same as you are, if Rome is still your current location - Germany GMT+2 currently
