### ISSUE TITLE
FabricJS Drawing mode and Hammer.JS Pinch creates unwanted, non objects

### ISSUE THREAD

**Issue by Melcus** [fabricjs/fabric.js#5083]
## Version
1.7.22

## Steps to reproduce
 If the Fabric's drawing mode is activated, and I try to pinch using hammer.js's Pinch event, a weird artifact appears that does not show when I call getObjects() on canvas.

The code is as follows : 

```
let hammer = new Hammer.Manager(this.canvas.upperCanvasEl); // Initialize hammer
  let pinch = new Hammer.Pinch(); // Initialize pinch
  hammer.add([pinch]); 

  hammer.on('pinch',  (ev) => {
    let point = new fabric.Point(ev.center.x, ev.center.y);
    let delta = this.zoom * ev.scale;

    this.canvas.zoomToPoint(point, delta);
  }); 

  this.canvas = new fabric.Canvas('c', {
        hoverCursor: 'pointer',
        selection: false,
        allowTouchScrolling: false
  }); // create the canvas

  this.canvas.setBackgroundColor('rgba(255,255,255, 1)', this.canvas.renderAll.bind(this.canvas)); // add a white background
  this.canvas.isDrawingMode = true;  // enable drawing mode


  this.canvas.on('mouse:down:before',  (o) => {

   if(o.e.touches && o.e.touches.length > 1) { // more than 1 finger
      this.canvas.isDrawingMode = false;   // When a mouse down event is detected - disable FreeDrawing mode. At this point the (non) object is already created. 
    }
  });
```
If I try to get all the objects from canvas, the wrongfully unwanted items will not show up : 

```
  this.canvas.getObjects().map((o)=> {
     // The items are expected here, and maybe delete the ones that have less that 3-5 polypoints .. but they do not show up. 
  });
```

If you draw anything else after this, the "point" disappears.

Video : https://www.youtube.com/watch?v=hrxFfrQkDPU

Stack Overflow Issue : https://stackoverflow.com/questions/50947125/fabricjs-drawing-mode-and-hammer-js-pinch-creates-unwanted-non-objects

JSFiddle : http://jsfiddle.net/zgj60fr5/44

**Comment by asturur** [comment]
Can you make a JSFIDDLE with hammer.js integration so that we can try it?

**Comment by Melcus** [comment]
Updated with JSFIDDLE. For some reason, `mouse:down:before` will not trigger in the fiddle, but you get the idea.

**Comment by asturur** [comment]
i l get back to this as soon as i can,

**Comment by hiep317** [comment]
Hi @Melcus @asturur 
I'm facing the same issue, do you have any work around solutions?
Thanks a bunch.

**Comment by Melcus** [comment]
@hiep317 
Hey man. I haven't worked on it for over a year and I don't have access to the codebase anymore :( 
Sorry and good luck.

**Comment by Damzwan** [comment]
Hey guys, I might be a bit late but I think I solved it! The problem lies with the 'mouse:down:before' event, initially o.e.touches.length will be 1 since it is impossible to put both your fingers on the screen at the same time. fabric js recognises this as a mouse down and starts drawing. If you put the drawing mode on false, it will only work starting from the next mouse:down event.

my solution is inspired by the way how telegram solves it. They allow you to draw but as soon as a pinch event is recognised, they destroy the last path created.

`
 hammer!.on('pinchstart', () => {
    cancelPreviousAction(c)
  })
  
  function cancelPreviousAction(c: Canvas) {
  setTimeout(() => {
    fabricateTouchUp(c)

    if (c.isDrawingMode) {
      const lastObject = c.getObjects().pop()
      if (lastObject) c.remove(lastObject)
    }
    c.renderAll()
  }, 1)
}

export function fabricateTouchUp(c: any) {
  const evt = new TouchEvent('touchend', {
    bubbles: true,
    cancelable: true,
    view: window
  })
  c.upperCanvasEl.dispatchEvent(evt)
}
`

c.upperCanvasEl is not a valid property according to types/fabricjs so that's why I do c: any. The reason why we put a timeout is that you cannot trigger a touch event right after the previous one.

Hope this helps :)
