### ISSUE TITLE
ClipTo

### ISSUE THREAD

**Issue by luismanuelmontoro** [fabricjs/fabric.js#5090]
I see clipTo, was deprecated, how i can clip a canvas without using clipTo? thanks.

**Comment by asturur** [comment]
Untill the alternative is ready there is nothing else. There is  a PR in
nearly good state with the new feature.

On 6 Jul 2018 7:42 pm, "Luis Manuel Montoro Marchal" <
notifications@github.com> wrote:

I see clipTo, was deprecated, how i can clip a canvas without using clipTo?
thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fabricjs/fabric.js/issues/5090>, or mute the thread
