### ISSUE TITLE
Performance issues with large SVGs and zooming

### ISSUE THREAD

**Issue by NoFr1ends** [fabricjs/fabric.js#5099]
## Version
2.3.3

## Test Case
http://jsfiddle.net/uztedrb1/

## Steps to reproduce
Zoom with mouse wheel into the canvas

## Expected Behavior
The zoom is smooth and the pixel-perfect rerendering happens after scrolling ends like scaling does.

## Actual Behavior
The large svg image is getting rerendered every browser frame update, because of this the zooming process lags.

**Comment by blobinabottle** [comment]
To be fair, this SVG is hell to render. Even Illustrator can't do it properly.

**Comment by asturur** [comment]
Is not easy to define performance strategies that work for many use cases.

Zooming a group means re rendering everything. there are options that are a pain to implement.

One could be define a threshold for object rendering: if objects get smaller than 1x1 pixels skip them
Another could be apply the `is out of screen` logic to objects inside of groups
Another could be make a fixed limit of objects per render cycle and the other objects get rendered 16 ms later on top of the already rendered so that you try to keep a minimum 20fps target
Another one is to apply the cache scaling that we use on the scaling event to the zoom event to and re render once the zooming action is finished.

All of them require to put restrictions on what user may expect.

**Comment by blobinabottle** [comment]
I think the last one is what Figma.com is doing (in webgl). I think that kind of UX is more than acceptable. But I don't know how better performance this would mean

**Comment by asturur** [comment]
webgl is another option.
But i have no idea how to write a shader that will make write text with subranges and custom fonts.

**Comment by asturur** [comment]
and i do not want fabricJS to be 3megs of JS. at that point is an application, an editor. Handling full screen changes with 500+ objects will always be a bottleneck.
I agree there are low hanging fruit for improvements

**Comment by DevChuckNorris** [comment]
@asturur "Another one is to apply the cache scaling that we use on the scaling event to the zoom event to and re render once the zooming action is finished."

How is this possible, I think it's not implemented right? And if not do you have some points where it would be possible to start?

**Comment by asturur** [comment]
we need to make the zooming action something that is supported in fabricJS.

That would mean that rather than having a method to setZoom we should have a state in which the user is actually zooming, fabricjs know that and will defer some processing to the end of zoom.

i think maybe a state canvas.isViewportChanging true/false would be something neutral enough
