### ISSUE TITLE
objectCaching: false make extra stroke in object with shadow

### ISSUE THREAD

**Issue by AlexSergey** [fabricjs/fabric.js#5127]
## Version
2.3.3

## Test Case
http://jsfiddle.net/agodj2h3/1/

## Steps to reproduce
When we set
fabric.Object.prototype.objectCaching = false;
Any objects with shadow+affectStroke have extra stroke

## Expected Behavior
http://joxi.ru/MAjEgR4I4dJRE2

## Actual Behavior
Check jsfiddle

**Comment by asturur** [comment]
you could invert the order of fill and stroke with the paintFirst property so that the overlap is less visible.
The problem is that unless you are caching, fill and stroke are two separated operation and will produce 2 different shadows, the last of which will overlap your last drawing operation ( fill or stroke )
 This has always happened and indeed affectStroke was meant for stroke only shapes.

To solve this we should first paint the object with fill and stroke on a separate layer and then paint this layer with a shadow. But this is exactly what caching is doing.
Is there any particular reason why you are disable caching?
