### ISSUE TITLE
Drop Shadow bug on flipped images

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#5148]
## Version
2.3.4

## Test Case
https://jsfiddle.net/melchiar/m7t1yvrd/

## Steps to reproduce

Add an image to the canvas with a blurred dropshadow and flip the image. You'll see that the drop shadow appears cropped on the sides

![drop-shadow-bug](https://user-images.githubusercontent.com/9057412/43815940-1c64f92e-9a87-11e8-99db-af3b3d110f7b.PNG)

**Comment by asturur** [comment]
oh what a weird bug.
Is chrome only for now and for the strange way it disappear i ll point the finger to hardware acceleration.

Can you please have a look if disabling hardware acceleration the bug is still there?
Also can you post your system specs?
(operating system, browser version, GPU (ati, nvidia, if intel integrated which one)

**Comment by melchiar** [comment]
You're right, chrome hardware acceleration seems to be the culprit. 

Here are my specs:
Windows 10 64-bit
Chrome 68.0.3440.84
Nvidia Geforce GTX 1050

The issue also exists on Chrome for Android (tested on a Huawei P10)

**Comment by asturur** [comment]
i think i need to open a chromium bug, won't be fixed easily.

**Comment by asturur** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=899512
Opened bug i chromium, flagging as chrome bug and closing the issue. Conversation and updates will go on, but since is handled, i m going to close it.
