### ISSUE TITLE
Inorge small object 

### ISSUE THREAD

**Issue by sangle1996** [fabricjs/fabric.js#5226]
![image](https://user-images.githubusercontent.com/42021108/45336612-88de3100-b5ae-11e8-8673-566587d5ee72.png)
this is list object of my canvas;
I want to remove small that i not intention to draw just a little touch on screen, do you have any ideal? 

## Version
2.3.5

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by ncou** [comment]
I don't understand the problem ???? can you explain a bit ?

**Comment by asturur** [comment]
You can filter out your objects from the array using object.getScaledWidth and getScaledHeight and remove them by size.

canvas._objects is the array to filter.

If you want to exclude them ONLY from render, you need to modify the `chooseObjectsToRender` private method of the StaticCanvas

Other than this this is a request that is more for stackoverflow rather than here.
