### ISSUE TITLE
Cloning selection of custom objects fails

### ISSUE THREAD

**Issue by cybrooke** [fabricjs/fabric.js#5229]
## Version
2.3.6

## Test Case
https://jsfiddle.net/1b68eLdr/70304/

## Steps to reproduce
Create 2 custom rectangles
Select both of them 
Copy and paste

## Expected Behavior
Duplicate the selection

## Actual Behavior
Cloning fails at  klass.fromObject(o, function (obj, error) { as getKlass return null

**Comment by gaooyao** [comment]
Fabric will create a new idRect object when clone. but the fabric.idRect can't be find because it is not be difined . So you should change the code like this ' fabric.IdRect = fabric.util.createClass(......)'. Second the "'type: 'idRect'" is not support,it should change to "type: 'IdRect'".I am sorry with wrong grammar because I`m a Chinese.
[https://jsfiddle.net/1b68eLdr/70718/](https://jsfiddle.net/1b68eLdr/70718/)

**Comment by cybrooke** [comment]
@gaooyao Thanks for your answer. It seems like fabric.idRect works fine. Do you know how this could be done in typescript without getting  Property 'idRect' does not exist on type import ...
As for your second point, there should be no problem starting with a lower case (there's an example in the tutorial).

**Comment by cybrooke** [comment]
I figured out I could assign it to a variable of type any to bypass the type system.
`var Fabric: any = fabric;
Fabric.IdRect = fabric.util.createClass(fabric.Rect, {`
