### ISSUE TITLE
Feature: Full Tutorial Projects to complement Demos are needed

### ISSUE THREAD

**Issue by tamusjroyce** [fabricjs/fabric.js#5233]
## Version
2.3.5

## Test Case
User audience is novice and just learning Javascript

## Steps to reproduce
1. git clone https://github.com/fabricjs/fabric.js.git
2. Search for examples or template folder

## Expected Behavior
Download pre-built templates from github or elsewhere

## Actual Behavior
Only code segments exist through the website. There are no full-fledge, pre-built examples to support the demo's and tutorial. It would also be nice to expand the tutorial with common IDE's such as Atom, Visual Studio Code, or Brackets.

I apologize for this being a non-technical feature request. I feel this project could have gained a huge amount of tracking years ago. And I still think it can.

React js, Angular js, and Iconic are good examples how using quick to use template really gets people on-board, and speeds up development and adoption of libraries. This is a great library! Thank you for all the work you have put into it!

**Comment by ncou** [comment]
My 2 cents opinion : Not really sure some examples integreated with React/angular/iconic could help the visitor to understand how to use the library, it will obfuscate the code with some non relative library code, and fabric.js will look more complex to use.
But I also think the demos are not really easy to use because if you want to manipulate a bit the library you need to recreate the same demo in jsfiddle or codepen and start to play with it. 
A possibility to edit the demo on the fly directly in the siteweb could be a plus for the site.

**Comment by asturur** [comment]
What i wanted to do is make the demos available for direct edit on the website.
The problem is the time needed.

Full tutorials are not really that much, it depends on your project.
The fabricjs propject all start adding something on the canvas, since the highest used feature is interaction.

I would like to have a tutorial for a small game or for a weird website part with some display ( like music driven canvas animation or similar )

I agree current demos code is TERRIBLE and built for speed.
Demos/examples/ would probably stay on fabricjs.com more than on the repo, since there is a banner there that is the only active supporter of the library

(stickers, eventually money for bounties, shipping sitckers)

**Comment by tamusjroyce** [comment]
@ncou I agree. But I think I was misunderstood. The only thing I meant was that people jump on the React/angular/iconic/Express bandwagon because they are quick to install. And they have a blank template and a few example templates.

I personally disapprove of tying libraries into "frameworks." It should be the framework that incorporate and supports the library. But if Fabric.js is not popular enough, it doesn't seem like that would happen.

@asturur I don't see anything under demo's. But https://github.com/fabricjs/fabricjs.com/tree/gh-pages/docs has some great samples. There are a lot of extra blank lines. But otherwise, it looks clean and efficient. Exactly how you would want it. But there does not seem to be a link on the website nor in the library to it. It just isn't intuitive to download an entire sites source code to get the demos.

It looks like most of the work is done?
  1. https://github.com/fabricjs/fabricjs.com/tree/gh-pages/docs directory into its own repository.
      (Reason: 71MB -- 20 minutes for me to download and unzip -- is a bit too large)
  2. Change resource locations so opening the .html (offline) works. Like opening it directly in Firefox.

Again, @asturur, thank you for the location of the files. I will try playing around with them as time allows and see if I can't do my part to help complete this feature.

**Comment by tamusjroyce** [comment]
I was saying that fiddle.js can link directly to github. http://doc.jsfiddle.net/use/github_read.html

That would accomplish both. Plus, github supports forking repositories and pull requests. So it would be easy to pass cool things back into the site. And they would automatically be hosted on fiddle.js once you reviewed and pushed in the changes.

**Comment by tamusjroyce** [comment]
I have all the .html files downloaded into a directory. I am making progress on a nvm module that uses sanitize-html to convert a bunch of .html files into respectively named directories demo_[htmlFileName] with demo.html, demo.json, demo.cs.

Keeping the resources in the demos pointing to the original resources should allow them to be demo'd. Since the resources are essentially hosted online.

**Comment by ShaMan123** [comment]
https://github.com/fabricjs/fabricjs-react-sandbox

**Comment by ShaMan123** [comment]
better off #8135
