### ISSUE TITLE
fix(geometry): object bounding box, clip path taken into account

### ISSUE THREAD

**Issue by blobinabottle** [fabricjs/fabric.js#5275]
Hello, clipPath seems working pretty well (in canvas, I didn't test toSVG yet). But I think we should improve the way controls are displayed. For the moment it's like this:
![image](https://user-images.githubusercontent.com/8090162/46200839-f90ce680-c312-11e8-8b52-c52eba203ee5.png)

So boundaries are based on all objects inside the clipPath. 

But I think it makes more sense to only consider the clipPath for the boundaries:
![image](https://user-images.githubusercontent.com/8090162/46200761-c7941b00-c312-11e8-91a8-4efcde7e76f6.png)

But maybe I'm missing something.

**Comment by rikkarv** [comment]
Perhaps, when using "absolutePositioned", the present implementation makes more sense. 

For example the clipping area is positioned in top left of the canvas, however the clipped object is still in the center of canvas and i want to move it towards the clipping area. How could i drag him if the controls are in the clipping area?

@blobinabottle good point to bring this to discussion

**Comment by rikkarv** [comment]
Please look at issue #5266 and http://jsfiddle.net/utryjax4/85/ where we have a situation in which is needed controls to the full clipped object and controls to other object that marks the clipping area

**Comment by asturur** [comment]
there should be some logic that would be able to get the intersection between the 2 boxes.

The width and height is not the one or the other but is where they overlap.

While this could be still be done drawing the controls, i have no idea what happens when you want to scale something with this logic

**Comment by blobinabottle** [comment]
maybe using sectable true/false on clipping area and/or content?

**Comment by rikkarv** [comment]
Look at this [crazy implementation](https://jsfiddle.net/rikkarv/kanejp47/4/) inspired by @releasecreative issue #5266 and @TsuchiyaMasahiro idea of setting a interactive clipping fabric object.

It is possible to interact in many ideas with the clipping area (scaling, rotating, moving, stretching) on the second canvas.

It seems a little off-topic here but i think it's connected to @asturur reference to "_i have no idea what happens when you want to scale something with this logic_". Couldn't it be a workaround?

**Comment by ShaMan123** [comment]
This has been solved by #7858 
Make sure the clipped object is a group and set `layout: 'clip-path'`
#7868

**Comment by ierover** [comment]
@ShaMan123 It doesn't work in fabric v5.3
you can try here:
https://jsfiddle.net/1yjvLhbe/

**Comment by ShaMan123** [comment]
Layout management is a v6 feature

**Comment by ierover** [comment]
@ShaMan123 oh, the lastest version in [npm](https://www.npmjs.com/package/fabric) is still v5.3

**Comment by ShaMan123** [comment]
npm i fabric@beta

**Comment by ierover** [comment]
@ShaMan123 Thanks

**Comment by ierover** [comment]
@ShaMan123 Hi, ShaMan123, if the clipPath Object is a Rect and has a angle, the bounding box doesn't fit the clipped area, bcs Bounding Box doesn't rotate, try here:
https://jsfiddle.net/9pumzod5/1/

**Comment by ShaMan123** [comment]
#9148 fixes that - https://codesandbox.io/s/4vzfv4

**Comment by ShaMan123** [comment]
> This has been solved by #7858 Make sure the clipped object is a group and set `layout: 'clip-path'` #7868

This is outdated, look at  https://codesandbox.io/s/4vzfv4

**Comment by ierover** [comment]
> > This has been solved by #7858 Make sure the clipped object is a group and set `layout: 'clip-path'` #7868
> 
> This is outdated, look at https://codesandbox.io/s/4vzfv4

hi, Thanks for you replay.  But is there any way that i can make the Bounding Box exactly the same as the clipped area to minimize or trim the Bounding Box ?  Just like the picture below：

![clipPath](https://github.com/fabricjs/fabric.js/assets/31580492/c90c7278-bbe2-4a2e-bb1e-b174b209348c)

maybe it's what more developer want i think,because it won't affect user to click their target object

**Comment by ShaMan123** [comment]
There is
You will need to subclass the layout manager and clip path strategy probably

**Comment by ierover** [comment]
> There is You will need to subclass the layout manager and clip path strategy probably

oh, that is great... I have been troubled by this problem for several days😇   and don't know how to resolve. is there any example? I would be grateful  🥹

**Comment by ShaMan123** [comment]
No there isn't.

**Comment by bitttttten** [comment]
Is there a different solution for fabric6?

**Comment by asturur** [comment]
i guess it could be implemented, but in this moment i m not adding features that touch the core API because the documentation of the exising API is not good enough.

**Comment by bitttttten** [comment]
so there is a way to do this in js userland already?
i have seen some fabric apps that have this kind of feature implemented, although i am assuming they are not on fabric6 yet. although the code probably looks similar. so it is possible i am understanding, just not a core feature.

**Comment by asturur** [comment]
i think the simplest solution right now wouls be having the object in a group, alone, and set the clippath to the group. The group should also have a clippath layout manager instead of the standard one
