### ISSUE TITLE
convenient index control using tags

### ISSUE THREAD

**Issue by bjuriewicz** [fabricjs/fabric.js#5276]
I'm lacking a convenient way to control the stack order of similar objects, which for some reasons shouldn't be a fabric Group. It would be nice to have a function that would work like: 'hey, bring all the triangles in front of circles, but behind the squares', without having to group them in fabric.Group.

In my project, I handled this by adding a `tag` property to every object, and I created the following  function in `static_canvas.class.js`:
```    
    /**
     * Moves an object to level before the first occurence of tag
     * in stack of drawn objects
     * @param {fabric.Object} object Object to send
     * @param {String} tag Position to move to
     * @return {fabric.Canvas} thisArg
     * @chainable
    */
    bringBehindTag: function (object, tag) {
      var index = this._objects.findIndex(function(object) {
        object.tag === tag
      })
      removeFromArray(this._objects, object);
      this._objects.splice(index, 0, object);
      return this.renderOnAddRemove && this.requestRenderAll();
    }
```

**Comment by bjuriewicz** [comment]
Is closing tickets without any response a standard practice in this repo?

**Comment by asturur** [comment]
No is not, i confused this issue with the issue of this PR:
https://github.com/fabricjs/fabric.js/pull/5088
I'm sorry about that.

The problem is the same, we can't pull in every feature because it would be hard to mantain.
The code you wrote those no need to be internal in the core lib in order to work, so is ok as an application use case.

Most changes i want to pull in are about SVG compatibility, rendering speed and quality, code reduction, simplify usage of gradients,patterns,mask, make node render reliable.
Moving graphic filters to objects.

Outside those topics i want to pull as little as possible in order to keep the library manageable. I often feel is already out of control
