### ISSUE TITLE
Text background fill padding

### ISSUE THREAD

**Issue by Fandangi** [fabricjs/fabric.js#5328]
Hi - great product. 

On SO someone asked about how to get the textBackgroundColor to include padding per line of multiline text - specifically NOT as a padding to the bounding box of all lines in the text.  See the post here for images of what I mean: https://stackoverflow.com/questions/52903599/line-by-line-text-background-color-padding-in-fabric-js-canvas

It seems like a common use case to desire padding around text in general, but also to be able to have the background color tight to the text in a multiline case.

The solution in the SO case involves getting the text lines info from a dummy text object and calculating positions for a background rect from that. 

Any chance you could consider adding a feature ?

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/47311581-71c54100-d63a-11e8-9a54-edb954c92788.png)

this is the default behaviour of text. what is wrong with it?

**Comment by Fandangi** [comment]
Hi - nothing wrong with the excellent fabric.js. However, your example is on the left - I have edited this by hand to add padding around the text.  This is the requirement I am trying to convey. Thanks

![image](https://user-images.githubusercontent.com/16245859/47312574-a7ffc200-d634-11e8-88c4-e6fb6db1519d.png)

**Comment by friday** [comment]
I agree, and like the fact that this issue hasn't been closed like the other three. I think this is the expected behavior. There may be some reason I haven't considered though (besides backwards compatibility).

This is how you can override fabric to do what you want:
https://codepen.io/fullkornslimpa/pen/XyOOKR/?editors=0010

**Comment by asturur** [comment]
I have been busy a bit ( i still am) was unclear from the issue, what `tight to the text` meant. Looked like that there was no padding at all, hence my `what is wrong with it`.
There is no easy way to do what you wanted, this is something you should obtain with custom code.
If you did not solve, please open a stackoverflow question that relates to your problem and ask for an answer, someone will help, or maybe i can try a small snippet there. And post the question here in this issue.
But you have to start with an active snippet and not a link to a fiddle.

**Comment by Fandangi** [comment]
Hi Andrea – forgive the late response, I have been travelling.

I will consider the requirement and may post a further SO question, however I already provided a custom solution in answer to another OP’s question.  I opened a query on your git because I felt this was a common requirement that fabric should address. I appreciate the need to critically decide what features to include and which to leave to custom code to, so your answer is fine.

Kind wishes

James

**Comment by Fandangi** [comment]
Understood.

**Comment by hags033** [comment]
I would like to know if you have considered or would consider expanding Object Options padding, or allow extending per object type, Padding between object and its controlling borders (in pixels), to include 4 numbers (like css shorthand) for padding instead of 1 number for all 4 sides. Basically support padding: 1 number for all sides, as well as an array of 2, 3 and 4 numbers that follow css shorthand for: 4 numbers = top, left, bottom, right. 2 numbers = top/bottom and left/right etc. This would allow text to be able to have custom size boxes for background colors or whatever it needs, with the ability to move the text inside the bigger box by adjusting the padding on a side.

**Comment by asturur** [comment]
padding would not extend the backgroundColor or the textBackgroundColor area.

**Comment by DineshCodeFlow** [comment]
> padding would not extend the backgroundColor or the textBackgroundColor area.

https://github.com/fabricjs/fabric.js/issues/5328#issuecomment-455775051

Ideal it does by the definition!
