### ISSUE TITLE
Safari - free drawing brush is cut flat sometimes, even with strokeLineCap = 'round'

### ISSUE THREAD

**Issue by carterw485** [fabricjs/fabric.js#5330]
## Version
2.4.0

## Test Case
http://fabricjs.com/freedrawing - open this on safari, draw horizontal lines until one is flat on the starting side. Seems to happen more often when drawing from right to left, but the starting circle ends up being cut in half sometimes.

## Information about environment
Which browsers?
Safari

## Steps to reproduce
 Under 'Test Case'

## Expected Behavior
Brush strokes are always round on both ends

## Actual Behavior
Brush strokes sometimes become flat on the starting end

**Comment by asturur** [comment]
this happens when the stroke movement at the end or start bend on itself.
because you click at X, you briefly go to X-0.1, the proceeds to > X.
I think is an hardware acceleration problem for which i can do nothing.

the strokeLineJoin ( that i think is responsible for the effect ) is already set to round.
