### ISSUE TITLE
 Modify brightness by filter is not work in fabric v2.3.5 ?

### ISSUE THREAD

**Issue by MingyueSun** [fabricjs/fabric.js#5361]
I wrote a method to modify the brightness of the child component in the parent component of react. The brightness was successfully added to imageData.filters, but the brightness of the image did not change.What should I do ? The code like this:
![image](https://user-images.githubusercontent.com/31138694/47836096-d2464200-dde1-11e8-996b-0496c2b3d092.png)

**Comment by MingyueSun** [comment]
@kangax @davidjrice @maxim @seanhussey 
Can you help me?

**Comment by asturur** [comment]
Hi @MingyueSun, please replicate the problem in plain js on a js fiddle. If you can change the brightness of a backgroud image with a normal slider, then the problem is likely in your react code.

Could be a caching issue of some sort. Did you enable caching for images? is enabled by default in 2.4.0 unsure if it is in 2.3.5
Also applyFilter should reset the cache anyway.
