### ISSUE TITLE
how to apply filter for pattern (image) in path or  text 

### ISSUE THREAD

**Issue by sbala69gmail** [fabricjs/fabric.js#5368]
I would like to apply filter for a pattern in text or svg path which is filled with image.
ref :  http://fabricjs.com/patterns.

@asturur @kangax

**Comment by sbala69gmail** [comment]
Can someone  help me out of this

**Comment by asturur** [comment]
With the current pattern api this is not really easy.
You can create a custom pattern made with an image and filter it.

Create a fabric.Image with the image you want.
Apply filter to it.
Create a pattern passing as element the fabric.Image._element. This should do it.

Each time you want to change the filter, create a new pattern since the old pattern will just have a reference to the old filterImage and not the new one.

**Comment by asturur** [comment]
We can continue the discussion here, but as said many time, this is food for stackoverflow.
Is ok to post a reference to a question here, but not the question itself.
