### ISSUE TITLE
Programmatic ActiveSelection does not behave identically with mouse click selection

### ISSUE THREAD

**Issue by iongion** [fabricjs/fabric.js#5377]
## Version
2.4.0

## Test Case
https://jsfiddle.net/3kqeoyuw/44/

## Information about environment
Browser
Chrome

## Steps to reproduce
1. Click the create button - you will see a circle added and a log with created object position:
```{"name":"my-obj","top":30,"left":30}``` 

2. Click select to programmatic select last created object - the object will be selected and the log will show:
```{"name":"my-obj","top":-40.5,"left":-40.5}``` 

3. Click anywhere in the canvas to clear selection then click on the last created object - the log will show:
```{"name":"my-obj","top":30,"left":30}```

## Expected Behavior
Position should be ```{"name":"my-obj","top":30,"left":30}```

## Actual Behavior
Position is ```{"name":"my-obj","top":-40.5,"left":-40.5}``` 

_Shouldn't programmatic select have the object report the same `top` and `left` coordinates - now, when a programmatic selection is made, the object has wrong positions_ ?

If one traverses the nodes using `this.canvas.forEachObject` then the selected node (by programmatic selection) will have unexpected coordinates, can this be avoided ?

**Comment by mohamediburan** [comment]
Inside this section,
`canvas.on('selection:created', function(event) { 
	const selection = canvas.getActiveObject();
  if (selection.type === 'activeSelection') {
    selection.forEachObject(obj => {
      reportDiv.innerHTML = JSON.stringify({ name: obj.name, top: obj.top, left: obj.left });
    });
  } else {
     reportDiv.innerHTML = JSON.stringify({ name: selection.name, top: selection.top, left: selection.left })
  }
});`
On if condition, you are checking for the left, top and name of the objects inside the selection and in else condition you are checking for the name, top and left of the selection not the objects inside. If i am not wrong, selection works a lot like group. Objects are placed relative to the center of the selection. So, left, top values are calculated in relation to the center of the selection that's why you are getting different values.

**Comment by iongion** [comment]
@mohamediburan you are right, closing this
