### ISSUE TITLE
Selection objects bug. When we select only text another object will stay selected

### ISSUE THREAD

**Issue by AlexSergey** [fabricjs/fabric.js#5401]
## Version
2.4.3

## Test Case
http://jsfiddle.net/w3c2rktf/1/

## Information about environment
all browsers

## Steps to reproduce
When we selected only Text onSelect will fire for both objects. After that both of objects have been active. In version 2.4.2-b this worked fine.

## Expected Behavior
We need call onSelect only one for iText

## Actual Behavior
Both of objects have been active.

**Comment by asturur** [comment]
Can you first explain me what seems a bug to you? i see weird things like the missing of a `onDeselect`.

onSelect and onSelect are not callbacks but are function supposed to avoid deselecting or selecting items.
If they return true with come condition, the process of selection or deselection will be stopped.
Are not supposed to be used as counters or to set properties, they can be called in more places than you expect.

**Comment by AlexSergey** [comment]
In my case I need to set "active" state to object when it will be select. I rewrite these two methods "onSelect", "onDeselect" for this behavior.

`
fabric.Object.prototype.onSelect = function() {
    console.log('select object ', this.id);
    this.active = true;
};
fabric.Object.prototype.onDeselect = function() {
     console.log('deselect object ', this.id);
    this.active = false;
};
`

How can I do that correct way?

**Comment by asturur** [comment]
i ll pull up an example. should be doable with the selection modified event.

**Comment by asturur** [comment]
if you check in the canvas.class.js this code:

```javascript
      if (oldObjects.length > 0 && objects.length > 0) {
        opt.selected = added;
        opt.deselected = removed;
        // added for backward compatibility
        opt.updated = added[0] || removed[0];
        opt.target = this._activeObject;
        somethingChanged && this.fire('selection:updated', opt);
      }
```

when `selection:updated` is fired you get the selected and deselected array.
Looping over that arrays you can set active true,false on them.

```javascript
canvas.on('selection:modified', function(opt) {
  opt.selected.forEach(obj => obj.active = true);
  opt.deselected.forEach(obj => obj.active = false);
});
```

The event `selection:modified` has been enhanced to give more visibility on what happens when user click around and let you intervene with custom code, while the onSelect, onDeselect callbacks are used to stop standard fabric flow.
Before onSelect and onDeselect you would deselect or select object from user action without ability to interrupt and then you should counter act the effect with custom code, with events fired every time.

**Comment by AlexSergey** [comment]
Thank you! It became clear to me. I will try to implement it soon
