### ISSUE TITLE
load svg image as url

### ISSUE THREAD

**Issue by daniEDIT** [fabricjs/fabric.js#5449]
Hello,

I add a svg images to a fabricjs canvas with his code:

          var url = site_url;
          fabric.loadSVGFromURL(url, function(objects, options) {
              var obj = fabric.util.groupSVGElements(objects, options);
              canvas.add(obj);
              })
          

Using this code inserts the svg paths directly into the json, when saved.
          

{"type":"path","version":"2.4.3","or ...............,"path":[["M",40.06,12.76],["L",35.24,7.94],..LOT OF CODE HERE

when I insert a jpg, png image with this other code etc..

        fabric.Image.fromURL(url, function(img) {
              canvas.add(img.set({..........

The image is inserted as image type, and accesed by url. ( a lot of less code)
{"type":"image","version":"2.4.3","............e,"src":"/editor/user_files/2018/10/18/7/4/742671b07868f310d5834faf62d93d7f.jpg",

The problem with svg system is that we cannot control what is the origin of the svg, becouse is codded into the json, and we lost the url when inserting.

And If we clone a svg 20 times in the same canvas, the code is repeated 20 times(imagine a svg of 500kb...)
If there where linked by the url like images, there is only one load of the external image.

Is there any way to insert the svg into the canvas using linked method like jpg images with the url??

Becouse fabric.Image.fromURL doen't works for svg.

Thanks a lot!

**Comment by asturur** [comment]
So adding as a SVG as an image should work and should give you vector scaling without problem ( maybe the problem is in the SVG itself missing width/height? ).

Loading the SVG as an image won't give you access to paths and modification in fabric code.

There should be a way to save the canvas `.toDatalessJSON` preserving the SVG link rather than the svg objects in full. I do not remember if it works in all conditions. Please setup a working fiddle we can discuss bugs/solutions.
