### ISSUE TITLE
Resizing objects with a clipPath gives blurry edges

### ISSUE THREAD

**Issue by matrei** [fabricjs/fabric.js#5494]
## Version
2.6.0

## Test Case
https://jsfiddle.net/mattiasr/h7t6yp8d/12/

## Information about environment
Nodejs or browser? Browser
Which browsers? Chromium, Firefox

## Steps to reproduce
Resize the object in the fiddle quite a bit larger.

## Expected Behavior
The edge of the circle gets redrawn to be sharp

## Actual Behavior
The edge of the circle stays blurry

**Comment by asturur** [comment]
yes this is a known missing thing, i ll work on it as soon as i close a couple of bugs.
The clipPath cache does not take care of the parent object scaling.

**Comment by asturur** [comment]
@blobinabottle

**Comment by blobinabottle** [comment]
Thanks! I'll dig a bit in the code... Maybe I can find a (weird? :-D) solution or workaround.

**Comment by asturur** [comment]
maybe the error is in me wanting to use objectCaching on the clippath object. If cache is invalidated, we should be ok not checking inf the clippath is still valid and just recalculate it and redraw it.

**Comment by satendra02** [comment]
I am facing the same problem. Is this issue fixed? or any workaround?

**Comment by asturur** [comment]
not yet, is an hard fix somehow.

**Comment by maksym-plotnikov** [comment]
Ww're facing the same problem then I have a video/image with clipPath and it's scaling inside this clipped area. So there's a "jittering"(trembling) effect during animation. Check next video:
https://drive.google.com/file/d/1hGr1NyJtM17o8Z_8rRxYDAhPXycIMhvV/view?usp=sharing

Really looking forward for fix from @asturur or maybe You have an idea why it is behaving like this and give us a clue how we can fix it by our own.

**Comment by asturur** [comment]
Probably as soon as i merge the pr for masks i can see if i can generalize a fix for both.

**Comment by besworks** [comment]
I came up with a quick and dirty workaround for this issue that may be helpful to somebody out there. This won't work properly if you have a stroke applied to your object but it's better than nothing and suits my purposes.

What I've done here is: every time the object is scaled, it is resized based on the new scale and then the clipPath is recalculated. I've used an Ellipse instead of a Circle to preserve the ratio. I haven't looked into using any other shapes but the principle might hold up.

`
function clip() {
  let obj = canvas.getActiveObject(); if (!obj) { return; }
  obj.width = obj.width * obj.scaleX; obj.scaleX = 1;
  obj.height = obj.height * obj.scaleY; obj.scaleY = 1;
  let rx = obj.width / 2; let ry = obj.height / 2;
  obj.clipPath = new fabric.Ellipse({
    rx: rx, ry: ry, originX: 'center', originY: 'center'
  }); obj.dirty = true; canvas.renderAll();
  let reClip = function() { obj.off('scaled', reClip); clip(); }
  obj.on('scaled', reClip);
}
`

**Comment by asturur** [comment]
i know a lot of time passed, but i finally decided to see if i can fix this.

**Comment by rubenlagatie** [comment]
Any update on this? Thanks.

**Comment by svdwyer** [comment]
@asturur
Hi, is there any progress on this issue? I'm using the latest version (5.2.1) but I'm also having this problem.
Is there a fix or a work around? Thanks

**Comment by therealtimhawkins** [comment]
Hey, I'm also having this issue. I'm trying to clipPath an object with a stroke applied and having the same scaling issue. Struggling to figure out a workaround so all ears if anyone has any ideas!

**Comment by Webben47** [comment]
Hey, I'm also having this issue. The edges of the clippath (svg on text) are blurry when the object is exported with multiplier property of toDataURL(). Please fix! Do you have any information about which part of the library you need to change to solve the problem? Kind regards

**Comment by Webben47** [comment]
This is an isolated example, hope this helps: `<!DOCTYPE html>
<html>
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/5.3.0/fabric.min.js"></script>
</head>
<body>
  <canvas id="canvas" width="1400" height="400"></canvas>
  <button id="applyClipPath">Apply Clip Path</button>
  <button id="downloadImage">Download Image</button>
  <script>
    // Create a Fabric.js canvas
    let canvas = new fabric.Canvas('canvas');

    // Function to add text with a custom font
    function addTextWithCustomFont() {
      const text = new fabric.Text('Custom Text', {
        left: 50,
        top: 50,
        fontSize: 230,
        fontFamily: 'CustomFont', // Replace 'CustomFont' with your font-family name
      });
      canvas.add(text);
    }

    // Function to apply an SVG image as a clip path
    function applyClipPath() {
      fabric.Image.fromURL('background-form.svg', function (img) {
        canvas.clipPath = img;
        canvas.renderAll();
      });
    }

    // Event listener for the "Apply Clip Path" button
    document.getElementById('applyClipPath').addEventListener('click', function () {
      applyClipPath();
    });

    // Event listener for the "Download Image" button
    document.getElementById('downloadImage').addEventListener('click', function () {
      const multiplier = 10; // Change this multiplier as needed
      const downloadLink = document.createElement('a');
      const filename = 'canvas_image.png';

      let data = canvas.toDataURL({
        format: 'png',
        multiplier: multiplier,
        quality: 1,

      });


          downloadLink.href = data;
          downloadLink.download = filename;
          downloadLink.click();
    });

    // Call the function to add text with a custom font
    addTextWithCustomFont();
  </script>
</body>
</html>
![canvas_image (1)](https://github.com/fabricjs/fabric.js/assets/53402640/d73a5070-1f02-40fd-837f-974cdf6fe022)
`

**Comment by ShaMan123** [comment]
Turn this into a wirking live repro in codesandbox
We have links available in the repo under issues > new
SVG is sharp because it is vector drawing
Canvas is pixel drawing, so indeer sharpness is an issue.
Currently fabric caches an object with a clip path because there is not mechanism for context isolation rendering (clipping, masking etc.)
