### ISSUE TITLE
Free drawing on hover vs on mouse down

### ISSUE THREAD

**Issue by mrkylemac** [fabricjs/fabric.js#5520]
Hi there! 

I'd like to freedraw when someone hovers over the canvas, without having to click — Is this possible?

Thanks!

**Comment by asturur** [comment]
Maybe yes, unsure how much would it be change-proof since is not a feature.
Can we handle this on stack overflow, and then if some library problem surface, we move it back here?
If you could start a SO question with an empty working fabricJS fabric canvas we can start from there.
Using the SO snippets.

**Comment by asturur** [comment]
issue will be temporary closed.

**Comment by mrkylemac** [comment]
Thanks @asturur.

Here we go! 
https://stackoverflow.com/questions/54622125/fabric-js-freedrawing-on-hover-of-canvas-instead-of-click-mouse-down

**Comment by asturur** [comment]
@mrkylemac i did not had time to handle most of the issues this months.
I kept them in the inbox to go over them later. did you ever find a satisfying answer?

**Comment by mrkylemac** [comment]
Yes, the above StackOverflow link was a perfect solution! @asturur
