### ISSUE TITLE
Load SVG as clipPath with border

### ISSUE THREAD

**Issue by jrodrigo0809** [fabricjs/fabric.js#5533]
I need to delimit the canvas with an SVG. Before I had it with clipTo and it worked fine, but we have updated the version to the 2.3.4 of Fabric.js and clipTo no longer works, and recommend ClipPath. When doing it with ClipPath it does it correctly, but the border does not paint it. We need to delimit the edges to highlight the editable zone.

My result with Fabric version 1.6:
![image](https://user-images.githubusercontent.com/17614987/53078608-dca55c80-34f4-11e9-82a5-ba1762289ba1.png)

My result with Fabric version 2.3.4 and clipPath:
![image](https://user-images.githubusercontent.com/17614987/53078659-f9da2b00-34f4-11e9-9472-02552afb9c78.png)

As you can see, it does not paint the edges of the limits, although it does.

How can I perform this functionality with the new version of Fabric?

I have a JSFiddle with a circle of clipPath to test, without getting to add a border.

https://jsfiddle.net/jrodrigo0809/43p28k6o/5/

**Comment by asturur** [comment]
https://jsfiddle.net/7rq49xn5/

this is one way, adding the clipPath to the canvas too but as non evented ( so users cannot click it at all ).

The point is that the border will be always under the image and never on the image. Well to be honest half of the border will be always cut way.

I'll close the issue since this is request for help. Not that i won't help, just i cannot leave it open as an open issue to address, since it is not.
