### ISSUE TITLE
loadSVGFromString adds strokeWidth to text objects

### ISSUE THREAD

**Issue by rikkarv** [fabricjs/fabric.js#5534]
## Version
2.6.0

## Test Case
https://jsfiddle.net/fuL39810/3/

## Information about environment
Browser - Chrome

## Steps to reproduce
In console log we can see that the object has been created with stroke width set to "1" and by clicking in the button (reset stroke width to 0) we see the text in Canvas changing place. I think that this only happens with text objects imported from svg.

## Expected Behavior
The object should have stroke width = 0?

## Actual Behavior
The object has stroke width = 1

**Comment by asturur** [comment]
This is expected, since the stroke contributes to the object size.

If you want to avoid this, you need to read the center of the object before setting the stroke and then setting it back. Or you can work with originX and originY set to center.

to read the center

`var point = Object.getCenterPoint()`
to set it back where it was:
`Object.setPositionByOrigin(point, 'center', 'center')`

**Comment by rikkarv** [comment]
Thank you for your explanation. Sorry for the inconvenience
