### ISSUE TITLE
Shadow clipping issue

### ISSUE THREAD

**Issue by anthify** [fabricjs/fabric.js#5547]
## Version
2.4.0

## Test Case
[http://jsfiddle.net/a5v3wgLc/](http://jsfiddle.net/a5v3wgLc/)

## Information about environment?
Chrome & Safari

## Steps to reproduce
Create two shapes (rectangles). Set shadow to shape 1, set shape 2 as the `clipPath` for shape 1. 

## Expected Behavior
The shadow to be clipped at the same position as the shape.

## Actual Behavior
The shadow is not clipped.

## Visual Example
![2019-03-03 11 23 03](https://user-images.githubusercontent.com/11407171/53694553-74823080-3da8-11e9-961e-d7cfcebf5e9b.gif)

**Comment by asturur** [comment]
I would classify this has a wrong expectation.

ClipPath for the object will clip the object, not the shadow it project on the canvas.
For this kind of thing use the canvas clipPath:

http://jsfiddle.net/3rexhqj1/

The absolute clipPath exists because someone could want to define a different clipPath for each object on the canvas ( imagine a grid in which each object can be confined just in one place of the grid ). But in that case the shadow from the object will be projected anyway.

**Comment by asturur** [comment]
Please feel free to continue talking about this, the issue is closed because there is no action item. And can be reopened.

**Comment by anthify** [comment]
@asturur perfect, thank you so much 🙏
