### ISSUE TITLE
Paths not visible on canvas

### ISSUE THREAD

**Issue by morrowsend** [fabricjs/fabric.js#5578]
## Version
1.5.0 and higher

## Test Case

- You can [test the different libraries in this example](https://jsbin.com/pebumonike/edit?html,js,output)
- [Original example code used 1.4.0](https://jsfiddle.net/GarryPas/6FdzK/)

## Information about environment
Chrome Version 72.0.3626.121 (Official Build) (64-bit) Windows

## Steps to reproduce
You can comment and uncomment each specific version
Click on the canvas to draw a path with endpoints when you click again. Doubleclick to exit drawing mode. Check the console to see the same type of data being written to the path. I don't believe this is the same issue as in [3859](https://github.com/fabricjs/fabric.js/issues/3859) because that seems to have been fixed.

## Expected Behavior
Path should be visible when using the newer versions just as they are when using fabric.js v 1.4.13

## Actual Behavior
Nothing is visible on the canvas when attempting to draw

**Comment by asturur** [comment]
https://jsbin.com/dusociwaja/edit?html,js,output

We can't really try to adapt a 1.4.0 fiddle straight forward to 2.4.6

The main fix there is to disable objectCaching for the path you are creating.
Also you can use the native double click handler.

Next time for this kind of help, please add a stack overflow question and  post the link here rather than doing the question directly here.
