### ISSUE TITLE
free drawing eraser

### ISSUE THREAD

**Issue by ShahramCodeDeveloper** [fabricjs/fabric.js#5595]
hello
Please add a eraser of the free drawing to clear a part.

**Comment by melchiar** [comment]
See here: 
https://github.com/fabricjs/fabric.js/issues/5188
and here:
https://github.com/fabricjs/fabric.js/issues/1225
and Stack Overflow questions here:
https://stackoverflow.com/questions/19311038/fabric-js-eraser-issue-canvas
and here: https://stackoverflow.com/questions/53387010/how-to-implement-eraser-in-fabric-js

**Comment by asturur** [comment]
thanks!

**Comment by Madaoism** [comment]
@ShahramCodeDeveloper  #1225 
I just posted some sample code here (see the latest comment). It has some code that would allow you to create an eraser that would not erase the background image/color, since the 'destination-out' composition is only applied to objects and no the canvas.

Here's a codepen example to illustrate that it works (add some shapes, then erase them):
[](https://codepen.io/anon/pen/byPeNQ)
