### ISSUE TITLE
Lagging issue when dragging or zoom-in/zoom-out the images.

### ISSUE THREAD

**Issue by surajwaghmare** [fabricjs/fabric.js#5608]
I'm rendering a canvas with multiple images (near about 230 HD images). When I'm dragging or zoom-in/ zoom-out the image then it's shows some lagging.
After some time I visit same tab ( in idle mode) then the application hangs for a while.
I provide fiddle with this, please let me know where is the actual issue.
  
https://jsfiddle.net/surajwaghmare/9r504pbs/119/

I'm using fabric.js 2.4.6 version.

**Comment by asturur** [comment]
well:
![image](https://user-images.githubusercontent.com/1194048/55364757-36307c00-54e2-11e9-8f98-40a70344f5fb.png)

images of 30 megs look big to me.
Handling 230 HD image ( 20mb+ each ) yes can be slow.

The fiddle takes so much to start i cannot see anything on the screen. Can you provide a fiddle that is easier to consume?

**Comment by surajwaghmare** [comment]
Hi @asturur, 
Please refer the following fiddle URL .

https://jsfiddle.net/surajwaghmare/9r504pbs/129/

I added 150 HD images in this solution. Using Google Chrome browser for development. In future I'm adding total 400 HD images on HTML5 Canvas using Fabric JS.
Please let me know where we can improve performance.

**Comment by surajwaghmare** [comment]
@asturur  are you able to consume the above fiddle url ?

**Comment by surajwaghmare** [comment]
Hi @asturur,
How many HD images I can add using FabricJS on Canvas ? And not getting delay/lagging in operations ?
**I'm waiting for your reply ?**

**Comment by asturur** [comment]
Hey i'm sorry, too many emails and too many things to do, i do not have time for everything.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/55937351-0d725a00-5c39-11e9-83ad-386c9b33c6d7.png)

after 500 seconds ( 9 minutes nearly ) i loaded half of the images.

I believe you have to work with thumbnails first of all, plus you have to take in account those things:

```
        if (delta > 0) {

            const originalRender = fabric.Image.prototype.render;
            fabric.Image.prototype.render = function (ctx, noTransform) {
                console.time("originalRender start");
                if (!this.isOnScreen()) {
                    return;
                }
                console.timeEnd("originalRender start");
                return originalRender.call(this, ctx, noTransform);                
            };
        }
```
this is super wrong. On every mousewheel you are wrapping the render function with another render function. Indeed mine was wrapped like 1000 times.

FabricJS has already the `isOnScreen` optimization per object

150 images at 5400x3700 mean that the browser has to handle ar 20MPX 3000 mega pixels per render, and resize operation to draw a big image in a small space. Is a lot of stuff to execute at 60fps for a browser.

A canvas that is 2500px in height is 5000px on a retina screen, and is too big. You have to work with a canvas that is as big as the are a you see and handle viewport so that it scrolls like if it was bigger (like you are doing with the alt key )

if you take my example of your fiddle here:

https://jsfiddle.net/nthurbms/

you will see it is way smoother.

Another important thing is that if you come and ask for suggestions and help, you can't let me discover details of your fiddle, that fiddle is big and requires being read all from top to bottom, you have to help if you want to be helped.

The tab hangs when left idle, because browser is not going to do things where you are not there. It finish download let's say other 10 images, and when you come back it has to reorganize the canvas content. In meantime the canvas has been probably removed from your GPU memory and so you do not see anything anymore. Browser has to work in order to rebuild the visualization.
With a smaller canvas it happens less.

**Comment by asturur** [comment]
when images are properly loaded, the render cycle is very fast
![image](https://user-images.githubusercontent.com/1194048/55940250-069b1580-5c40-11e9-81bb-6c27040d3a9e.png)

when new images enter in the viewport, the browser after having loaded them, has to actually decode them and use them:
![image](https://user-images.githubusercontent.com/1194048/55940326-2df1e280-5c40-11e9-81ec-105af24dc0a3.png)

and as you see that takes time and is not fabricJS stuff.
(pink lines are renders, well spaced and short, image decodes freeze everything for a second )

When all the images are in GPU memory, if your GPU can keep them, everything is very fast and smooth.

But again, you have to work with smaller images and maybe swap them when zoom is high.
I m not sure what is your application doing so i cannot really suggest you what is the best way to do it. nor i want to enter in that topic.

**Comment by asturur** [comment]
Here is the chrome profile of me panning and zooming, you can inspect it and check it.

[Profile-20190411T100153.zip](https://github.com/fabricjs/fabric.js/files/3067564/Profile-20190411T100153.zip)

**Comment by surajwaghmare** [comment]
Thanks @asturur
