### ISSUE TITLE
Event before:selection:cleared doesn't receive the actual target

### ISSUE THREAD

**Issue by 0ro** [fabricjs/fabric.js#5616]
## Version
2.7.0
## Test Case
https://jsfiddle.net/DenBogdanov/9t0wdvs5/
## Information about environment
browser
## Steps to reproduce
Open console in jsfiddle, select two objects and then deselect them
## Expected Behavior
Event listener of _before:selection:cleared_ must to receive the ActiveSelection.
## Actual Behavior
Event listener of _selection:created_ receives in field `target` value of ActiveSelection, but event listener of _before:selection:cleared_ receives the first object of ActiveSelection.

**Comment by 0ro** [comment]
I don't understand why is in code this behavior with **currentActives[0]**
```javascript
    discardActiveObject: function (e) {
      var currentActives = this.getActiveObjects();
      if (currentActives.length) {
        this.fire('before:selection:cleared', { target: currentActives[0], e: e });
      }
      this._discardActiveObject(e);
      this._fireSelectionEvents(currentActives, e);
      return this;
    }
````

**Comment by asturur** [comment]
good  question. looks wrong to me.
I think the point is that in the moment the deselection happen, the active selection gets destroyed, the objects mutated back, and you are basically working on invalid targets.

The event should be fired with the current active selection, since we are releasing a breaking release i think we should fix this now.

**Comment by 0ro** [comment]
Great job!
