### ISSUE TITLE
resize image after clipping the image

### ISSUE THREAD

**Issue by binoy-neo** [fabricjs/fabric.js#5633]
I am using fabric js 2.4.6.when i try to clip an image with clip Path property I am facing the following issues

1.The Image is not resizing

2.Not able to move the clipped image

Pls check the fiddle.This is the code i am using

https://jsfiddle.net/binoy/3jp2a71w/

1.Clip image as a new object

2.crop the image size with respect to the clippath

Expected result

1.Add the original image to canvas

2.create a croppingArea rectangle and add it in canvas

3.use the respective left, top, width, height, scaleX, scaleY of croppingArea and the originalImage to calculate the the bounding coords of the cropped area in originalImage coordinates

4.create a cropedImage from originalImage where cropX, cropY, width and height are set by step 3

**Comment by melchiar** [comment]
This is really more of a stack overflow question. You shouldn't be using clippath for simple image cropping since it can be done by just modifying cropX, cropY, width, and height. If you're still stuck did you want to open a question on SO and link to it from here?

**Comment by binoy-neo** [comment]
can u please modify my fiddle and give me a updated one

**Comment by Tsunami2069** [comment]
I'm not 100% sure if that what i'm about to say is the true cause of your problem but I notice that you have the parameter absolutePositioned set to true.
This makes the clipping position, width & height be relevant to the canvas and not the object itself.
It will also make it so that when you move your image, the clipPath stay's stationary in that position on the canvas.

I think you'll have to set that parameter to false and change the clipPath's position to match the position of the cropping rectangle in relation to your image.

Also, yeah, cropX, cropY, width and height can only be used to crop as a rectangular shape.

**Comment by asturur** [comment]
@binoy-neo please this is best handled on SO. Open a question and link it here.
