### ISSUE TITLE
Moving rectangle corner along the two axis at the same time

### ISSUE THREAD

**Issue by emmanuelle** [fabricjs/fabric.js#5649]
Thank you developers for a great library!

I am building an image annotation tool (for building training sets for machine learning) which is based on fabric.js and react-sketch. Operators can mark object by drawing rectangles (Rect objects of fabric.js) as bounding boxes for objects of interest.

When operators draw a bounding box, usually they do a first rough rectangle and then they adjust the corners for a better fit. One thing which frustrates them is that it's not possible in one single mouse move to move a corner to its final position, you have to move along one axis first, then the other, using the handles at the middle of the segments (or maybe I missed something!). Dragging the corners directly only allows for scaling. Since annotating images is tedious and they have thousands to annotate, going to several mouse moves to a single one is a big deal for this application.

So I have two questions:
- are there some attributes of Rect which would allow moving a corner along the two axis? I looked at the documentation and I thought not but maybe I missed something.
- if it's not possible at the moment, could it be an interesting feature to implement, and is it easy enough that for example I could try to do it?

**Comment by asturur** [comment]
Hi @emmanuelle there is some embedded function and some option.

Canvas has 2 properties.
uniScaleTransform true/false that allows you to obtain the desired effect ( if i undestood correctly )
Also there is a uniScaleKey, set as default to shiftKey that when pressed during scaling allows you to do the same.

I'll close the issue since there are no action items, please feel free to continue posting.

**Comment by emmanuelle** [comment]
@asturur thank you so much this is exactly what I was looking for!
