### ISSUE TITLE
Top/left should not be possible when setting scaleX=scaleY=1

### ISSUE THREAD

**Issue by njofce** [fabricjs/fabric.js#5656]
## Version
2.4.0

## Test Case
https://jsfiddle.net/njofce/pxLvrzkf/9/

## Information about environment
Chrome latest version

## Steps to reproduce
Try scaling the object left,right,top & bottom.

## Expected Behavior
I think that the object should not move in this case.

## Actual Behavior
The object moves when scaling on the left & top.

**Comment by melchiar** [comment]
Could you explain what it is you're trying to achieve here? Currently, scaling from the top left corner is causing your group to move because your scaling event is setting the scale values back to 1, meaning the bottom right corner is having to collapse to maintain the group's scale. Keep in mind that the default origin is the top left corner so this behavior will change with a different origin.

**Comment by njofce** [comment]
@melchiar In my real case, I have additional logic inside the scaling event callback. I am actually scaling the objects inside the group, then setting the group scale X&Y to 1. I want to know whether it's a library bug or is there anything I can do to prevent the movement?

**Comment by asturur** [comment]
if you do something in the scale handler that modify object size you need to provide position on yourself. look in the source code for usage of 'setPositionByOrigin' to see how fabricjs does.
