### ISSUE TITLE
Need to add passive:false option for wheel event listener

### ISSUE THREAD

**Issue by vamzz1** [fabricjs/fabric.js#5710]
## Version
2.4.2-b

## Information about environment
ReactJS: 16.6.3
Google Chrome: Version 74.0.3729.157 (Official Build) (64-bit)

## Steps to reproduce
On rendering the Fabric Canvas I see this error log

[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

Then I sent addEventOptions {passive: false} as the fourth argument in this line https://github.com/fabricjs/fabric.js/blob/master/dist/fabric.js#L11077 by hard coding the argument in the library and that fixed the issue.

Without the `addEventOptions` options to wheel event listener there's an error log for each of the canvas that is rendered.

**Comment by vamzz1** [comment]
Please let me know if anything else is needed. Help would be really appreciated! I get a feeling I'm missing something really small but I'm stuck on this for the last 2 days. Thanks

**Comment by asturur** [comment]
hi @vamzz1 what you see is a warning log.
I think that warning, it just warns you that if you will put HEAVY js in the mousewheel event, that  generally is for scrolling, the scrolling may be affected in performance.

This happens becase a non passive event ( a norma one ) can cancel the scrolling and so scroll before starting has to wait for the event code to end.

Now we can assume that if you are using the mousewheel on fabricJS canvas you are not scrolling but doing something else, and so this warning is a warning without meaning for you.
Also setting the event as passive will let first the browser consume it, fire a possible `animation frame` and then execute the event, while since that event contains fabricjs code, you probably want to first execute it and then render.

All this to say that i do not think that warning should be considered a problem at all.

**Comment by zhe-he** [comment]
After enabling all levels in the console, I discovered this warning.
I looked into the Chrome Blink source code and found that omitting the third parameter behaves the same as setting passive: false.
The only difference is that when the third parameter is omitted, the program calls UseCounter::Count() for metrics collection.
Therefore, I support the original poster's modification to add passive: false in order to remove the warning.

Below are the code details:

```ts
div.addEventListener("mousewheel", fn)   ->     PassiveMode::kNotPassiveDefault  
div.addEventListener("mousewheel", fn, { passive: false })   ->     PassiveMode::kNotPassive  
div.addEventListener("mousewheel", fn, { passive: true })   ->     PassiveMode::kPassive 
```
```c++
enum class PassiveMode : uint8_t {  
    // Not passive, default initialized.  
    kNotPassiveDefault,  
    // Not passive, explicitly specified.  
    kNotPassive,  
    // Passive, explicitly specified.  
    kPassive,  
    // Passive, not explicitly specified and forced due to document level  
    // listener.  
    kPassiveForcedDocumentLevel,  
    // Passive, default initialized.  
    kPassiveDefault,  
};  
```

Instances where both `PassiveMode::kNotPassiveDefault` and `PassiveMode::kNotPassive appear`:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/events/event.cc;l=242;drc=5cdefdec21f75a91f3a29ee7fe017ef5a6981236
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/events/event_target.cc;l=94;drc=5cdefdec21f75a91f3a29ee7fe017ef5a6981236;bpv=1;bpt=1
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/events/touch_event.cc;l=120;drc=5cdefdec21f75a91f3a29ee7fe017ef5a6981236;bpv=1;bpt=1

Instances where PassiveMode::kNotPassive appears alone (only set):
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/events/event_target.cc;l=1068;drc=5cdefdec21f75a91f3a29ee7fe017ef5a6981236;bpv=0;bpt=1

Instances where PassiveMode::kNotPassiveDefault appears alone (only for metrics):
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/events/touch_event.cc;l=156;drc=5cdefdec21f75a91f3a29ee7fe017ef5a6981236;bpv=1;bpt=1
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/events/wheel_event.cc;l=166;drc=5cdefdec21f75a91f3a29ee7fe017ef5a6981236;bpv=1;bpt=1
