### ISSUE TITLE
Best way of sponsoring?

### ISSUE THREAD

**Issue by marcohamersma** [fabricjs/fabric.js#5738]
Heya,
Wondering what's the best way of sponsoring this project and the people working on it? I found the [flattr](https://flattr.com/@kangax) and bountysource page, but I'm not sure if that is the best way. 

Perhaps it's also an idea to enable [GitHub Sponsors](https://github.com/sponsors) for this project?

Cheers,
Marco

**Comment by asturur** [comment]
Hi @marcohamersma, thanks for the question.
We do not have a best way to get sponsered. We do not have a way at all.

Our biggest sponsor is so far Shutterstock. I work there and getting an extremely fine work/life balance i got more time and will to work on this project. It does not sponsor fabricJS directly with money but so far it played a great role in the last 3 years.

Actually i m mantaining this mostly alone with some help from coworkers.

I was thinking to open a Patreon but i would feel like a commitment to produce some content there fro which i do not have much time.

We have an ADS on the website that produce around 100$ per month.

Giving money is nice for me, but is not that helpfull for the project.
Do you want to thank me? You can send me money or buy me something on amazon. That won't help the project much, will make me feel better.

Do you want to help the project grow and stay modern? You can either:
- Post bounties on particular bug you want to be solved or feature that are stopped since long
- Do something for the project, like write examples, tutorials,
- Put someone with design skills to make a new website that works with github pages

I'll enable github sponsor by the way.

**Comment by asturur** [comment]
I opened a patreon, just in case someone really feel like contributing something.

**Comment by tiesont** [comment]
Related? #671

**Comment by rikkarv** [comment]
> Hi @marcohamersma, thanks for the question.
> We do not have a best way to get sponsered. We do not have a way at all.
> 
> Our biggest sponsor is so far Shutterstock. I work there and getting an extremely fine work/life balance i got more time and will to work on this project. It does not sponsor fabricJS directly with money but so far it played a great role in the last 3 years.
> 
> Actually i m mantaining this mostly alone with some help from coworkers.
> 
> I was thinking to open a Patreon but i would feel like a commitment to produce some content there fro which i do not have much time.
> 
> We have an ADS on the website that produce around 100$ per month.
> 
> Giving money is nice for me, but is not that helpfull for the project.
> Do you want to thank me? You can send me money or buy me something on amazon. That won't help the project much, will make me feel better.
> 
> Do you want to help the project grow and stay modern? You can either:
> 
> * Post bounties on particular bug you want to be solved or feature that are stopped since long
> * Do something for the project, like write examples, tutorials,
> * Put someone with design skills to make a new website that works with github pages
> 
> I'll enable github sponsor by the way.

You forgot to say that you are a life saver

**Comment by asturur** [comment]
GITHUB sponsor is active and we also have a sponsor! 🎉 
The button is clear on top of the page, this issue can be closed.
