### ISSUE TITLE
touchevent ：Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by tczj199076** [fabricjs/fabric.js#5743]
## Version
3.1.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers? chrome,firefox

## Steps to reproduce
I use wacom，but the browsers renturn error 'Cannot read property 'x' of undefined'

**Comment by asturur** [comment]
hi, i do not have a wacom tablet, and i do not know how it works.
What kinds of events it generates?

**Comment by tczj199076** [comment]
> hi, i do not have a wacom tablet, and i do not know how it works.
> What kinds of events it generates?

I use the pen of wacom，draw in canvas，and it tips me Cannot read property 'x' of undefined，I use chrome，but when I set the mobile model of chrome，it works，I don't know why

**Comment by pinstripe-potatohead** [comment]
I am facing a similar issue. I deployed a fabricjs drawing application, which ,y users say works with mouse and touch devices, and with certain graphics tablets (like Wacom one), but not with others (eg, Wacom Intuos). 

Unfortunately, I don't have access to a wacom intuos device, so don't know what the issue is. Browser console doesn't seem to throw an error either. 

I'm using fabricjs 3.2.0, with pointer events enabled.

**Comment by asturur** [comment]
please check on #5785
