### ISSUE TITLE
Regression in Drawing => disappearing dots

### ISSUE THREAD

**Issue by niels-van-den-broeck** [fabricjs/fabric.js#5753]
## Version
3.1.0

## Test Case
https://codesandbox.io/s/dots-disappearing-9vll1

## Information about environment
Nodejs or browser?
Which browsers?

Chrome@latest
Others not tested

## Steps to reproduce

draw dots on attached sandbox

## Expected Behavior

dots stay

## Actual Behavior

dots go away at random

**Comment by asturur** [comment]
i inspected the objects, between one disappeared and one not disappeared there are virtually no differences.
I have no idea what is happening.
Your code is fine.

I wonder if is a mutation problem.
we are resetting points doing points.length = 0, i wonder if is better to assign a new array completely.
And also the decimation and the convert to pathData could happen on a copy of the dots rather than the actual array.

**Comment by paulconlin** [comment]
Not sure if it's related, but the drawing demo also has an issue the paths moving when committed to the second canvas.

**Comment by Zahin-10** [comment]
I have been using a really old version 2.4.1 this issue doesn't seem to happen over here and we have been running it in production for a while now.

**Comment by asturur** [comment]
I'll change some code to see if i can fix, but i still miss a way to replicate the problem fast. Sometimes i have to add hundreds of dots before seeing one disappear

**Comment by asturur** [comment]
Found the issue, pushing a fix and publishing.

**Comment by niels-van-den-broeck** [comment]
Thanks!

**Comment by niels-van-den-broeck** [comment]
> Not sure if it's related, but the drawing demo also has an issue the paths moving when committed to the second canvas.
> 
> http://fabricjs.com/freedrawing

I assume the version hasn't been bumped yet but this has already been fixed earlier
