### ISSUE TITLE
Canvas video flickers when seeked

### ISSUE THREAD

**Issue by stray-dev** [fabricjs/fabric.js#5795]
## Version
3.2.0

## Test Case
https://jsbin.com/wegehorebe/1/edit?html,js,output

## Information about environment
Chrome so far

## Steps to reproduce
Drag the range input on the fiddle to seek video and reproduce flickering.

## Expected Behavior
Video should play smoothly

## Actual Behavior
Video flickers whenever it's seeked

**Comment by asturur** [comment]
it flickers probably because the seeking is not done yet.
Setting the currentTime does not mean the data of that frame is ready to render.
Please use the seeked event to render your frames.

**Comment by luishdosreis** [comment]
> it flickers probably because the seeking is not done yet.
> Setting the currentTime does not mean the data of that frame is ready to render.
> Please use the seeked event to render your frames.

Hey @asturur thank you for you reply. I have tried using the `onseeked` event but it still flickers. Any other guesses?

**Comment by asturur** [comment]
https://jsbin.com/papobazadu/edit?html,js,output

1) remove the animation cycle completely. no automatic render all
2) oncanplay will trigger and start a requestRenderAll, then you will slide again and the media won't be ready anymore, so it will flicker. The solution is to use the syncronous render so that as soon as it is ready you have to render a frame. and the the next seek can happen.

Did not find a solution to allow for smooth seeking, ideally if you want to see most of the frames this is the best solution, you could also use something like debounce on requestRenderAll so that requestRenderAll gets really fired in the moment you stop seeking, but in that case you won't see any progress happening.

**Comment by asturur** [comment]
sorry this is the correct link:
https://jsbin.com/zuviley/1/edit?html,js,output

**Comment by stray-dev** [comment]
@asturur Amazing stuff man. Thank you so much for your reply. Just expanding a little further on the subject, I hope you don't mind. Would you have any idea why triggering `.play()` on the video element itself causes no flickering whatsoever but seeking does? Pardon my ignorance by the way.

**Comment by asturur** [comment]
i think the problem is that the resource not being drawable in some moments.
When you are in play, i **suppose** a frame gets read, and when is time to display it, it gets put in some buffer and the browser and drawImage can use it.

For some weird reason, as soon as you ask for a seek, this thing does not work untill the next frame you want is ready to be displayed ( after seeking and decoding in the file ).

it can either be that:
- implementation is the same, but something syncronize requestAnimation frame from fabricJS and the actual play of the video file in the backend of the browser.
- implementation differ for any reason, and they could let the last ready frame available till the seek was completed.

I think we can know only reading the original source code of the browser, the thing i cannot really do, both for skill and time required.

It could also be a choice because having the video always renderable would mean that you can get a set a `currentTime` and display a frame that is not the right one.
So being broken does not leave doubts that that is not the frame for `currentTime`

**Comment by stray-dev** [comment]
@asturur Got it. I found a palliative solution for the time being. Not entirely sure how good it is or if I'm doing it correctly but here it is. It involves essentially loading the video into another canvas and instead of drawing the video itself drawing the canvas (double buffering). The issue is now the external video canvas is likely being converted to an `Image` object behind the scenes before being drawn onto the main canvas and that operation causes some lag when scrubbing through the video timeline. No more flickering though. Also, the video's first frame doesn't get painted immediately.

https://jsbin.com/dogojusuve/edit?js,output
