### ISSUE TITLE
"path:created" handler receives wrong value

### ISSUE THREAD

**Issue by martynasma** [fabricjs/fabric.js#5799]
## Version
3.2.0

## Test Case
http://jsfiddle.net/eb6qc3oj/

## Information about environment
Any browser

## Steps to reproduce
Draw anything in drawing mode, then look at browser console.

## Expected Behavior
`path:created` event handler should receive an object of type `Event` with actual object located in `event.target`.

## Actual Behavior
Value passed into event handler is the object itself, not event object, which is inconsistent with other events.

https://github.com/fabricjs/fabric.js/blob/master/dist/fabric.js#L8897

**Comment by asturur** [comment]
So events in fabricJS are not all mouse events.
Events are supposed to give you hooks to write behaviour on special events that user may trigger without you knowing it.

In this case the events wants to give you the information that the path is created and give you opportunity to do something before is added to the canvas.

We can add more information, i m not against adding the event that generated it since is easily available there, but please provide some use case or example for what we can use it.

**Comment by SebastienEske** [comment]
I confirm!!
I have been struggling with this bug for a while now. I also added a related issue to the jsfiddle:
we can't hide the added path form the canvas.

**Comment by asturur** [comment]
if we want to have it consistent we can change it, but only with a major release.
We can create a new event and deprecate the old one.
From path:created to object:added directly since it seems more of a fit.
Need some thinkering.
