### ISSUE TITLE
在node中无法生成png图片

### ISSUE THREAD

**Issue by SureEnough** [fabricjs/fabric.js#5816]
node : v10.15.1
canvas : ^2.5.0
fabric : ^3.3.2

var fs = require('fs'),
    fabric = require('fabric').fabric,
    out = fs.createWriteStream(__dirname + '/helloworld.png');

var canvas = new fabric.StaticCanvas(null, { width: 200, height: 200 });
var text = new fabric.Text('Hello world', {
  left: 100,
  top: 100,
  fill: '#f55',
  angle: 15
});
canvas.add(text);

var stream = canvas.createPNGStream();
stream.on('data', function(chunk) {
  out.write(chunk);
});

![aa](https://user-images.githubusercontent.com/31834802/61843070-f9432780-aecc-11e9-8071-93e843dc280f.jpg)

**Comment by asturur** [comment]
i wish i coud help. What is the actual problem? can you explain?

**Comment by kadiks** [comment]
Well, I guess I have the same problem.

I'm on Mac with Node 10.16, fabric 3.3.2 and canvas 2.5.0 and when running this example from the documentation, the PNG is blank.

I tried to downgrade to node 8 and older version of both fabric and canvas.
When using canvas alone, or fabric client side, it works fine.

When running the first two lines to check the `typeof` canvas, it returns an object instead of the function.
But when I downgrade canvas, it returns a function. 

Is this code example still up to date?

**Comment by asturur** [comment]
oh i guess since fabric uses a delayed render as default, you have to call canvas.renderAll() before outputting.

Is this example on the website? if so needs a correction.

**Comment by kadiks** [comment]
Dude you rock. I created a pull request so someone else doesn't spend hours like me trying to figure this out ;)

I consider this closed. Thx!!!

**Comment by SureEnough** [comment]
@asturur   嗯,网上的例子加这个就可以了`canvas.renderAll()`

```
var fs = require('fs'),
    fabric = require('fabric').fabric,
    out = fs.createWriteStream(__dirname + '/helloworld1.png');

var canvas = new fabric.StaticCanvas(null, { width: 200, height: 200 });
var text = new fabric.Text('Hello world', {
  left: 100,
  top: 100,
  fill: '#f55',
  angle: 15
});
canvas.add(text);
canvas.renderAll();

var stream = canvas.createPNGStream();
stream.on('data', function(chunk) {
  out.write(chunk);
});
```
![image](https://user-images.githubusercontent.com/31834802/62016565-79c39a00-b1e5-11e9-80ac-148aab361427.png)
