### ISSUE TITLE
Cant align circle over polygon point

### ISSUE THREAD

**Issue by danielcarter131** [fabricjs/fabric.js#5842]
Hi could someone help me with transformations. I have listed the problem in more detail on stackoverflow and google group's with no answers.
The problem is me understanding the co ordinate system. When I try to add a circle over one of my polygon points it shows it offset visually but the coordinates are correct. If I zoom in   and do the same process the circle looks exactly right. 
I have done a fiddle to show as I find it difficult to explain. There are 2 buttons on the fiddle. Click corner button then the zoom button and see the position of the circle. Run the fiddle again and zoom first then add corner second. 2 different positions both matching coordinates. I need to exactly place a separate line or circle over of my polygon points but achieving this is quite difficult with fabric.

https://jsfiddle.net/bzk18L9r/6/

Many thanks for your time and hoping someone can answer as ive been 2 weeks battling my head on this one

**Comment by asturur** [comment]
https://jsfiddle.net/ghcvq1ft/

Hi @danielcarter131 , the calculation get complicated because of the change in strokeWidth you do on the zoom button.

I suggest you to set all the objects with originX/originY to center so that the repositioning of objects due to the change in stroke does not affect your calculation.

**Comment by danielcarter131** [comment]
Fabulous thanks for this very helpfull and simple fix
