### ISSUE TITLE
isPartiallyOnScreen method returns true when object place inside the canvas boundaries .

### ISSUE THREAD

**Issue by fawadmukhtar** [fabricjs/fabric.js#5878]
## Version
3.2.0

## Information about environment
On browser

## Steps to reproduce
If an object is placed in the center of the canvas then check that object like this centeredObject.isPartiallyOnScreen() then it returns true while centeredObject is not on the boundaries of the canvas. 

## Expected Behavior
In the above case, this isPartiallyOnScreen() method should return false instead of true

## Actual Behavior
isPartiallyOnScreen() returns true when an object is in the center of the canvas

**Comment by asturur** [comment]
can you provide a fiddle please? is unclear what object and how much big

**Comment by asturur** [comment]
reopening when we get a fiddle

**Comment by Delca** [comment]
@asturur I just encountered this issue, here is a fiddle that reproduces it
https://jsfiddle.net/6q7to13p/

![image](https://user-images.githubusercontent.com/6437965/84114440-4f7a7400-aa67-11ea-8be1-738ba3849f8c.png)

In this case the yellow and blue squares work fine, but because the red square contains the center of the screen, it is treated as being partially on screen even if it is smaller than the viewport itself.

**Comment by fawadmukhtar** [comment]
@asturur I have the same issue as @Delca mentioned in fiddle
