### ISSUE TITLE
rotate an entire canvas with Squares (300$ for whom solves the issue)

### ISSUE THREAD

**Issue by erosmontin** [fabricjs/fabric.js#5898]
## Version
3.4.0

## Test Case
https://jsfiddle.net/erosnitnom/gwfq725y/12/

## Information about environment
Html, angular js 

## Steps to reproduce
you can add a red square (RS) using the button 'Add' (they are randomly placed in the image), rotate the viewport (VP) with button 'Rot', rotate VP and group RS with 'Rot2'
## Expected Behavior
 After the rotation 
- all the RSs in the VP are rotated along with the VP and rendered.
- I can add new RSs.

## Actual Behavior
After rotation: 
- the RSs are not rendered correctly, some of them are not rendered at all.
- the bounding box of the RS keep pointing the top of the canvas (does not rotate).
- i can not add any new RS.

As stimulus to solve this 'issue' I'm offering 300$ (if this won't be a problem for the owner of the git)

**Comment by asturur** [comment]
@erosmontin  there is a viewport rotation PR opened since long, that could get some help getting to the finish line.
I do not exactly remember what were the show stoppers.

https://github.com/fabricjs/fabric.js/pull/4624

It is a feature we want, you can either contribute time to update to 3.x and finish it or if you want, money as gratitude when is done.

We currently have no great way to accept donations apart my paypal and the bounty tracker, that anyway has high cost in fees.

My personal experience with people jumping on PRs for money is that they are unwilling to comply with what it takes to get a PR in:
- code style
- agreeing with existent lesser than cool patterns
- write tests
- fix all the use cases the feature is introducing.

Of course maybe this time we find the good one.

**Comment by asturur** [comment]
@erosmontin did had time to look at the PR, did you find useful code?

**Comment by ShaMan123** [comment]
#7670 solves this out of the box by adding a `Layer` and rotating it instead of canvas.
[![Edit fabric_app (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fabric-app-forked-q7yq6w?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.tsx&theme=dark)
It has been a long while but you are more than welcome to sponsor the project.

**Comment by ShaMan123** [comment]
https://user-images.githubusercontent.com/34343793/163723845-baeba2a2-2f0e-4b02-8109-c9f62b3ff730.mp4

**Comment by erosmontin** [comment]
Thanks for your fix but we moved to konva long time ago.
I'm sure someone will stille benefits from your fix!
