### ISSUE TITLE
Disable events when using loadFromJSON

### ISSUE THREAD

**Issue by Aror** [fabricjs/fabric.js#5905]
Would be nice to be able to disable all or specific events when loading data from JSON onto canvas.

**Comment by asturur** [comment]
What kinds of events you mean?

**Comment by Aror** [comment]
All or specific events that are fired after canvas is loaded from JSON. Eg: object:changed @asturur

**Comment by asturur** [comment]
Does `object:changed` fire? i also do not remember what is it.
Something should be done to make loadFromJson more quiet if needed.
Would feel like describing your actual application use case and difficulties found so that we can argue on what make sense?

Is also requested by the issue template in some way.
A single line description for an issue often brings to questions.

With a full descriptiove issue and explanation we could jump to conclusion quicker.
🤷‍♂
