### ISSUE TITLE
Override Fabric Object

### ISSUE THREAD

**Issue by meron1122** [fabricjs/fabric.js#5972]
Hi!
I want extend fabric object(and all children component have this method/properties which i wrote.
I tried on top of my application similar to this(Typescript):

```ts
class MyObj extends fabric.Object {
    public myName:string;

    public doSth(): void {
    }
}
fabric.Object = MyObj;

```

How to properly override fabric object?

**Comment by asturur** [comment]
If you want to add a method to all classes, this is enough:

```
fabric.Object.prototype.doSth = function() {
  // `this` is bound to the instance.
}
```

No need to create an extra class.

I'll close the issue, conversation is open

**Comment by meron1122** [comment]
@asturur  I want a override a existign method too (For example add my logic to event handlers)

**Comment by asturur** [comment]
in that case:

const orginalMethod = fabric.Object.prototype.chosenMethod;

```
fabric.Object.prototype.doSth = function(...args) {
  // `this` is bound to the instance.
  // custom code..
  orginalMethod.call(this, ...args);
  // more custom code
}
```

I would not suggest overriding too much, depending on what you want to do, probably there is already a way to do so in the library.

**Comment by meron1122** [comment]
@asturur 
Thanks for response.
What i want to do:
* Add custom properties(CustomName) - And serialize, deserialize it
* Add custom method as you show above - I want make own event handlers(For example - define behaviour for item click) - and serialize/deserialize this information(In property for sample)

**Comment by asturur** [comment]
if you go throught the docs and examples you will see that there is a way to output custom properties with the standard code:
http://fabricjs.com/docs/global.html#toObject

For the `click` event you can just add as we do in the `_initInteractive` function, using 

```
upperCanvasEl.addEventListener('click', () => { .... your code ... })
```

I would not try to serialize behaviours since that is a security flaw and is probably unsuggested by everyone.

I made a plain es5 example, but of course this works with the standard javascript class notation from es6. I'm not sure is convenient to create new classes.

Please look in advanced for closed issues on how to serialize/deserialize custom classes.

**Comment by peteringram0** [comment]
@meron1122 Did you ever find a solution for this? Im also looking to do the same as its easier with Typescript and getting custom types rather than ES5. Thanks

**Comment by asturur** [comment]
The standard class notation should work well too.

**Comment by CarlosMaranje** [comment]
I'm working on a project where we want to extend the `fabric.Rect` class. We want to create a `customRect` object that will have multiple methods and properties that we constantly need to use in multiple sections of the app. So instead of modifying the original `Rect` adding a new object that we can easily recognize makes more sense to us. 

We've seen that it is possible to use `fabric.util.createClass` to create a new class but since most of the discussion we find around are  2 - 3 years old, we would like to confirm if it is possible to use the ES6 notation to extend an existing `fabric` object. Something like what @meron1122 is suggesting. We are also aware of issue #7596 so maybe this is planned / included ?

**Comment by NonStopTreasure** [comment]
Hello,i'm testing now Control object for dlb click and triple click on fabric4.
Does fabric4 has instrument to adding dblclick or tripleclick handler on control (like mousedown) ? Can i add this behavior to Control.prototype by own main.js by extend or only creating a new Class?
