### ISSUE TITLE
Fabric js language support

### ISSUE THREAD

**Issue by adatdeltax** [fabricjs/fabric.js#6019]
How many languages does fabric js support?

**Comment by asturur** [comment]
None and all.

There is no specific language support in fabricJS code.

There are 2 things that makes fabric compatible with a language that is not the basic 0-255 ascii letters based.

1 - the grapheme understanding, that fabric delegate to `fabric.utils.graphemeSplit` this function takes a string and returns an array of grapheme. There is a basic implementation in, but you are supposed to provide your own.

2 - the input method. Some languages, like chinese and japanese make use of composition, to hlpe in that fabricJS provides a positioned text area near the cursor in order to let the operating system being able to do what it wanted to do, to some extent.
