### ISSUE TITLE
SVG not loading from URL

### ISSUE THREAD

**Issue by khurramIlyas** [fabricjs/fabric.js#6044]
## Version
3.4.0

## Information about environment
Chrome browser 

## Steps to reproduce
```
var canvas = new fabric.Canvas('canvas');
var url = http://fabricjs.com/assets/182.svg

fabric.loadSVGFromURL(url, function(objects, options) {
    console.log('objects', objects);
    var obj = fabric.util.groupSVGElements(objects, options);
    canvas.add(obj).renderAll();
}
```

## Expected Behavior
SVG should be loaded into canvas
## Actual Behavior
What I got is an empty object in my canvas, which has nothing. I also did console log for objects array but that is also empty.

**Comment by 0ro** [comment]
@khurramIlyas I think this is not a bug and you have a problem with mixed content. Because in your example URL has a protocol `HTTP` and you made a request from `HTTPS`
I've tried to reproduce your steps in [jsfiddle](https://jsfiddle.net/DenBogdanov/fac4Ly6w/7/) and I got the next error:
```
Mixed Content: The page at 'https://jsfiddle.net/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://fabricjs.com/assets/182.svg'. This request has been blocked; the content must be served over HTTPS.
fabric.util.request @ fabric.min.js:1
```
And I tried to reproduce this behavior on my local machine from HTTP protocol and I got loaded svg without errors.
![image](https://user-images.githubusercontent.com/7969190/71248848-f5f18200-232c-11ea-95b7-a37e4b2cd4c0.png)
If I'm wrong, then describe the steps of reproducing the bug in more detail

**Comment by asturur** [comment]
http://fabricjs.com/test/svg_import/
That SVG is loaded in the visual tests at number 182. It works.
