### ISSUE TITLE
Rectangles are not drawn at the correct position

### ISSUE THREAD

**Issue by lcswillems** [fabricjs/fabric.js#6068]
## Version
3.6.0

## Test Case

This very simple code is not working correctly:

```js
const fCanvas = new fabric.Canvas('c');
fCanvas.backgroundColor = 'black';
fCanvas.add(new fabric.Rect({
  width: 100,
  height: 100,
  fill: 'red'
}));

```
It doesn't draw correctly the red rectangle:

![image](https://user-images.githubusercontent.com/5437552/71767029-6d1b3e80-2f07-11ea-859a-74b8f62ae806.png)

We should not see this black thin border on left and top sides.

To reproduce, execute this fiddle: https://jsfiddle.net/d1u63at5/

## Information about environment
Browser. Chrome 79

**Comment by asturur** [comment]
The positioning of the rectangle include their stroke.
By default every object has a stroke of 1 pixel, you can disable it per object or for every object if you act on the Object.prototype.

https://jsfiddle.net/57ednzL4/

**Comment by lcswillems** [comment]
Okay, thank you for the answer!

Why setting a stroke of 1 by default? It doesn't make sense for me and is very confusing because, by default, this border is transparent!

**Comment by asturur** [comment]
Because the library started with mirroring the SVG defaults long time ago. So that setting the properties of an SVGElement to a fabric object would automatically mirror the look.

in 1.5 we removed this for images, because the added blurriness was an headache for everyone, i m sure we would be better without it and adding it during svg import, but as today this change would break all the saved/restored design of applications based on fabricJS and is also easy to just read it somewhere

Now i could change it in 4.0 but i think the sets of changes we have for it are disturbing enough and i do not want to add this too.

For now this should be added to the list of common mistakes/problems here:
http://fabricjs.com/fabric-gotchas

**Comment by lcswillems** [comment]
Okay, thank you for this detailed answer!

I would like to thank you again for all the great work you did with this library. It is huge and helps me so much!!

**Comment by asturur** [comment]
You could open a PR on this file to add this to the gotcha list:
https://github.com/fabricjs/fabricjs.com/blob/gh-pages/posts/_posts/2019-08-26-fabric-gotchas.html

so you close the loop :)

I'm happy people like this old library,  is not a tech gem but has definitely its use cases that other do not cover.

**Comment by lcswillems** [comment]
I did a PR: https://github.com/fabricjs/fabricjs.com/pull/244
