### ISSUE TITLE
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

### ISSUE THREAD

**Issue by maxakash** [fabricjs/fabric.js#6107]
While using fabricjs library in Ionic 4 , i am getting the below every time I try to resize , drag an image.

Error
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

Please help me fix this issue.

**Comment by asturur** [comment]
I'm not sure exactly what ionic 4 is and why it complains.
Probably this is more an issue for Ionic develeopers?

FabricJS touchmove event can't be passive because it has to call `preventDefault` sometimes.

also the preventDefault message and warning is definitely over alarming, and is generally a suggestion for performances.

I'm very confused with our touch scrolling situation right now and i have no time to investigate, it could also be that if we do want to allow for touch scrolling, we can register the event differently.
