### ISSUE TITLE
Event for changing color (and other attributes) of an object?

### ISSUE THREAD

**Issue by maniac0s** [fabricjs/fabric.js#6151]
I have an event listener on my canvas that triggers on object:add, object:remove and object:modified. However for some reason "object:modified" doesn't trigger when I change the color of an object.

Is there a way to detect if an object has it's color set (furthermore other attributes like stroke, font size ect because none of them seems to trigger the modified event)?

This is how I set the color of the selected object:

    canvas.getActiveObject().set({"fill": color.hex});

Just checked the Documentation and it says, modified triggers on 

    object:modified — fired after object is modified (moved, scaled, rotated)

So is there a way to detect performing a .set() operation?

**Comment by asturur** [comment]
There are different way. Which of them i think are unnecessary.
One is enabling the stateful option, which is expensive, but will detect changes in properties that are part of an array.
http://fabricjs.com/docs/fabric.Canvas.html#stateful
![image](https://user-images.githubusercontent.com/1194048/74585750-83291e00-4fe0-11ea-8f67-676c6fafcd38.png)

Also thing that no user can call `set` without you to know, because you are the one that writes the code, so this event need is more a way you want to organize your code rather than something that is necessary. That does not mean is a bad thing, but you can work around it because you are in control.

Example, wrap the set method in something that is good for you

```js
const originalSet = fabric.Object.prototype.set;
fabric.Object.prototype.set = function(key, value) {
  if (key === 'fill') { this.fire('fill:change', { old: this.fill, new: value  }); }
  originalSet.call(this, key, value);
}
```

not that i suggest this solution, but if you need it, this is a good approach.

On how many different spot of you project/application are you allowing for a color change? 2-3? this is not necessary. 10? maybe there is something unoptimal in our your application is being built.

Of course those are opinions and such as those should be taken.
Let me know what you think.
