### ISSUE TITLE
Loading a video as the canvas background is broken in v3

### ISSUE THREAD

**Issue by shayh** [fabricjs/fabric.js#6164]
## Version
3.6.0

## Test Case
https://jsfiddle.net/an9ft751/19/

## Information about environment
Nodejs or browser? browser
Which browsers? FF/Chrome

## Steps to reproduce
as shown in the fiddle, loading video as background image doesn't works in 3.6
replacing the imported version of fabric with `https://cdnjs.cloudflare.com/ajax/libs/fabric.js/2.3.0/fabric.min.js` does work.
## Expected Behavior
the video loads as the canvas background
## Actual Behavior
no background is loaded

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/75167679-04da2380-5726-11ea-8b60-e701b0114522.png)

not sure if is related by it complains it can't seek the video

**Comment by AdamMadrzejewski** [comment]
Ohh, [HTMLMediaElement.seekToNextFrame()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/seekToNextFrame) is non-standard, experimental element. I've tested it on version 2.3, but it is still not working. I wonder why it ever worked passing an HTML video element to a simple Fabric Image constructor.

It doesn't feel like it should be supported and maybe it was working only because somehow the the HTML video element was treated as an image element. I would simply find a way to pass a normal image to the fabric.Image constructor.

**Comment by asturur** [comment]
i feel like video elements should work as background or nor

**Comment by shayh** [comment]
It works for me in 2.3 without the call to seekToNextFrame
though I had to click the canvas, in order to get it rendered.

**Comment by AdamMadrzejewski** [comment]
Yes playing background video should be supported, I've found this example 

[](http://fabricjs.com/video-element)

I've made a simplified version of it and it works perfectly, but I am not able to have that code running on jsfiddle.net

Can you please check and see if it solves your issue? Probably is related to the missing parts in the example code or jsfiddle.net not playing the video due to some portal restrictions.

**Comment by shayh** [comment]
Hi Adam,
I already saw this example.
the difference here is that instead of setting the video as background it adds it as an element.
and again, my fiddle works in version 2.3 of fabric.js but fails on 3.x it doesn't.

**Comment by asturur** [comment]
https://jsfiddle.net/n6vh1cdg/

There is no bug in fabric around this.

- seekNextFrame was not working at all
- the video was missing an height and so it was rendering at 0 height
- the video is slow to load and you need to wait to actually load something to render something

**Comment by shayh** [comment]
thanks @asturur adding video dimensions did the trick.
