### ISSUE TITLE
about lock object

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6175]
Last week, I asked a question about lock objects, no moving，i tried to the
           
            e.target.lockSkewingY = true;
            e.target.lockSkewingX = true;
            e.target.lockMovementY = true;
            e.target.lockMovementX = true;
            e.target.hasControls = false;
 If I select an object, it is successful, it cannot be moved，but if I select several objects, including it, it can be dragged and moved together.What can I do when I select several objects  including the locked object, the locked object can't move. Other objects can move?

**Comment by joylord2018** [comment]
@asturur

**Comment by OrlandoCo** [comment]
Just add selectable property to false. This is in the documentation, please read it carefully. I don't want to sound rude but this place is for issues and bugs not for usage questions.

**Comment by joylord2018** [comment]
> 只需将selectable属性添加为false。这在文档中，请仔细阅读。我不想听起来很粗鲁，但是这个地方是针对问题和错误的，而不是针对使用问题的。

Iknow the selectable, set selectable, but it can't be chosen

**Comment by asturur** [comment]
This question has been answered a couple of time already.
https://jsfiddle.net/83vjn9c7/
^^^ this answer taken from some of the closed issues, is what you should try to do.

**Comment by shashank-brightness** [comment]
Above is what also there in photopea (photoshop clone website) and other editors.

In that way which @asturur mentioned, if i have a image object which can act as a background which is locked but still can be selected and if i drag through all objects including that background which is currently locked, nothing can be moved because anywhere i drag, it will simply include that image in it's selection so considering array some method locked thing is always there.

and still i don't want to set selectable to false for that image because at some point i might also want to make it unlocked which can be only done if it is be first of all selectable (i.e. can be selected).

In photopea for selection, there are layers so one can also click on layer to select but what if one does not want to use layers?

**Comment by asturur** [comment]
You are confusing locked with other things.
Locked is just not moving, not immune to selection.
If you want the object to allow for drag selection on top of it, you can try to change the 'activeOn' property and see if it helps.

There are also helpers like onSelect and onDeselect  or the selectionFullyContained of the canvas to tweak the experience

**Comment by shashank-brightness** [comment]
@asturur I have checked documentation but could not found anything on `activeOn` property which you mentioned. 

Also, `selectionFullyContained` just says it's `boolean` and `Select only shapes that are fully contained in the dragged selection rectangle` but there is not much detail given what it actually does.

The main issue here is the same as what @joylord2018 mentioned that when we select something which is `evented` to false (or all locked related properties e.g. `lockMovementX` to true, doesn't matter), and if it is under selection, that shape starts moving which it technically should not, so that one can drag and select it but still it can not be moved/rotated/skewed and scaled.

**Comment by asturur** [comment]
There are a number of options for selections and you want to build a feature on top of it, you have some options at your disposal, if none works as you want you will have to custom code it.
You can keep the image as backgroundImage and transfer it to an object every time it gets clicked, or you can play with that options and the onSelect function and  activeOn property to see if you can obtain this immunity to drag selection but still being able to select on click.
