### ISSUE TITLE
fabric.Object.getBoundingRect - extend with right/bottom property

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#618]
Return right/bottom property of bounding rectangle.

```
      return {
        left: minX,
        top: minY,
        right: maxX,
        bottom: maxY,
        width: width,
        height: height
      };
```

These properties can be used e.g. in isContainedWithinObject or isContainedWidthinRect (https://github.com/kangax/fabric.js/issues/610#issuecomment-17541221)

**Comment by ManjunathBiradar** [comment]
when I have added left to point.x and right to point.y to each of the points and resulting points array I passed to draw polygon with no left and top properties , it rendered me exactly at the same position.
But my issue is when user modifies shape using corners I would like to save the coordinates so that next time when user logs in , he should be able to see his edited shape. But what if user expands the shape right side or bottom side still the left and top and points remain same? 
My use case is jus I need to render the edited shape by user. can any one please help me soon
