### ISSUE TITLE
SVG sprites not shown properly (when delete is present)

### ISSUE THREAD

**Issue by onassar** [fabricjs/fabric.js#6192]
## Version
`3.6.0` & `4.0.0-beta7`

## Test Cases
`3.6.0`: http://jsfiddle.net/qnwpjy5x/
`4.0.0-beta7`: http://jsfiddle.net/0pjr5gsz/

## Information about environment
Browser (Chrome)

## Steps to reproduce
See fiddle

## Expected Behavior
Sprite should not be shown; the bounding box should be limited to the proper SVG. The SVG can be properly seen when the `delete` lines are removed.

## Actual Behavior
Sprite is show

**Comment by onassar** [comment]
Any luck with this? It's a tricky one.

**Comment by onassar** [comment]
One possibility that I'm investigating is to use the `forEachObject` on the `fabric.Group` object to iterate over each object and if it's not in the `viewBox`, discard it?

**Comment by asturur** [comment]
Is unclear what the bug is for me.
If you keep the parsed width/height you get the correct SVG.
If you delete them, you get the whole thing.
That svg is weird because it has lot of data outside the bounding box.

You could manually cut out what is outside the bounding box with few lines of code ( i think ).
Is that what are you looking for?

**Comment by onassar** [comment]
Yes I'm wondering how to do that. How do I get view the correct SVG that shows up in the bounding box, but have the exact perfect width & height?

**Comment by asturur** [comment]
So you can actually do that in a couple of ways.
You know that your bounding box goes from 0,0 to width,height.

I thing you can fake for a moment the `isOnScreen()` coordinates and use `isOnScreen()` to delete objects.

Is late for me to dig up an example, but if you look how `isOnScreen` works, you can either derive the code from there or make it so that using that function you filter the object array, then delete width/height and then group + add.

**Comment by onassar** [comment]
Okay I will take a look. Any chance you can show me an example using that fiddle? I trust you a lot ;) No rush: I can wait till tomorrow!

**Comment by onassar** [comment]
I couldn't figure out how to use `isOnScreen`; if you have any example of fiddle let me know and I can test?

**Comment by onassar** [comment]
It looks like `isOnScreen` returns true if it's fully _or_ partially on screen. I want to filter out any shapes that are not _fully_ on screen. I tried using the `isContainedWithinRect` method by using the group's bounding box, but I couldn't get that to work either.

Here's what I had:

    var shapes = group.getObjects();
    for (var index in shapes) {
        var shape = shapes[index],
            boundingRectangle = group.getBoundingRect(),
            tlx = boundingRectangle.left,
            tly = boundingRectangle.top,
            tl = new fabric.Point(tlx, tly),
            brx = boundingRectangle.left + boundingRectangle.width,
            bry = boundingRectangle.top + boundingRectangle.height,
            br = new fabric.Point(brx, bry);
        console.log(
            shape.isContainedWithinRect(tl, br),
            shape.isContainedWithinRect(tl, br, false),
            shape.isContainedWithinRect(tl, br, true)
        );
    }

Ignore the fact that I'm not optimizing anything in here ;)

**Comment by onassar** [comment]
Here's a recent jsfiddle I tried to see how this can work.
http://jsfiddle.net/onfuv70s/

If you drag the SVG layer around, you'll see that paths that are _not_ visible on screen are still there:
![](https://i.imgur.com/eSR2zWc.png)

:shrug emoji:

**Comment by onassar** [comment]
Here's a bit more progress that shows where I'm getting stuck:
http://jsfiddle.net/d6xw97fu/

The issue at the moment seems to be that even though the canvas is `100x100` and the group is `100x100`, the path in question (starting with a `d` value of `'m90.379 32.314c-.038 0-.074.005-.112.006v-.001c-.005 0-.013.001-.019.002-` has `aCoords` that are appearing _outside_ of the canvas.

I'm very confused by this;  how can the `aCoords` be outside of the canvas for this shape/path? I'm guessing it has to do with the translate/matrices of the shape/path, but if I can't figure out the exact tl/tr/bl/br of the shape/path, then I can't run checks to confirm if it's within the canvas.

**Comment by onassar** [comment]
The way I'm dealing with the strangeness of the corners being outside the canvas is to adding a padding value of `1`. A more fully functional version can be seen here:
http://jsfiddle.net/b0kn9wvh/

Once I take the `1` padding value into consideration, I am able to properly remove shapes/paths that are offscreen, however as you can see, there's an issue with some vectors and their associated controls and where the vector is drawn:

![](https://i.imgur.com/8wjAYIK.png)

Hope this helps!

**Comment by asturur** [comment]
https://jsfiddle.net/c2z8mn1u/

look the semplicity of this!

**Comment by onassar** [comment]
And what about this one :-P
https://jsfiddle.net/v67w5qzp/

Should look like this:
![](https://i.imgur.com/17W0p5w.png)

**Comment by asturur** [comment]
i mean, you are not even trying!
![image](https://user-images.githubusercontent.com/1194048/76575854-bcaa5780-64c0-11ea-8f02-e615656d515c.png)

![image](https://user-images.githubusercontent.com/1194048/76576013-2591cf80-64c1-11ea-9cd1-80c05e65c7cd.png)

if you add a width and height in pixels to the SVG, you will notice that the SVG is touching the borders. Probably for this the function is excluding it.
Since you are supposed to have a sprite sheet, and i hope there is some space between a sprite and another, just add some padding to your viewport rect and you can make it.

https://jsfiddle.net/38gdpmv9/

I'll close the issue, even if fabric still need a better svg parser, and since we have anyway an issue to track it, this is a standard help post and looks like you got some help.
There isn't really much else we can say around isolating pieces of SVG.

**Comment by onassar** [comment]
Thanks for this; this is perfect! I will test this out now, and write a gist for other people to use incase it's helpful. I really appreciate your help. I will close this issue now!

**Comment by onassar** [comment]
This works almost perfectly; I did fine a few cases where not all the "whitespace" was removed. Do you have any idea why that is? Here's the fiddle: https://jsfiddle.net/Ln4x519y/

Here's a screenshot where you can see whitespace between the bounding box and the SVG.

![](https://i.imgur.com/b46nk74.png)

**Comment by asturur** [comment]
https://jsfiddle.net/pyaLob0v/

SVG elements default have strokeWidth of 1 pixel, even if is transparent is there.
That whitespace is the invisible stroke.

You can't disable like i did in the example ( line 5 ) because it can break most of the SVG.
The shapes have been designed with those invisible lines around them and you just have to deal with it.
While you can be able to disable stroke for a number of svg, there isn't a solution that fits all.

**Comment by onassar** [comment]
Ahh okay that makes sense; I'll add some checking my code to handle stroke values. Thanks again!
