### ISSUE TITLE
Objects can only move when run object.toDataURL() in object:modified event

### ISSUE THREAD

**Issue by laibinweb** [fabricjs/fabric.js#6196]
# Version
3.6.0
# Test Cases
https://codepen.io/laibinweb/pen/NWqvbee
# Information about environment
Browser (Chrome)
# Steps to reproduce
1. run code object.toDataURL() in object:modified event
2. key down the shift key to select both objects to create activeSelection
3. move activeSelection
4. remove activeSelection
5. select any object, the object can only move, can't rotate scale
# Expected Behavior
Objects can operate normally

**Comment by laibinweb** [comment]
![5](https://user-images.githubusercontent.com/24617510/75763163-cc19fa00-5d76-11ea-9230-9a193b0f4cab.gif)

**Comment by asturur** [comment]
yes i can reproduce

**Comment by laibinweb** [comment]
Ok, I look forward to your fixing it

**Comment by asturur** [comment]
Found where the bug is, so i can fix it later:

Adding a group to the temporary canvas for export, is setting the temporary canvas to every object contained in the group/active selection.
When we finish exporting, nothing is setting back the object on the old items.

Possible solution: having a setter for the group and use `set('canvas')` rather than `.canvas =`
