### ISSUE TITLE
React

### ISSUE THREAD

**Issue by hsluoyz** [fabricjs/fabric.js#6208]

**Comment by asturur** [comment]
Or should React support fabric.js?
What does support mean here?

**Comment by hsluoyz** [comment]
See an alternative Konva and React-Konva: https://konvajs.org/docs/react/index.html

**Comment by asturur** [comment]
I do not have to have another big project, this is the main issue.
Complex fabricjs project and react already leave together happily without need of a library to comunicate.
Just initialize your canvas, use a createRef api and use fabric normally.

Data-flows are not solved by this kind of bindings.

If someone wants to do this kind of job, it can be hosted here, or in another repo, as he/she prefer.

**Comment by mrslimslim** [comment]
Fabricjs can work perferctly in React project.Checkt https://ludus.one/

**Comment by hsluoyz** [comment]
You link is not source code.

**Comment by asturur** [comment]
Because there is not source code for a so generic question/feature.
FabricJS works with react.

You do not need a react wrapper, you do not need to do things that are not related to DOM with react, when building a react app.

We may want a specific react initializer? maybe.
Is it clear what kind of support were you looking for? no.
You did link a website that says to look at a github repo.

How much time do you think a person wants to spend to try to understand what are you looking for? Very little. This is not because of the topic or you, but because it requires a lot of effort and time to follow those things and try to help or fix bugs.

I can assume that since you were looking for something like that, you had difficulties using react and fabricJS together in a way that seems right to you.
But i can't assume it, you should be here explaining what and how, or you'll probably get nothing.

**Comment by AdamMadrzejewski** [comment]
Hey @asturur do you think making a tutorial how to set up the FabricJS with React would be a good idea? I can do it, if you can give me some indication on where you would like me to post/submit it.

Looing at StackOverflow FabricJS + React, there are duplicates people asking how to do it https://stackoverflow.com/search?q=%5Bfabricjs%5D+react

I think it would be a good idea.

**Comment by asturur** [comment]
We cold make a demo of a canvas with a small panel that display the text information of the selected text object on the canvas
To show how to possibly use react-redux and react with fabric

**Comment by niels-van-den-broeck** [comment]
We've worked on a react project which is fueled by fabricjs for about 2 years now. Apart from it being hard to sync rendercycles, I think it works just fine. What we did was add the `renderOnAddRemove: false` option to the canvas and do a requestRenderAll at the end of each component update. That way it is possible to at least kinda sync the render cycles.

**Comment by niels-van-den-broeck** [comment]
> We cold make a demo of a canvas with a small panel that display the text information of the selected text object on the canvas
> To show how to possibly use react-redux and react with fabric

I think redux would be overkill, I think a simple state update could be enough to get things rolling for people who want to try and integrate it with react.

**Comment by asturur** [comment]
it mostly depend no the size of the app. I was using redux anyway in my app, and while it took a bit to understand what we needed, we just found it.

We do not manage fabric objects with react, but we want the react UI to know what is currently selected basically.

**Comment by asturur** [comment]
Another weird part was syncing canvas size to html current size

**Comment by juzhiyuan** [comment]
hi @asturur,  do we have a global event which can be fired when any event triggered, and could log the diff information? so we could build the app needs batch update.

**Comment by asturur** [comment]
no there is not such event. i personally rely on object:modified for example text:changed, selection:created, selection:modified, object:added, object:removed.

I try to catch all in this way.

If you think of it the user can do little to nothing without your code, it  can just move and scale and rotate. Object:modified catches that.

If you let them add/delete/change-color, you do it with your own code. At that point you do not need an event, because you are in control.
I know that a central place to rule them all is what we always want, but we do not have it in this case.

**Comment by juzhiyuan** [comment]
> no there is not such event. i personally rely on object:modified for example text:changed, selection:created, selection:modified, object:added, object:removed.
> 
> I try to catch all in this way.
> 
> If you think of it the user can do little to nothing without your code, it can just move and scale and rotate. Object:modified catches that.
> 
> If you let them add/delete/change-color, you do it with your own code. At that point you do not need an event, because you are in control.
> I know that a central place to rule them all is what we always want, but we do not have it in this case.

All right, I would try to get diff data by object-diff :) (because I have the needs to store the diff data and then do a batch update).

Thanks anyway!

**Comment by asturur** [comment]
Well the needs of your project are clear to you of course. the solution still is applicable, do canvas.toObject at each event and make the diff with the previous one. I think is not super efficient tho.

**Comment by ShaMan123** [comment]
I use `_set` method and from there fire a generic `change` event.
I also use `ReactDOM.render` to render components outside the main tree and from "within" fabric. A good hook for that is the controls API render/position method.
#7178

**Comment by ShaMan123** [comment]
https://github.com/fabricjs/fabricjs-react-sandbox

**Comment by ShaMan123** [comment]
available in the README
