### ISSUE TITLE
React hooks

### ISSUE THREAD

**Issue by alexmelo23** [fabricjs/fabric.js#6233]
Hi,

 I try using fabric js in react hooks but fabric object created All the time 

`
const useFabric = (node) => {
    console.log("render");
    const canvas = new fabric.Canvas(node.current, { backgroundColor: 'red' });
    canvas.setDimensions({ width: '100%', height: '100%' }, { cssOnly: true });
    return canvas;
}
`
`const canvas = useRef(null)`

`
const canvasEl = useFabric(canvas);
`

`
<canvas id="canvas" className={classes.canvas} ref={canvas} />
`

What am I doing wrong?

**Comment by asturur** [comment]
This is not a react support forum, and the problem here is 100% react based.

The problem is that useFabric is not a custom hook since it uses  NO react hooks.

useFabricCanvas run before the render process and at that point node.current is empty.

So you get a canvas that is not attached to the DOM.

your hook should be something like
```
const fabricInstance = useRef(null);
const useFabric = (node) => { useEffect(() => {
  fabricInstance.current = new fabric.Canvas(node.current, { backgroundColor: 'red' }); 
  canvas.setDimensions({ width: '100%', height: '100%' }, { cssOnly: true })
});
return fabricInstance;
}
```
