### ISSUE TITLE
How to consistently use pt measurements 

### ISSUE THREAD

**Issue by fusionbeam** [fabricjs/fabric.js#6252]
Hi guys,

We are evaluating fabricjs to define and edit some print specific templates. Thus we need to ensure the dimensions of the canvas and the layout of all graphical elements is proportional with some 'pt unit' based guidelines that drive our printing process. We also need to be able to define some text attributes and font sizes in pt, import some graphical svg-s that use 'pt' based dimensions.

What would your advice be in this matter? If needed we'll be happy to contribute code back here or sponsor additional support for this use case.

Thanks,
R

**Comment by andrewzolotukhin** [comment]
Hi @fusionbeam , you need to introduce DPI and recalculate all dimentions in pts when you display it to user, and recalculate it back to px when you ask user to input some value in pts, you can look how we did in https://cleverbrush.com/editor, there is a possibility to switch units in the right bar.

**Comment by asturur** [comment]
Fabric can parse SVG with pt units, provided that the default DPI is what you want:
https://github.com/fabricjs/fabric.js/blob/master/src/util/misc.js#L228

There is a parseUnit functionality that will let you parse that based on the fabric.DPI value ( that you can change ), this because PT are defined by inches, and here we are in pixels, the DPI value is the glue bewteen them.

For font size in pt, this is not really supported, but if you need to set and read font size in that way you can define a getFontSize and setFontSize for the Text.prototype that uses fabric.util.parseUnit to set the final unit in pixel.

I think this is all you need based on your initial request.

**Comment by fusionbeam** [comment]
Thanks guys. This is very helpful.
