### ISSUE TITLE
cannot clear Stroke on fabric Rectangle in IE

### ISSUE THREAD

**Issue by mk10391** [fabricjs/fabric.js#6281]
## Version
3.6.3

## Information about environment
Which browsers?
IE & Chrome
## Steps to reproduce
- use javascript.
- Just create a simple "fabric.Rect" and color it using stroke like below. 
myFabricRectObj.stroke = 'yellow'
- i have a simpe UI button called "clear". when i click "clear" button, i want to remove stroke (i.e the color ) ...so the rectangle will disappear. i am using something like following code

myFabricRectObj.stroke = ''

in this way, the yellow rectangle disappears in Chrome.....but its still visible in IE11. This used to work in very early versions of fabric. any idea how to hide & show rectangle ?

## Expected Behavior
clicking the "clear" button should hide the rectange in IE and Chrome
## Actual Behavior
clicking the "clear" button hides the rect in chrome but it doesnt hide in IE11.

**Comment by mk10391** [comment]
seems like following code works on both IE and chrome. it hides the rectangle 
myFabricRectObj.strokeWidth = 0;

and i can unHide it again by setting it to proper value. 

is this the correct way to show/hide rectangle on canvas ?

**Comment by asturur** [comment]
I'm not sure if you gave a look at docs, also not sure what are you doing since there is no fiddle.
- to hide/show an object you can use a property called `visible` http://fabricjs.com/docs/fabric.Object.html#visible
- object are cached: http://fabricjs.com/fabric-object-caching this will explain you why setting stroke color does not work out of the box
