### ISSUE TITLE
Changing height/width of an object after initial render does not work.

### ISSUE THREAD

**Issue by virror** [fabricjs/fabric.js#6305]
## Version
3.6.3 and master

## Test Case
https://jsfiddle.net/qogLps5a/5/

## Information about environment
Firefox, Chrome

## Steps to reproduce
Run the fiddle, select the little red box. Click the button, select the red box again.

## Expected Behavior
After the button press, little red box should be 150x100 in size and the selection box should be the same size.

## Actual Behavior
Only the selection box is the correct size, the red box is still the original small size.

**Comment by melchiar** [comment]
The correct syntax is `rect.set('width", 150);`, not `rect.width = 150;`

It's in the docs:
http://fabricjs.com/fabric-intro-part-1#objects

**Comment by virror** [comment]
Doh! Im upgrading from fabric 1->3 and there seem to be lacking any kind of documentation on whats changed between versions : )
Been looking at all the individual release notes but seems to have missed this one.

**Comment by virror** [comment]
But still it seems a bit strange that you can still use .height/.width at all since it gives you this really strange behavior.

**Comment by asturur** [comment]
i can't really replicate the bug.
Sometimes that happens with caching behaviour, but since width/height are part of the properties that calculate the size of the object, that is not really necessary, setting width/height straight will always work.

From what version are you upgrading?

Here are described the breaking changes from 1.x to 2.0
http://fabricjs.com/changes-introduction

Then the next big change is 2.4.0 where clipPath is introduced.

other incremental addition of 2.0 are : strokeUniform, splitByGrapheme, some gradient improvement, all the rest seems always small fixes and patches ( of course in the long run with surprises )

In version 3 i think that the only thing changed are major bumps in deps, removing old node support, and the node code changes. Some deprecated method is deleted

http://fabricjs.com/changelog <-- where it speaks of 3.0 describe a bit.

in 4.0 lot of deprecated method are deleted.

**Comment by virror** [comment]
Well, the only think i really know is that it does not work in the fiddle that i posted. But if set width works instead its not a big problem i guess.

**Comment by asturur** [comment]
for me the fiddle works, that is really strange.

**Comment by virror** [comment]
https://dl.dropbox.com/s/lljw3uudmu2c0hw/shot_200501_123046.png
This is my result.

**Comment by asturur** [comment]
super super weird.
Can you let me know exact browser and hardware?

**Comment by melchiar** [comment]
For me the issue was only visible on my pc running chrome, not on my android phone running chrome. Perhaps it's something to do with retina scaling?

If it helps, I wrote up a stack overflow answer recently outlining the main changes between fabric.js versions. Perhaps it'd make a useful doc addition?

https://stackoverflow.com/a/61221654/7693185

**Comment by virror** [comment]
For me it happened both on chrome and ff, both at home and on my office computer.

**Comment by asturur** [comment]
@melchiar that list is great! Can you make a simple .MD file from it so we can add it to fabricJS.com on top of that small list we have now?

**Comment by melchiar** [comment]
@asturur sure, which page are you thinking. The [changes-introduction](http://fabricjs.com/changes-introduction) page? I can do a PR if that easiest.

**Comment by asturur** [comment]
Yes that page would be good, or also a new page. I 'm not particularly attached to the current structure of the website, that seem more a giant notepad more than a structured website.
You can definitely make a PR on fabricJS.com, also i m leaning toward .md files rather than .html when possible, so if you pick up that page, just rename the file in .md and convert it , is simple enough to create no issues.

**Comment by azeemgujjar** [comment]
> ## Version
> 3.6.3 and master
> 
> ## Test Case
> https://jsfiddle.net/qogLps5a/5/
> 
> ## Information about environment
> Firefox, Chrome
> 
> ## Steps to reproduce
> Run the fiddle, select the little red box. Click the button, select the red box again.
> 
> ## Expected Behavior
> After the button press, little red box should be 150x100 in size and the selection box should be the same size.
> 
> ## Actual Behavior
> Only the selection box is the correct size, the red box is still the original small size.

Any solution you got i am facing the same issue, but no answer from anyone on stackoverflow...

**Comment by virror** [comment]
Yes, use .set(width, 150) instead of .width = 150

**Comment by azeemgujjar** [comment]
No this not worked for me. Solution is this:
`polygon.scaleToHeight(objectHeight);`

**Comment by asturur** [comment]
I m still puzzeld by this non reproducible issue on my laptop.
The first fiddle works great and i believe it should.

**Comment by melchiar** [comment]
@asturur It seems like the issue only occurs on devices without retina scaling. Can you try this fiddle with retina scaling disabled to see if you can reproduce it? https://jsfiddle.net/melchiar/xr3oftuL/

**Comment by asturur** [comment]
oh ok i finially understood this.
I left an old mail to clear up that brought me to this issue again.
As always, if you change something that change the look of the rect, you have to change it with `set('width', 150)` or you have to specifically mark the rect as dirty for re-render or you get the cached copy.

Now, this is not necessary for retina screen because the rect is double as big.
The minimum cache size is 256x256, and can fit also a 150x100 rect. So when changing width/height fabric does not need to resize the cache, while in retina you need to paint a 300x200 rect and that is going to delete the old 256x256 cache ad produce a re-render anyway.
