### ISSUE TITLE
Version 4.0 with gestures support

### ISSUE THREAD

**Issue by sbraaa** [fabricjs/fabric.js#6351]
In my project I need to use new custom controls and gesture but it seems that, at the moment,  gestures are not supported in version 4.0 .
How can I obtain version 4.0 with gestures support? Did you plan a release date with this features enabled?
I noticed that source code for version 4 Beta 12 refers to version 3.6.1 (all the formats, zip and tar.gz),
Version4 beta 11 is ok!

**Comment by asturur** [comment]
I should revisit why our gesture module is so bad as of today, i never worked with it since i start contributing/mantaining fabricJS.
I m very busy those days, trying to keep up with issues and i m not sure when i can look at gestures.

I m using hammerJS on my project and was relatively easy to add pinch and pan gestures.

**Comment by sbraaa** [comment]
> I should revisit why our gesture module is so bad as of today, i never worked with it since i start contributing/mantaining fabricJS.
> I m very busy those days, trying to keep up with issues and i m not sure when i can look at gestures.
> 
> I m using hammerJS on my project and was relatively easy to add pinch and pan gestures.

it seems that version 3.6.x with gestures work reasonable well (but it doesn't not fire object deselect event).
Could you point me some example using hammerJS?
Thanks!

**Comment by asturur** [comment]
I do not have examples yet outside of my non free project.
I ll try to pull something out.

**Comment by jigyasam** [comment]
@asturur I could really use an example with HammerJS as well, please!
