### ISSUE TITLE
Once selected text has been assigned a style, this style can no longer be changed.

### ISSUE THREAD

**Issue by blucobalto** [fabricjs/fabric.js#6360]
## Version
3.6.2

## Test Case
http://fabricjs.com/kitchensink

## Information about environment
Nodejs or browser? Browser
Which browsers? Firefox 76.0.1 (64 bit); Chrome 83.0.4103.61 (64 bit); Microsoft Edge 44.18362.449.0

## Steps to reproduce
http://fabricjs.com/kitchensink. In textbox select "foo"; important: only 'foo' not entire object;
Assign Bold. Once assigned the bold it cannot be eliminated anymore (same Italic, Underline ecc...).

## Expected Behavior
Change the style of the selected text

## Actual Behavior
Once selected text has been assigned a style, this style can no longer be changed.

**Comment by melchiar** [comment]
I'll take a crack at this....

Just to clarify, are you having an issue removing a style in a project you're working on, or just noticing that the kitchensink demo is lacking this feature? Styles that apply only to specific characters in a textbox are stored in the `styles` attribute of an object, while styles applied to the entire object are stored as separate properties of the object itself. Removing one of these "sub-styles" programmatically can be done just by deleting the right style from the styles array. 

Building a UI to recognize if every character in the current selection shares a particular sub-style and then changes the style button's action accordingly is more tricky which I expect is why it was omitted. I believe that the kitchensink demo is primarily meant to be a simple demonstration of the features of the library rather than be an exhaustive editing tool.

@asturur, care to add to this?

**Comment by blucobalto** [comment]
Melchiar,
I used the "kitchensink" code to create a small interface.
I hadn't noticed that the "kitchensink" code uses the 
`text.setSelectionStyles (style);`
and not the 
`text.setSelectionStyles ({styleName: value}, startIndex, endIndex);`.

Thanks a lot,
Blu

**Comment by asturur** [comment]
i have really no time to improve the kitchensink and taking any code from there is ill advised since it may be old, based on 1.x constrains and also wrote in rush by someone else many years ago.

I think we have a way to set the selection's style to empty. Don't we?
