### ISSUE TITLE
error getwidth  and getheight  

### ISSUE THREAD

**Issue by HDONGDeveloper** [fabricjs/fabric.js#6392]
![$}P20` F9G1((GGY%@8PAQH](https://user-images.githubusercontent.com/31230864/84967694-2b91ef00-b147-11ea-879b-bb6c51f72597.png)

**Comment by melchiar** [comment]
Please follow the issue template since it's very difficult to know for certain what the problem is with just the screenshot you've provided. 

If you're wondering why the width and height values are the same for an object that is evidently rectangular then your object probably has a larger `scaleX` value than the `scaleY` value.

**Comment by asturur** [comment]
Sometimes i think with the new control interface the rect should use by default change width and change height.
Is what people expect even if to me seems just non coherent.
