### ISSUE TITLE
how to move mtr icon to bottom position

### ISSUE THREAD

**Issue by bulolo** [fabricjs/fabric.js#6445]
![image](https://user-images.githubusercontent.com/10026498/87056682-8dbaad00-c238-11ea-9ebe-1838df683e8c.png)

how to set mtr icon position? i want to move the top mtr icon to bottom .

like this

![image](https://user-images.githubusercontent.com/10026498/87056952-e38f5500-c238-11ea-909f-34e4ea165633.png)

**Comment by asturur** [comment]
you can do that only with version 4+, changing the position of the default mtr control.
Please look here:

http://fabricjs.com/controls-api

**Comment by bulolo** [comment]
thx.
is there any docs for 4.0.0
i found the newest one is http://fabricjs.com/docs/ for 3.6.3

**Comment by bulolo** [comment]
i use 4.0.0

```
 var controlsUtils = fabric.controlsUtils
  fabric.Object.prototype.controls.mtr = new fabric.Control({
    x: 0,
    y: 1,
    actionHandler: controlsUtils.rotationWithSnapping,
    cursorStyleHandler: controlsUtils.rotationStyleHandler,
    withConnection: true,
    actionName: 'rotate',
  });
```


i delete actionHandler and cursorStyleHandler 
![image](https://user-images.githubusercontent.com/10026498/87113894-dc506180-c2a1-11ea-8f23-4d85f1fd02f0.png)

i add actionHandler and cursorStyleHandler 
![image](https://user-images.githubusercontent.com/10026498/87113816-b7f48500-c2a1-11ea-84d8-692a7ad6b400.png)
but it can't rotate

i use the default controls to set mtr control and move mtr position y to 1:
https://github.com/fabricjs/fabric.js/blob/master/src/mixins/default_controls.js

**Comment by asturur** [comment]
The last commit that rename the utils to controlsUtils hasn't been published yet.

```javascript
  var controlsUtils = fabric.controlHandlers;

  fabric.Object.prototype.controls.mtr2 = new fabric.Control({
    x: 0,
    y: 0.5,
    withConnection: true,
    offsetY: 40,
    actionHandler: controlsUtils.rotationWithSnapping,
    cursorStyleHandler: controlsUtils.rotationStyleHandler,
    actionName: 'rotate'
  });
```

We are still fixing some name here and there.
Using a y position of 1 will make your control move away when you scale.
Please use 0.5 and an offset to make it distant from the bounding box.

**Comment by TheMangoTrain** [comment]
For reference here's a Codepen where rotate is moved to bottom, and there's a delete icon in top.
https://codepen.io/MarsAndBack/pen/OJMdwLL

On a side note, is there a way to do this in 3.6.1 ?
We have to revert to 3.6.1 for other reasons (gestures not working in 4.0.0rc1, as well an export issue seems like?).

**Comment by asturur** [comment]
you can do with 3.6.1, but is complicated and requires overrides to a couple of functions.
Gesture needs a fix, but which is the other problem?

**Comment by TheMangoTrain** [comment]
I've gotten pretty far with 3.6.1 icon customization, see Codepen:
https://codepen.io/MarsAndBack/pen/dyGaKNJ?editors=1111

**Remaining issue:** Although the icons are successfully positioned, the problem is the actual action (on mouse over) still exists in the old positions. For example, hover over the old original rotate icon position, and you see the mouse cursor changes to a "+" sign and rotate is still functional from there. The new icon position for rotate has no action and clicking it just deselects the active object. The same issue exists for the custom Delete icon (which is taking the place of 'mb' icon): The original 'mb' action still exists in the original 'mb' location.

Question: Does setCoord() need to be triggered at some point to account for the above? Or is there another function that deals with the actual action positions, separate from icon visuals?

**Re: 4.0.0rc1** I'm still tracing an issue on export; I'm not sure yet where it's coming from. A quick switch to 3.6.1 showed the same error so it could be just my own logic being an issue. In any case, we need gestures for a public release of what we're working on; otherwise we'd continue to use 4.0.0.

**Question:** Is there a timeline for the gestures fix for 4.0.0rc1?

**Comment by asturur** [comment]
I fixed gestures on the v4 today if you are still looking for a solution.

**Comment by asturur** [comment]
I changed in some old project the mtr position, and i remember i had to change many things in order to have it behave correctly, including the the rotation code.

your 3.6.1 looks good to me anyway

**Comment by Tunanby** [comment]
> ![image](https://user-images.githubusercontent.com/10026498/87056682-8dbaad00-c238-11ea-9ebe-1838df683e8c.png)
> 
> how to set mtr icon position? i want to move the top mtr icon to bottom .
> 
> like this
> 
> ![image](https://user-images.githubusercontent.com/10026498/87056952-e38f5500-c238-11ea-909f-34e4ea165633.png)



> ![image](https://user-images.githubusercontent.com/10026498/87056682-8dbaad00-c238-11ea-9ebe-1838df683e8c.png)
> 
> how to set mtr icon position? i want to move the top mtr icon to bottom .
> 
> like this
> 
> ![image](https://user-images.githubusercontent.com/10026498/87056952-e38f5500-c238-11ea-909f-34e4ea165633.png)

兄弟，你那个图标咋搞上去的呐

**Comment by Tunanby** [comment]
> ![image](https://user-images.githubusercontent.com/10026498/87056682-8dbaad00-c238-11ea-9ebe-1838df683e8c.png)
> 
> how to set mtr icon position? i want to move the top mtr icon to bottom .
> 
> like this
> 
> ![image](https://user-images.githubusercontent.com/10026498/87056952-e38f5500-c238-11ea-909f-34e4ea165633.png)
兄弟，你那个左右两边的图标咋搞上去的呐

**Comment by asturur** [comment]
Please have a look at the custom controls api.

I think setting 
```
fabric.Object.prototype.controls.mtr.y = 0.5
fabric.Object.prototype.controls.mtr.offsetY = 30 // example
```

should be enough.

**Comment by Tunanby** [comment]
thank you
