### ISSUE TITLE
Document sensible ES6 imports

### ISSUE THREAD

**Issue by Robbie-Cook** [fabricjs/fabric.js#6466]
**Is your feature request related to a problem? Please describe.**
When importing fabric in ES6 from the npm package, it is not immediately obvious that you can import fabric like so:

```typescript
import { fabric } from 'fabric';
```
Instead, it is quite easy to try:
```typescript
import fabric from 'fabric';
```
but this does not work.

**Describe the solution you'd like**

It would be great if we added some code to the README for ES6 imports of the NPM package, so that it is obvious how to import the package in an npm environment.

**Describe alternatives you've considered**

An alternative could be to allow a default import to be the fabric object itself, so that

```typescript
import Fabric from 'fabric';
```
Will also work.

**Additional context**

The README does not seem to have much detail as to how to use this package with NPM, either with commonjs `requires` or ES6 imports, even in the NPM package's README, unlike most packages. I think that it will encourage usage to give an immediate code sample here to show fabric in an NPM environment

**Comment by Robbie-Cook** [comment]
I am very happy to help with this if this is considered a worthy feature

**Comment by asturur** [comment]
So i would love to not change the current import logic, there is something delicated between AMD and commonJS, once i break it and issues popped out.

I agree this should be in the readme of the npm package, and in order to get that done, you can open a PR on our readme file, i guess that would be fine?

The same thing could be on the website, clarified in the poor node section:
https://github.com/fabricjs/fabricjs.com/blob/gh-pages/posts/_posts/2012-12-21-fabric-intro-part-4.html

**Comment by Robbie-Cook** [comment]
Hey @asturur , I have made a PR for this here: https://github.com/fabricjs/fabric.js/pull/6467. Thanks :)

**Comment by Robbie-Cook** [comment]
Also, I have a React CodeSandbox example here: https://codesandbox.io/s/react-fabric-example-87hh4?file=/src/App.js:51-84 . Could anyone envision this being part of the docs at some point?

**Comment by Robbie-Cook** [comment]
This PR has gone through for this: https://github.com/fabricjs/fabric.js/pull/6467 , so this issue is resolved! Yay! 🥳
