### ISSUE TITLE
Can't build 3.6.3 with selected modules on fabric.js website - it builds 4.0rc1 instead.

### ISSUE THREAD

**Issue by AvaelKross** [fabricjs/fabric.js#6476]
## Version
3.6.3

## Test Case
http://fabricjs.com/build/

## Steps to reproduce
Trying to build 3.6.3 with Gestures. But it downloads 4.0rc1. The label above the form states that "Fabric version: 3.6.3". Can I get 3.6.3 with Gestures somehow please?

**Comment by AvaelKross** [comment]
I think I can build it locally with Node, but it still seems an issue because the builder says it use v3.6.3.

**Comment by asturur** [comment]
i m sorry i have to messed up last website update. I'll fix.

**Comment by thobn24h** [comment]
@asturur : what is the correct command line to custom build fabric on local machine ? I want to build custom fabric but when import to reactjs project it error:
```
./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
Module not found: Can't resolve 'child_process' in '/Users/thobn/DEVELOP/Project/node_modules/jsdom/lib/jsdom/living'
```
I'm using command line:
```
node build.js modules=ALL exclude=node no-strict no-svg-export
```

**Comment by asturur** [comment]
Did you npm install?

**Comment by Syno0** [comment]
Hi
I have exactly the same problem. I need 3.6.3 with gesture but it build 4.0rc1 file instead.
So I have multiple js errors because my code is for 3.6.3 I guess.

Just for information my erros if I switch my 3.6.3 to  4.0rc1:
`Uncaught TypeError: fabric.controlsUtils is undefined` and `Uncaught TypeError: this._initEventListeners is not a function`

Any update for the fix on the website ? Are workaround to get the 3.6.3 with gesture ?

Thanks

**Comment by asturur** [comment]
i ll try to update the website tomorrow morning!

**Comment by asturur** [comment]
updated website back to latest v3.x
