### ISSUE TITLE
containsPoint returns true for transparent areas inside the bounding rectangle that aren't part of the object's shape

### ISSUE THREAD

**Issue by TrevorHinesley** [fabricjs/fabric.js#6509]
## Version
Master (https://rawgit.com/kangax/fabric.js/master/dist/fabric.js)

## Test Case
http://jsfiddle.net/q2bgnLoj/

## Steps to reproduce
Simply move the mouse into a transparent corner of the ellipse in the fiddle, and the console will print "now!"

## Expected Behavior
I expect `containsPoint` to honor the shape, and only return true if the point is actually contained within the object's shape itself.

## Actual Behavior
`containsPoint` is just checking against the bounding rectangle from what I can tell. I've tried all combinations of true/false for the last two parameters of the method as well.

**Comment by asturur** [comment]
yes Object.prototype.containsPoint just check the bounding box.
Was by design like that.
The class system allow you to eventually write contains point specific for particular shapes ( triangle, circle, ellypse, polygons and path )

Or there could be an additional method or parameter, to contains point to exec specific code for a particular kind of shapes.

ContainsPoint is used for a variety of functionalitis, i m not sure all would benefit from the more accurate version.

**Comment by pressureless** [comment]
Maybe containsPoint should be renamed, it's a method of an object that should check if `that` object (not the bounding box) contains a point.

**Comment by ShaMan123** [comment]
I want to change this method also or expose something complementry.
My concept is that containsPoint will return an object with keys of isContainedInFill, isContainedInStroke, isContainedInBBox or null
Then all cases are covered and the API is straight forward
I have a POC for that using math and bezier-js

**Comment by ShaMan123** [comment]
But maybe fir now you can use canvas.isTransparent
