### ISSUE TITLE
Vertical Text Positioning inside Text box

### ISSUE THREAD

**Issue by chrismeats** [fabricjs/fabric.js#6539]
I am having an issue where depending on the text length and size the text itself is positioned vertically in different areas.
My problem is then I am replicating this functionality in PHP to be able to generate a PNG and I cant see the logic behind why text gets positioned the way it does.
Here are a few screen shot examples.
Short Text, Large Font, tall box, Text is positioned further down inside the box:
![image](https://user-images.githubusercontent.com/3507007/90945178-f2952580-e3e8-11ea-818a-fc2a7c710ee7.png)

Longer Test, smaller font, same tall box, Text is positioned at the very top of the box:
![image](https://user-images.githubusercontent.com/3507007/90945201-18222f00-e3e9-11ea-8511-f4d52eead9fe.png)

ideally I would like figure out the logic behind this so I can reproduce pixel for pixel what it is doing in PHP as this would solve any legacy bugs as well. Alternatively, being able to set it so text was always centered or top vertically aligned would be acceptable.

Thank you for any help and guidance.

**Comment by lk77** [comment]
Hello,

same issue here

**Comment by asturur** [comment]
The text alignment position is described in the javascript code.
The tex shouldn't have a big bounding box like the one you show on the second picture, how are you getting that?

**Comment by chrismeats** [comment]
@asturur the text box sizing area is adjustable. So I have it setup that the user can make the box larger, to accommodate larger text and fit within other elements. I then setup the font size to automatically adjust based on the size of the box. but I do not think that is relevant to this as it still happens if you define the height and width and font of the text box.

**Comment by asturur** [comment]
Well is relevant in the sense that in the source code you find the answer on how the vertical alignment is calculated for the normal textbox, and you can try to replicate it in another languaage and render system. If you have a custom textbox i m not sure the code is much useful.

**Comment by chrismeats** [comment]
@asturur I am using a regular fabric.Text element, not a custom textbox.
Perhaps I do need to look into how the vertical alignment is calculated so I can replicate it in another language. Are you familiar enough with the source code to point me in the right direction?
Thank you for the help and replies! Really appreciated!

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/blob/master/src/shapes/text.class.js#L888

If you are outside javascript, consider that getHeightOfLine is just based on a multiplier of the fontSize of the text.

Everything is about the initial top (that you can really check how is calculated, it could be just Object.top and then rendering text line by line, moving down of a line + some extra space dictated by lineHeight. There are constants named and defined in fabric.js

When drawing text a the given top value, what exactly is at the top value is the baseline of text, described here:

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textBaseline

Eventually most of other languages drawing libs support baseline alignment since is the most common.

**Comment by chrismeats** [comment]
@asturur Thanks so much! I will spend some time recreating the pieces needed in PHP. Hopefully this solves my issue.

Thanks again for the info!

**Comment by ShaMan123** [comment]
I can't find the ticket - some dev did a POC of vertical text
@asturur do you remember?
