### ISSUE TITLE
gestures support on version 4 and custom build with gestures

### ISSUE THREAD

**Issue by sbraaa** [fabricjs/fabric.js#6550]
It seems that version 4 close a lot of issues regarding gestures but I still not able to made them work in my project.
I tried version 4 and 4.1 with chrome on Android 9 Devices.

I also tried to build a custom version which includes gestures : even if custom build's page says latest version is 4.1 the files I obtain after downloading the build refers to version 3.6.6. 
Is this right? 
I'm very confused..

**Comment by asturur** [comment]
i did not update the website yet to run on 4.1 (i have a draft on my disk).
But you can make the custom build using the cloned repository.

**Comment by sbraaa** [comment]
Thanks Andrea!
Can you confirm that standard release of version 4 and 4.1 does not contain gestures feature by default?
(looking at sources I didn't see the event.js parts...)

**Comment by asturur** [comment]
no it doesn't.
There is a build script that takes a bunch of options and will build it for you.

You can also use it in the npm post install stage of your  project if you need to have it in your pipeline.

I think that requiring event.js for events is bad from our side. Eventually you want to use your preferred multi gesture library and just fire some events. But i have no code for that. In my project i ended up using hammerjs because eventjs is so unmaintained i did not want to use it. Hammerjs had a couple of forks that are a bit more maintained

**Comment by sbraaa** [comment]
ok, thank you for the infos!
I thought event.js has better support because it can be part of regular release but I'll keep on with hammer.js! ;-)

**Comment by asturur** [comment]
choose the library that works better for gesture recognition, you can see that connecting fabricjs is really few lines of code.
