### ISSUE TITLE
TS definitions do not allow for importing fabric  from window using webpack externals

### ISSUE THREAD

**Issue by hga77** [fabricjs/fabric.js#6552]
## Version
3.6.6

## Demonstration Repo
https://github.com/hga77/webpack-externals

## Stackoverflow Issue
https://stackoverflow.com/questions/63623980/webpack-externals-are-resolving-to-undefined

## Steps to reproduce
Pull the provided repo and run

## Expected Behavior
When Fabric is configured as an external on webpack, it should resolve to the global fabric object

## Actual Behavior
Webpack provides a fabric variable that is undefined. This might be a webpack issue, but how come other libraries work such as jquery, lodash, etc...

**Comment by asturur** [comment]
The problem is with TS and the definition file.
The correct way to do it would be importing 
```js
import fabric from 'fabric';
```

because the external would recover the window.fabric variable, that has no fabric property. There is window.fabric.fabric to be clear.

If you set the import in that way TS starts to complain because definition do not match.

you can add this to your index.html to have it working

```html
  <script>
    window.fabric.fabric = window.fabric;
  </script>
```

**Comment by hga77** [comment]
Thanks for your reply. I just resolved the issue by importing in this way:

`const fabric = require('fabric');`

Will this be a problem if I leave it like this?

**Comment by asturur** [comment]
if TS does not get in the way no. I'm not a TS expert at all, i m also unsure who is maintaining the TS file at definitely typed.
