### ISSUE TITLE
Object.lockUniScaling alternative in V4

### ISSUE THREAD

**Issue by andrewzolotukhin** [fabricjs/fabric.js#6555]
I see that in V4 we have a lockUniScaling property removed for Object. Probably anybody knows what is propper alternative in V4 to get the same result?

**Comment by asturur** [comment]
http://fabricjs.com/upgrade-guide

Look at the v4 breaking changes.

**Comment by andrewzolotukhin** [comment]
Hi @asturur , I saw this link, there we have: " If uniformScaling is true, objects get scaled proportionally, if uniscaleKey is pressed, the behaviour get swapped." But what if I want only one object to get scaled uniformly but others no?

**Comment by asturur** [comment]
It is a canvas only property right now.
It could have been done on the object, so that you could have act on the protype to get all objects.
But it is not.

You can still act on controls on this function here:

```js
  /**
   * Inspect event and fabricObject properties to understand if the scaling action
   * @param {Event} eventData from the user action
   * @param {fabric.Object} fabricObject the fabric object about to scale
   * @return {Boolean} true if scale is proportional
   */
  function scaleIsProportional(eventData, fabricObject) {
    var canvas = fabricObject.canvas, uniScaleKey = canvas.uniScaleKey,
        uniformIsToggled = eventData[uniScaleKey];
    return (canvas.uniformScaling && !uniformIsToggled) ||
    (!canvas.uniformScaling && uniformIsToggled);
  }
```
and let it consider an object property you like more.

I'm not opposed to reintroduce it for objects too, as it was before in 3.x was built broken.

**Comment by andrewzolotukhin** [comment]
Great, thanks, I'll check it.

**Comment by andrewzolotukhin** [comment]
As I understand now I should user controls API for that?

**Comment by asturur** [comment]
You are right this has been a misjudgment when deciding to keep it on the canvas or on the objects.
It has to be on both.

I have to run on the v3 code to remember what exactly lockUniScaling was doing and how it cooperated with `uniScaleTransform` on the canvas.

**Comment by andrewzolotukhin** [comment]
Would you like me to create a PR?

**Comment by adamgamble** [comment]
PR here: https://github.com/fabricjs/fabric.js/pull/6575

**Comment by asturur** [comment]
Added a message on the PR with an alternative, let me know guys what do you think.

**Comment by andrewzolotukhin** [comment]
Thanks, sent you a response there.

**Comment by SLKnutson** [comment]
Hi.
I'm trying to add back this functionality for our app so that we can upgrade to v4. We mainly need it for things that need to scale proportionally, like images that need to keep their aspect ratio.

What is the best way to change scaleIsProportional for fabric objects? It seems like that function is not available for overriding. I could override the things that use it, but I would prefer to copy and paste as little code as possible.

Thanks!

**Comment by asturur** [comment]
@SLKnutson there is a pr with a discussion and a solution. Does it fits your needs?
