### ISSUE TITLE
Gradient: options.colorStops.splice() is not a function

### ISSUE THREAD

**Issue by andrewzolotukhin** [fabricjs/fabric.js#6563]
## Version
4.1.0

## Test Case
https://jsfiddle.net/9rf4kbws/11/

It was working in V3, but now stopped. Does colorStops expect array now? But when I pass array there I get another error.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/issues/6510

The new fabric.Gradient always had a slightly more elaborated option format.
setGradient ( from which it looks like you copied the options ) was removed because was just a translation layer on top of it.

Also coords have a different option format.
The breaking change docs definitely needs a specific example since you are the second asking this.

**Comment by andrewzolotukhin** [comment]
Thanks

**Comment by asturur** [comment]
i need it open to fix docs or i ll forget

**Comment by thatisuday** [comment]
Though this feature needs to be documented, I have figured it out by reading the source code.

```js
element.set(
  "fill",
  new fabric.Gradient({
    type: "linear", // or "radial"
    coords: {
      x1: 0,
      y1: 0,
      x2: 0,
      y2: element.get("height"),
      // r1, // for "radial" gradient
      // r2, // for "radial" gradient
    },
    colorStops: [
      {
        offset: 0, // value 0 - 1
        color: "#000",
        opacity: 1
      },
      {
        offset: 1,
        color: "#fff",
        opacity: 1
      }
    ]
  })
);
```

**Comment by asturur** [comment]
you can open a pr and make it happen

**Comment by asturur** [comment]
docs updated.
http://fabricjs.com/fabric-intro-part-2#gradients
