### ISSUE TITLE
Simulating form field using TextBox

### ISSUE THREAD

**Issue by sbraaa** [fabricjs/fabric.js#6690]
For my project I need to simulate a form field using Textbox.
These are the requirements:

- field cannot be moved or stretched
- field has fixed length that cannot be overmatched
- no carriage return is allowed (always 1 row!)

Reading all the available docs and stackoverflow posts I know that Textbox cannot support these features by himself so I'm tried to achieve desidered behaviour.
This is my best attempt : https://codepen.io/sbraaa/pen/gOMZmKW?editors=0010

As you can see it doesn't runs very well: when width limit is reached  it seems that exceeded chars are removed but if you type  again you'll see that the chars are not removed!
I also tried with splitByGrapheme = false or using onInput event but it doesn't run as expected.
Any suggestions?

**Comment by CharlesRA** [comment]
Hi !
I hope this jsfiddle will help you : https://jsfiddle.net/4h9qpcw0/1/

**Comment by sbraaa** [comment]
@CharlesRA : outstanding, thank you.  That's exactly what I needed. Could you give some hint to understand  your approach?

**Comment by CharlesRA** [comment]
I'm glad this helps you :)

1 / First we create a new type which is based on TextBox so as not to change the original class.
`fabric.Form = fabric.util.createClass(fabric.Textbox,` 

2 / We ovveride the "onInput" method in order to write the desired behavior
2.A / We will look at the height of our text zone and verify that it is not greater than the maximum height
            `this.getBoundingRect().height  > this.maxHeight * this.canvas.getZoom()`
2.B / We make sure that our input is not the backspace key , so the field is not blocked and can be deleted 
             `e.inputType !== "deleteContentBackward"`
2.C / If it's too height we will delete the last char from the hidden text zone. Then call the parent method to display the deleted char/our new char
`this.hiddenTextarea.value = this.hiddenTextarea.value.slice(0, -1);`

3/ The loop is there to handle pasted texts that are too long

Hope it's a little clearer :)

**Comment by sbraaa** [comment]
Thank you again @CharlesRA ! Now  it's clearer, I never thought about it, brilliant and clean solution! ;-)
