### ISSUE TITLE
Site redesign [$305]

### ISSUE THREAD

**Issue by aleph1** [fabricjs/fabric.js#671]
I wasn't sure if a site redesign is still on the table — it is mentioned here: https://github.com/kangax/fabric.js/wiki/Love-Fabric%3F-Help-us-by... — but I started to put something together that simplifies the homepage and encourages people to start with the tutorial or downloading the library.

I think simplifying the features that are showcases on the home page, as users can easily click through to the full demos page.

There are still some items that need to be added back in (twitter, github, flattr, etc.), but it is a start. If this is an acceptable first stab I will do some additional identity exploration and work to refine the design.

![fabric](https://f.cloud.github.com/assets/485722/594381/a5cc62c0-ca7f-11e2-8abc-bc7f52c2bf97.jpg)
##

**Comment by bartektomas** [comment]
Heh sh*t, i didnt saw this topic before i was started with logo contributing. Anyway, anybody continues this project? It's been a year since then

**Comment by kangax** [comment]
Someone reached out to me recently with proposal for another logo but no, there's no definite work on this yet so please feel free to pick it up! Would be much appreciated.

**Comment by bartektomas** [comment]
Cool i'll try do somethimg :)

**Comment by FeaRCODE** [comment]
@kangax Is this still a thing? When you mean re-design are you referring to a PSD or the actual coding? I might try to throw something together, ill let you know. It's been a while since anyone has tried to do this and I think it is time for an update :)

**Comment by kangax** [comment]
Thanks. I mean actual design (.psd, .ai, whatever)

**Comment by FeaRCODE** [comment]
@kangax I'm definitely gonna give this a go. And for what it's worth, most of the bounty i will put back into fabricjs. It's really nice to have something like this I can use on my projects <3

**Comment by FeaRCODE** [comment]
@kangax Check your email. I sent you a quick preview. Tell me what you think. Thanks!

**Comment by shtefcs** [comment]
I wanted to re-design it as well, just was to busy recently.

@FeaRCODE wanna collaborate with me and few guys on re-design ? If you provide design/UI, we can craft in materialize, add some cool animations, optimize for SEO, etc.

If you wanna hang out with us, join https://chat.vanila.io

**Comment by FeaRCODE** [comment]
I'll try to help as much as I can!

**Comment by shtefcs** [comment]
@FeaRCODE sure, I saw you registered, lets chat :)

**Comment by FeaRCODE** [comment]
Should the issue be closed considering we have a team already on it?

**Comment by kangax** [comment]
Generally issues are closed only when the task is completed, so let's keep it open for now.

**Comment by FeaRCODE** [comment]
So, here is what I have so far. Please tell me what you think and if im missing something. 

[screenshots.pdf](https://github.com/kangax/fabric.js/files/288244/images.pdf)

**Comment by FeaRCODE** [comment]
What else is needed to finish this issue? I still have the PSDs if needed. @asturur @kangax

**Comment by asturur** [comment]
PSD needed, lot of time available ... :(

**Comment by FeaRCODE** [comment]
@asturur I emailed you the PSD (Using Artboards).

**Comment by tiesont** [comment]
Is this still in progress? If not, are you looking for someone to work on completing whatever has been started?

**Comment by asturur** [comment]
i have someone that actually provided psd designs. i should cut them and make them in gh-pages templates.

in one year i did not find the time

**Comment by tiesont** [comment]
Okay, I'm generally pretty good at slamming out static HTML, if someone has PSDs or whatnot for what they'd like the site to look like. I'm personally a fan of what was shown at https://github.com/kangax/fabric.js/issues/671#issuecomment-18800093 and https://github.com/kangax/fabric.js/issues/671#issuecomment-18998428

I'm not after the bounty, I just think the Fabricjs website could use an overhaul. Of course, the current home page _does_ do a decent job of demoing a lot of features, so...

**Comment by FeaRCODE** [comment]
@tiesont I am not sure what PSDs he is talking about, however I did send him some. If he selects my design i'd be happy to send them to you.

**Comment by asturur** [comment]
So your designs @FeaRCODE are the one that were accepted, i have still them here: 
![image](https://user-images.githubusercontent.com/1194048/28497945-bcee9352-6f93-11e7-8b8f-9733e3c489de.png)

in my `keep to read, so you do not forget`. I remember your designs were chosen by @kangax ( i do not have even photoshop to open them ).

If @tiesont is happy to help the bounty should go to @FeaRCODE 

To see how to do that, would be necessary  to clone the fabricjs.com repository, start it with the command `jekyll serve` and check between files how the layout works. Everything is static and css.
I'm totally open to explain it if is not clear, just that between coding the lib and working on the website, i always gave the lib higher priority.

**Comment by asturur** [comment]
I also have no idea how to make the transition from one branch to another with github.

**Comment by magebay99** [comment]
publish your HTML so everyone can help to build fabricjs.com great again

**Comment by asturur** [comment]
html is on fabricjs.com github repository

**Comment by FeaRCODE** [comment]
Been a while since I’ve come back to this but I think I may have some time to help with the html/coding portion of the redesign that way we can close this issue. I’ll keep everyone posted here.

**Comment by asturur** [comment]
i would really wanto to update the website.
I nearly released 2.0 too and i have time for it.

**Comment by asturur** [comment]
oh and we have a logo too now.

**Comment by hermbit** [comment]
wow, reading all of that was crazy. its been 4 years! what's the status on this? i'd love to help out.

**Comment by asturur** [comment]
So the status is that de facto nothing has been done ( apart i decided to use my not-so-skills to finalize a proposed logo, that now is the facto the logo ).

The website run on github pages + jekill  and i would like it to continue to do so

Who wants to help, apart designs, should focus on that platform and deliver some kind of html chunks as is the actual so that things can be translated and actually tried locally

We need to reserve a small space for ```carbon ads``` that as today is the only thing that is sustaining  fabricjs a bit and can pay stickers or other small things.

Whoever wants to commit to this, can say it here. 

Commitment to a slow, long term work is preferable to a burst of super design skill to which i cannot run behind.

the $305 dollars that are at stake here are not representing the amount of effort needed. Is probably just for the glory and a big thank you.

I will be available by email or hangout, to clarify how gh-pages work, how to setup to run it locally, to question about design decisions ( since usability in adding new demos and tutorial or docs is important).
Once the first 2 or 3 things are set up, i can help too, i have frontend and css skills.

**Comment by hermbit** [comment]
@asturur I completely agree that it should be done slowly. From reading this thread I see the error in one person trying to do it all at once, and failing to deliver. It would be great as a community effort.

Perhaps you could close this issue and create a new thread, considering this is 4 years old, so that more people involved in Fabric will see it.

Is this the official repo for the website? https://github.com/kangax/fabricjs.com

**Comment by asturur** [comment]
yes. that is the repository.
As you can see i made disordered commits to move it on, but if you are interested in see how it works, i can explain you if we setup an hangout ( i'm in a EU timezone, and i prefer mornings )

I did not build the first setup of the website, but with time i understood how it works.

**Comment by tiesont** [comment]
So, I suppose I can make the periodic bump to this issue and ask if this is still something to do?

If so, is there a preferred place to either start, or to pickup? I've downloaded the PDF from https://github.com/fabricjs/fabric.js/issues/671#issuecomment-222348091, if that's the target (although I was a bigger fan of what @aleph1 was building). If it needs to be started, I'd assume we'd want to use something like Jekyll (unless you have something else in mind)?

**Comment by asturur** [comment]
So i arrived at the point that i do not care for the look of it, as long as it looks modern-ish.
Like any other JS library.

There are more important things to take care of, someone else said he wanted to help on the fabricjs.com repository in this same organization.

it would be nice to:
- have something that is static generated as today
- play well with github pages
- is documentation focused ( so that adding documentation is easy, and that support somehow a translation method of any sort )
- can be started with a PR

Optional:

 - .MD files over html files

**Comment by asturur** [comment]
There is this repo here:
https://github.com/fabricjs/fabricjs.github.io

that is a complete playground and that can be used to start a proof of concept.
it points here
https://fabricjs.github.io/

**Comment by gustavorps** [comment]
Bountysource decided to update their Terms of Service:
>2.13 Bounty Time-Out.
>If no Solution is accepted within two years after a Bounty is posted, then the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource. For Bounties posted before June 30, 2018, the Backer may redeploy their Bounty to a new Issue by contacting support@bountysource.com before July 1, 2020. If the Backer does not redeploy their Bounty by the deadline, the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource.

**Comment by asturur** [comment]
Let me see if i can get this bounty back, bounty source is acting really shady lately.

**Comment by tiesont** [comment]
@asturur Were you able to get any resolution on this? If not, please contact me at the email shown on my profile.

**Comment by asturur** [comment]
there is a whole new site in progress on a repo here in the  organization.

I closed the issue because i see that bountysource is eating away the money
from the donors and i do not want them to get wasted.

You can check the work being done at http://fabricjs.github.io and on the repo with the same name

**Comment by tiesont** [comment]
I'm aware of that - I should have been more precise: were you able to get the bounty back? _That_ is what I wanted to talk about, if not.

**Comment by asturur** [comment]
No, wrote bountysource friday, let them alone in the weekend, trying again monday on email and social media eventually.
