### ISSUE TITLE
Create ActiveSelection with objects in group

### ISSUE THREAD

**Issue by jameszhong2008** [fabricjs/fabric.js#6776]
I want to create a multiple selection from objects in group.
After create selection with ActiveSelection, bound box of the ActiveSelection is wrong. 
How to select multiple object within group or nested group?

check it here.
https://jsfiddle.net/zhongjian2008/49wdsg2q/

**Comment by asturur** [comment]
http://fabricjs.com/manage-selection

Please first check if this answers your questions, and if it doesn't be specific on what.

**Comment by septemberjustin** [comment]
@asturur I think James wants to select specific objects in a group, which means if there are 3 objects in a group. 
When he select 1 or 2 objects, or even 3 objects in this group. He got wrong bound box.

**Comment by asturur** [comment]
Oh ok, that does not work, and is not in the planning for now.
It should't be hard to fix the bounding box to be honest, not hard at all.
And that would still help people that want to show as selected objects not directly by clicks but from some other kind of UI in an application.

**Comment by septemberjustin** [comment]
Thanks Andrea, you are very responsible. 👍 
Yes, users need to select objects on the object tree of the UI, especially there are multiple layers and groups.

**Comment by septemberjustin** [comment]
We really need this to work. (ʃƪˆ▿ˆ)

**Comment by asturur** [comment]
This should be fine and useful for me too. I just wonder about controls. Controls are mostly useless inside a group. I wonder who is responsible for hiding/showing them. The  developer or an option in the library.

**Comment by jameszhong2008** [comment]
@asturur @septemberjustin Thanks for your time and response, so you mean it should be implemented by developer rather than this library? 
ActiveSelection is convenient when we resize/move multiple objects together. So I want to know is there any chance that you can implement it within the library?(add multiple objects in a group or different group to ActiveSelection)

**Comment by asturur** [comment]
Jameszhong, i do not get what are you looking for. I think the library should correctly draw the box for a select object inside a group.

what are you looking for?

**Comment by septemberjustin** [comment]
@asturur James means the library should correctly draw the box and also show Controls for selected objects inside a group. 

Because when user drawing, they will group some objects, and they still need to adjust them inside a group. 
They don't want to ungroup them, then group them again. So, Controls are important inside a group. 

And users will also select multiple objects inside one group or between different groups. :) 

<img width="1135" alt="Screen Shot 2021-01-05 at 1 00 28 PM" src="https://user-images.githubusercontent.com/4484980/103608543-8f023380-4f56-11eb-9504-052722ab4259.png">

**Comment by asturur** [comment]
Worked a bit today on this.
At the end i trashed everything. I think i can solve it partially, not totally.
Drawing controls, and i m not sure it makes sense to solve it across different groups.

You cant select an object from group 1 and group 2 and put them in an active selections.
But you could create an after:render event and programmatically render controls of a couple of objects you want.

Need to think more about it.

**Comment by weixiaodeCode** [comment]
..

**Comment by septemberjustin** [comment]
Hi Andrea,
Thank you very much. What’s the reason for trashed everything?
You can also discuss solutions with James.

BTW, how about Travis reactive? How much is their plan?
Did you find any other tools to replace Travis?

Best Regards,
Justin

**Comment by asturur** [comment]
I trashed my attempt because i went too far and changed too much code and then it wasn't doing what i wanted.
For single objects is definitely doable, while i m not sure is doable for multiple objects scattered along different groups.

I swapped travis with github actions and is partially working , i still need to setup some piece, but this last week i have been inactive, i have also some health issue and i need to rest a bit. My inbox is full of fabricjs stuff and i m behind answering.

**Comment by septemberjustin** [comment]
Hi Andrea,
Thank you very much.
I think you can only consider single objects and multiple objects within one group at now.
Scattered along different groups function are complicated.
Is there any other contributor can help you handle some issues? Like Juriy Zaytsev or other people?

Thanks again, and take care yourself.

Best Regards,
Justin

**Comment by harm-less** [comment]
I'm currently working on a project similar to what @septemberjustin showed, but I ran into this issue as well.
I notice progress is being made on this issue, so that's great to see!

For me personally I'd be fine if the active selection works within 1 group only, but selecting objects scattered across multiple groups would be insane!

Personally I was thinking of making this work by switching contexts/levels similar to how Adobe XD or Flash Professional work. So you double click on a group (level 1) and suddenly you're "inside" the group (level 2). At the same time all the other groups or objects from the first level appear a bit more transparent or something. Then you can alter everything within this group and by clicking outside the group or perhaps with a breadcrumb system I can move back to level 1.

A workaround for this at the moment is ungrouping when you go a level deeper and regrouping them again when you go back. That means keeping track of the objects when heading back, but it probably will work.

**Comment by harm-less** [comment]
All right. I made it work for my current purposes.

**Navigator class:**
```ts
import {fabric} from 'fabric';


export interface CachedGroup {
	objects: Array<fabric.Object | null>;
}

export function replaceItemInArray(items: Array<unknown>, search: unknown, replaceWith: unknown) {
	const foundIndex = items.findIndex((item) => item === search);
	items[foundIndex] = replaceWith;
}

export class GroupNavigator {
	private _cachedGroups: Array<CachedGroup> = [];

	constructor(private canvas: fabric.Canvas) {}

	goIntoGroup(group: fabric.Group) {
		this.checkGroupCanvas(group);

		const groupSequence: Array<fabric.Group> = [group];
		let parentGroup: fabric.Group | undefined = group.group;
		while (parentGroup) {
			groupSequence.unshift(parentGroup);
			parentGroup = parentGroup.group;
		}
		groupSequence.forEach((group) => {
			this.goIntoRootGroup(group);
		});
		this.canvas.requestRenderAll();
	}

	goIntoObjectGroup(object: fabric.Object) {
		// todo: Potential performance improvement: It would be perfect if we could detect IF we have to go to the root or just go back to the commen parent and traverse back down
		this.goToRoot();

		if (object.group) {
			this.goIntoGroup(object.group);
		}
	}

	groupBack() {
		const highestGroup = this.popCurrentGroup();
		if (!highestGroup) {
			return;
		}
		const canvas = this.canvas;
		const activeSelection = new fabric.ActiveSelection(
			this.filterCachedObjects(highestGroup.objects),
			{canvas}
		);
		canvas.setActiveObject(activeSelection);

		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		const newGroup = (canvas.getActiveObject() as any).toGroup();

		const previousGroupUnfiltered = this.getCurrentGroup();
		if (previousGroupUnfiltered) {
			replaceItemInArray(previousGroupUnfiltered.objects, null, newGroup);
		}

		const previousGroup = this.getCurrentGroup();
		this.restoreObjects(
			previousGroup ? this.filterCachedObjects(previousGroup.objects) : canvas.getObjects()
		);
		canvas.discardActiveObject();
		canvas.requestRenderAll();
	}

	goToRoot() {
		while (this._cachedGroups.length) {
			this.groupBack();
		}
	}

	isOnRoot() {
		return this._cachedGroups.length === 0;
	}

	private goIntoRootGroup(group: fabric.Group) {
		if (group.group) {
			throw new Error('Must be a root group');
		}
		const currentGroup = this.getCurrentGroup();
		if (currentGroup) {
			replaceItemInArray(currentGroup.objects, group, null);
		}

		this._cachedGroups.push({objects: group.getObjects()});

		const canvas = this.canvas;
		const parentObjects = currentGroup
			? this.filterCachedObjects(currentGroup.objects)
			: canvas.getObjects();
		this.disableObjects(parentObjects.filter((object) => object !== group));

		this.ungroup(group);
	}

	private getCurrentGroup() {
		const groupLength = this._cachedGroups.length;
		return groupLength ? this._cachedGroups[groupLength - 1] : null;
	}
	private popCurrentGroup() {
		return this._cachedGroups.pop();
	}

	private filterCachedObjects(objects: Array<fabric.Object | null>): Array<fabric.Object> {
		return objects.filter(<TValue>(value: TValue | null | undefined): value is TValue => {
			return value !== null && value !== undefined;
		});
	}

	private disableObjects(objects: Array<fabric.Object>) {
		objects.forEach((object) => {
			object.opacity = 0.3;
			object.selectable = false;
			object.hasControls = false;
		});
	}

	private restoreObjects(objects: Array<fabric.Object>) {
		objects.forEach((object) => {
			object.opacity = 1;
			object.selectable = true;
			object.hasControls = true;
		});
	}

	private ungroup(group: fabric.Group) {
		const canvas = this.canvas;
		const items = group.getObjects();
		group._restoreObjectsState();
		canvas.remove(group);
		for (const object of items) {
			canvas.add(object);
		}

		canvas.discardActiveObject();
	}

	private checkGroupCanvas(group: fabric.Group) {
		if (!group.canvas) {
			throw new Error('Group not placed on any canvas');
		}
		if (group.canvas !== this.canvas) {
			throw new Error('Group not placed on the target canvas');
		}
	}
}
```

**Implementation:**
```ts
const canvas = new fabric.Canvas('canvas');
canvas.add(
	new Group([
		new fabric.Rect({
			width: 50,
			height: 50,
			fill: 'blue'
		})
	])
);

const groupNavigator = new GroupNavigator(canvas);

canvas.on('mouse:dblclick', (event) => {
	const target = event.target;
	if (target && target.isType('group')) {
		groupNavigator.goIntoGroup(target as fabric.Group);
	} else {
		groupNavigator.groupBack();
	}
});
```

Like I said, it works for my purposes, I hope it helps you if this was something you were looking for as well.
If you go into a group by double clicking on it, the objects outside of the group will be less opaque and non-selectable. Double clicking outside of the group will get you back one level.
When this issue is fixed this code will for the most part still be useful for me, it will just be simplified as I don't have to destroy and create new groups when navigating the object tree.

But I just encountered a scenario in which it's hard to go on with the current bug. I want to group all my content into a container that's can be scaled, zoomed or can be panned (similar to Photoshop or XD). But because all my content will be in a stage group, there's no way to select and transform objects on that stage without the bug appearing.

I think it's worthwhile to share a few possible solutions to this problem as the issue can be interpreted in many ways I think.

**Simple solutions:**
The simple solutions are restricted to selecting objects contained in just one group. You cannot have an active selection with objects from two or more groups, even if these groups are nested in each other. If you try and set an active selection with objects from multiple groups Fabric will throw an error in the console.

_Solution 1: Fix the issue for selecting objects from one group_
Just fixing the issue originally stated in this issue and implementing the active selection to be limited to objects from one group should go a long way and is probably the simplest solution. 

Pros:
- The Fabric API will not be changed

Cons:
- Developers will have to figure out how they will circumvent the active selection error themselves (but 1 or 2 demos could go a long way!)

_Solution 2: Use the features from the above group navigator_
Of course the active selection bug needs to be fixed, but it does make it very clear what's selectable and what's not. Probably a few extra properties could be added to the `Canvas` object to understand what's going on. I'm just not sure how well this solution would work as it's not very generic UI/UX wise.

Pros:
- UX is easy and will probably feel intuitive

Cons:
- Not a generic solution

_Solution 3: Add group property `subTargetsSelectable`_
Setting a group to `selectable = false` and `subTargetsSelectable = true` allows you to select objects within a group. Right now you cannot select an object as the group set to `selectable = false` will be disabled entirely and sub targets cannot be selected by just clicking on them.

Pros:
- Generic solution

Cons:
- No clear way of safeguarding selecting object from 2 different groups. But for example the behavior from solution 1 can be made into a demo to show a solution for the safeguarding).
- No easy way to manipulate both the group or its content individually. It could be you want to transform the group itself and in your next action an object in the group. With these properties you'd need a different mechanic to make that possible.

**Hard solution**
Allowing for the selection of objects across groups. This will be an incredible feat and will solve all problems experienced in this issue.

I think going for simple solution 1 will solve a lot of the issues the people from this issue are experiencing. The hard solution could come later if it's feasible.

I'd love to help on on the core issue of this problem in the Fabric code, but I'm not sure where to start. @asturur, you mentioned selecting objects within a group is not a hard issue: https://github.com/fabricjs/fabric.js/issues/6776#issuecomment-753644418
Could you give some pointers on how to handle this?

**Comment by harm-less** [comment]
I went into the code a little more today and I found it odd to discover an ActiveSelection object is rendered as a group and replaces the `group` (if set) from each object with the active selection object. I think I expected it to be a thing that keeps track of selected objects, renders the controls and that's it. 

I think the first step to make this work is to make sure the ActiveSelection doesn't override the group from the selected objects: https://github.com/fabricjs/fabric.js/blob/master/src/shapes/active_selection.class.js#L37

I did notice it doesn't show up in the `canvas.getObjects()` array at least.

But the next steps seem daunting to me at the moment as it looks like recursive group nesting will impact quite a bit of code, doesn't it?

**Comment by ShaMan123** [comment]
Hi all,
I'm interested is this feature as well.
I have managed to select and draw controls on a nested object but the control action is badly transformed because it doesn't take into account the group's transform if exists.
https://codesandbox.io/s/interesting-dew-w3yh1?file=/src/App.tsx

**Comment by ShaMan123** [comment]
related #6650 #6649

**Comment by harm-less** [comment]
@ShaMan123 You are getting closer indeed, great job! Do you think you can manage in getting this to work? Because if you can manage to make a MR, perhaps it can help @asturur by only having to review the code.

**Comment by ShaMan123** [comment]
#6650 has been merged so now it's a matter a drawing/positioning the controls properly and perhaps tweaking their actions

**Comment by harm-less** [comment]
Sounds good @ShaMan123. I've been attempting fixing this issue, but this is a bit above my head. So I'm rooting for you, haha 😉

**Comment by ShaMan123** [comment]
Yeah, it's a deep dive into internals but that's why I have put my finding in this file: https://codesandbox.io/s/interesting-dew-w3yh1?file=/src/fabric.extend.ts
Try fiddling with the commented methods. That's where the transformations should I occur I believe.

**Comment by harm-less** [comment]
Did you manage to make any progress @ShaMan123?

**Comment by ShaMan123** [comment]
Made progress.
https://codesandbox.io/s/prod-leaf-mjj0p?file=/src/fabric.extend.ts
`Canvas#findTarget` Logic:
1. try selecting nested object 
2. remove from group, add to canvas
3. `onDeselect` restore to group

**Comment by harm-less** [comment]
I see, you're definitely getting closer @ShaMan123!

Though I'm not sure sure why it works entirely 😅 
But if I understand your code correctly, you're finding and selecting an object inside a group. By doing this you remove it from the group and add it to the canvas. Lastly, on a deselect you return it back inside the group?
What I don't understand is how it could do that and not "forget" certain properties. 

For example. Imagine you scale the group. Let's say x1.2. If you select an item in the group and it get's added to the canvas. Does it get a scale of 1.2 for the time being as well? And when you deselect, will it detract that scale from the object again? 
And if so, I imagine it does this for all transform properties, right?
I hope this made sense.

Does this method any unwanted side effects btw?
For example right now I can't select multiple objects with the shift key.

**Comment by ShaMan123** [comment]
If raw. You'll need to add more logic to handle more cases, like multi select.
It needs logic to handle clipPath if you want to have the object visually bound to it's group.
And regarding transforms the only way this can happen is if you change the transform programmatically when the object is outside the group. Because any other case will deselect the object. You can handle such a case as well, doesn't seem too hard.

**Comment by asturur** [comment]
So i gave a stab to fixing control display in multiple situations ( we are talking about only display controls, not make them interactive inside groups.

This is what i could do:

![image](https://user-images.githubusercontent.com/1194048/121817107-96550800-cc7f-11eb-8181-3fc3c94ff5fa.png)

For now i do not understand where the offset come from, but i already know that probably padding would be broken and a skewed group or object would be broken too.

this thing seems simple but isn't at all.
The controlbox is made of 2 pieces. The borders and the controls.
The borders are influenced by stroke that scales with the object and the group, unless is strokeUniform=true so it scale only with the container ( and even there is questionable what should happen )
The border box stays rectangular, while the object can be squeezed, and so should do the controls.
With those rules multiplying the matrices is not useful and requires a lot of patches.

On top of that there is the padding area that influences both control and the box ( in the active selection the padding is ignored for semplicity sake )

**Comment by asturur** [comment]
With less changes we can still have a correctly drawn border box around a selected object, that is better than nothing.

**Comment by asturur** [comment]
This seems a bit better:
![image](https://user-images.githubusercontent.com/1194048/121822887-e0e77c00-cca1-11eb-80a8-be5419e7ad65.png)

but isn't really perfect.

**Comment by asturur** [comment]
test code
```js
function flattenObjects(objects, destination) {
  objects.forEach(({ _objects }) => {
    if (_objects) {
      destination = flattenObjects(_objects, destination);
    }
  })
  return destination.concat(objects);
}


const objs = flattenObjects(canvas.getObjects(), []);
objs.forEach((obj) => {
  obj._renderControls(canvas.contextContainer, {
    cornerColor: "yellow",
    borderColor: "purple",
  });
});
```

test data:

```
{"version":"4.5.0","objects":[{"type":"group","version":"4.5.0","left":133.89,"top":240,"width":253.22,"height":210.92,"angle":321.15,"objects":[{"type":"group","version":"4.5.0","left":7.99,"top":36.05,"width":161,"height":161,"scaleX":0.43,"scaleY":0.43,"objects":[{"type":"rect","version":"4.5.0","left":-80.5,"top":19.5,"width":80,"height":50,"fill":"red"},{"type":"rect","version":"4.5.0","left":19.5,"top":-80.5,"width":50,"height":70,"fill":"blue"},{"type":"rect","version":"4.5.0","left":19.5,"top":19.5,"width":60,"height":60,"fill":"green"}]},{"type":"group","version":"4.5.0","left":68.08,"top":-105.46,"width":85.76,"height":131.3,"angle":46.96,"objects":[{"type":"rect","version":"4.5.0","left":1.88,"top":-43,"width":80,"height":50,"fill":"red","scaleX":0.17,"scaleY":2.2,"angle":22.89},{"type":"rect","version":"4.5.0","left":-11.04,"top":-65.65,"width":50,"height":70,"fill":"blue","scaleX":0.38,"angle":26.64},{"type":"rect","version":"4.5.0","left":3.95,"top":25.28,"width":60,"height":60,"fill":"green","scaleY":0.31,"angle":290.63}]},{"type":"group","version":"4.5.0","left":-126.61,"top":-45.25,"width":113.05,"height":86.33,"scaleY":1.88,"angle":332.32,"objects":[{"type":"rect","version":"4.5.0","left":-37.06,"top":0.64,"width":80,"height":50,"fill":"red","scaleY":0.36},{"type":"rect","version":"4.5.0","left":25.11,"top":-43.17,"width":50,"height":70,"fill":"blue","scaleX":0.62},{"type":"rect","version":"4.5.0","left":-56.53,"top":-17.83,"width":60,"height":60,"fill":"green","scaleX":0.6}]}]},{"type":"group","version":"4.5.0","left":194.14,"top":42.81,"width":79.65,"height":136.11,"objects":[{"type":"rect","version":"4.5.0","left":-39.82,"top":-48.7,"width":80,"height":50,"fill":"red","scaleX":0.59},{"type":"rect","version":"4.5.0","left":9.97,"top":-68.06,"width":50,"height":70,"fill":"blue","scaleX":0.59},{"type":"rect","version":"4.5.0","left":-8.68,"top":7.06,"width":60,"height":60,"fill":"green","scaleX":0.59}]}]}

```

**Comment by harm-less** [comment]
Awesome to see these attempts guys.

It seems like combining some of the ideas from the both of you could result in a nice solution.

I think if it's possible to select and transform objects that are nested 2 or more layers deep and next to that a multiselect (within the same group), you'd solve most issues most of the people in here seem to have 👌

**Comment by ShaMan123** [comment]
This is next on my list.
Once we rewrite `Canvas#_chooseObjectsToRender` this issue will be resolved.

**Comment by ShaMan123** [comment]
A bit more work and we're there
https://jsfiddle.net/twLoj8gv/2/

**Comment by ShaMan123** [comment]
For all interested you are welcome to test changes in the mentioned PR
