### ISSUE TITLE
Create a path from object

### ISSUE THREAD

**Issue by tran-ngoc-phuong-dang** [fabricjs/fabric.js#6779]
Hi. Im new to fabricjs and want to use the text on path feature to make text following specific shapes but I don't want to manually specify the path. I want to add shape objects then get the path from the objects then apply the text on path. I tried doing it like this

var circle = new fabric.Circle();
var path = fabric.Path.fromObject(circle);
var text = new fabric.Text('Text', { fontSize: 10, path: path, top: path.top, left: path.left });
canvas.add(text);

But the path return empty. How do I extract the path from Circle or Rect objects?

**Comment by asturur** [comment]
First of all, Text on path is a beta feature and still needs lot of improvements.

Secondly, in order to get paths as specific shapes, you better create them with some software. Text on a path will behave differently depending if the path is clockwise or counter clockwise.

Fabric does not offer this functionality out of the box

**Comment by saberjsd** [comment]
@tran-ngoc-phuong-dang 
Farbic not support basic shap for path text.
We can use this path to describe circle `M70 0 C140 0, 140 100, 70 100 C0 100, 0 0, 70 0Z`
```js
const path = new fabric.Path("M70 0 C140 0, 140 100, 70 100 C0 100, 0 0, 70 0Z");
const text = new fabric.Text("Text",{fontSize: 10, path});
```
For more use case from basic shape convert to path, look here: [https://www.zhangxinxu.com/sp/path.html](https://www.zhangxinxu.com/sp/path.html)
