### ISSUE TITLE
canvas.toJSON not working ajax call

### ISSUE THREAD

**Issue by subhash8108** [fabricjs/fabric.js#6794]
## Version
4.2.0

## Issue Details
If I use JSON.stringify(canvas) the element of my object is removed. but working ajax function, and I use canvas.toJSON(['_element','_originalElement']) the element of my object is not remove. but same time ajax not working. please help me how to solve my issue. **I want to call an Ajax function with an element**

## Not Working ajax call
```
var json = canvas.toJSON(['_element','_originalElement']);
var ajaxdata = {'action':'canvas_save',"canvas_data":json};

jQuery.ajax({
      method: "POST",
      //dataType: "json",
      url: the_ajax_script.ajaxurl,
      //data: ajaxdata,
      data: {'json': JSON.stringify(ajaxdata)},
      //cache : false,
      processData: false,
      contentType: false,
      success: function(msg){
	      var msgdata = JSON.parse(msg);
	      console.log(msgdata);
      }
});
```
How to ajax call with "canvas.toJSON" without lost my element data. you can see my below screenshot

![elements](https://user-images.githubusercontent.com/542535/103925004-e530cb80-513c-11eb-81b8-d5bcf2051783.png)

When I do stringify the _element goes out. you can see my below screenshot

![stringify](https://user-images.githubusercontent.com/542535/103925340-612b1380-513d-11eb-89db-f76946ea63b0.png)

After doing canvas.toJSON it works fine if I do canvas.loadFromJSON.

If I do canvas.toJSON, the issue of renderer comes in Ajax

Please help me. I need your help

**Comment by asturur** [comment]
So this is not a fabricJS or javascript problem, is a general issue with working with transferring things over the network.
When you say ajax call i have to assume you want to send this data somewhere.
JSON.stringify does not include those elements because it has to output a string and there isn't a string counterpart of the DOM elements.
Adding the properties to toObject will create a Javascript object with 2 properties that reference those elements, and that is fine, but sending them over an http request isn't possible.

The JSON data should be enough to represent your canvas somewhere else and isn't clear in first place why you want to transfer those extra properties too.

**Comment by asturur** [comment]
On top of that, please understand that `I want to call an Ajax function with an element` isn't a fabricJS related requirement or problem. Is something you want to do and is completely disconnected from the end goal you are pursing.
This is summarized in the xy problem: https://en.wikipedia.org/wiki/XY_problem. Be mindful when you ask help on forums/issue trackers so that other people can actually help you. It took me 3 days to get to this email, and i couldn't help becuase the question wasn't clear, and that is time wasted mostly for you.
