### ISSUE TITLE
Shadow is over text if objectCaching=false and charSpacing !=0

### ISSUE THREAD

**Issue by alex-gross** [fabricjs/fabric.js#6802]
## Version
4.3.0

## Test Case
http://jsfiddle.net/fm4hg6dr/

## Information about environment
Browser Chrome

![image](https://user-images.githubusercontent.com/29940389/104331230-233c3f80-54ef-11eb-8410-9de9149f36fc.png)

**Comment by asturur** [comment]
In the task of creating a minimal reproducible case, why leaving `charspacing: 1` in the test case?

**Comment by alex-gross** [comment]
My bad with charspacing: 1, sorry. Anyway, why is the shadow over the object?

**Comment by asturur** [comment]
Because of charspacing indeed.
If you would have tried to reproduce a minimal, minimal, case you would have figured out that removing charspacing would have removed the issue too, and opened an issue with the correct title.

Or at least you would have searched in the issues for shadow and charspacing and found this:
https://github.com/fabricjs/fabric.js/issues/5808

There isn't much we can do about this.
We can force the object to render with cache if charspacing and shadow are used, or specify in docs that this will happen because each char is drawn separately and so each of them is going to throw a shadow on its own.
