### ISSUE TITLE
Add canvas option to automatically delete objects out of bounds

### ISSUE THREAD

**Issue by acdvs** [fabricjs/fabric.js#6825]
I've been struggling with implementing this manually in while dealing with the caveats of other libraries I'm using in my current project (e.g., React/Redux).

It would be nice to have an extra option on the canvas initializer to specifcy if any objects dropped completely outside of the canvas bounds (`Object.isOnScreen`) should be automatically removed. It seems to me that there isn't ever a case where you'd need to keep this data around if your reason for using Fabric is for user interaction.

**Comment by asturur** [comment]
What is stopping you to do it with the moving/scaling events?

**Comment by acdvs** [comment]
Nothing at all, and that's exactly what I'm doing. My concern is that this is functionality that is undoubtedly widely used and also easy to implement, so why not build it into the library?

**Comment by asturur** [comment]
Because the library is already big and complex to document / maintain.
More features, more interactions between each feature, more bugs or unexpected behaviours for peoples that think the default behaviour should be different.

We try to provide an easy way to manage basic things on canvas and provide api and example to handle use cases like this.

**Comment by acdvs** [comment]
> Because the library is already big and complex to document / maintain.

That isn't a valid reason. This is an open source library and you should expect people to want new features and improvements.

> We try to provide an easy way to manage basic things on canvas and provide api and example to handle use cases like this.

Sure, that's understandable. But as I said initially, this is something that makes absolutely no sense _not_ to have in the library. If you're using Fabric for user interaction with a canvas, why would you ever want objects to get lost outside the boundaries?

**Comment by asturur** [comment]
I do expect and i do see people wanting to add new features every day. And i have to act as a gatekeeper, using human judgement on what is beneficial and what not. With the risk of making the wrong choice.

Sometimes you have to choose the lesser evil, really.
I maintain the library mostly alone, getting new focused willing maintainers is rare.
the more features, the more expectations the more requests and issues.
My personal experience is that when you get 10-20 daily emails about issues, you start to loose hope to keep up, and you let go. At that point people start to perceive the project as dead or unmaintained.

This feature probably ends up being:

```
canvas.on('object:modified', function(opt) {
  if(!opt.target.isOnScreen()) { canvas.remove(opt.target); }
});
```

or something very similar to this.

Now after some time someone could come and say, i implemented the zoom and pan feature, and isOnScreen isn't exactly what determine if my object is out of bounds, in my case for example is the intersection with the backgroundImage.

And then you have to wonder how to handle the difference, maybe with another option. outOfBounds and outOfBackground for example.
`featureCreep` https://it.wikipedia.org/wiki/Feature_creep is a reality for old libraries like that.

I do not want fabricJS to look a crappy chunk of code  more than is today, and i would like to be able to keep maintaining it without giving up.
In the long run, a nice tutorial article of one page, explaining how to use events to craft the functionality you want is more beneficial for the project than adding the feature itself, because it educates and document the developers on the available tools and how to use the library.

For example i would appreciate if you would write a small article/page with the codepen to teach people how to implement this.

**Comment by melchiar** [comment]
@asturur is correct. Deleting objects that are outside of the canvas would be a highly specialized behavior that's not likely to be widely used and very easy to achieve with the current set of features. Consider as well that objects on the canvas all have an index, and deleting objects automatically based on their screen position will change the index of other objects which would be confusing for many users.

New features should either provide completely new functionality (ie. text on a path), or improve/simplify existing ones (ie. speed/performance optimizations), but the main goal is to give devs the tools they need to achieve their purposes which in this case it does very well.

**Comment by acdvs** [comment]
Those are all very good points. Thanks for taking the time to explain your reasoning.
