### ISSUE TITLE
Where did the lockUniScaling property go?

### ISSUE THREAD

**Issue by carterw485** [fabricjs/fabric.js#6849]
This property was in `Version 4.0.0-rc.1` and `Version 3.6.6` but is not in `Version 4.0.0 +` with no mention of removing the property in the release notes.

Is there a new way to allow non-uniform scaling when using a corner control point?

**Comment by asturur** [comment]
I think we went over the topic on some issue on the repository, if you didn't do already try a search on the closed issues.

The removal is mentioned at least here:
http://fabricjs.com/v4-breaking-changes

The feature can probably be obtained with the control api anyway.

**Comment by Niels-NTG** [comment]
I've read through the various issues and PRs related to this issue. The new control API is great, but doesn't really address the problem caused by the removal of the `Object.lockUniScaling` property. I do understand why the previous implementation lead to confusion with the behaviour being swapped and all that. But there is still a use case for not ever letting the user non-uniformly scale an object of a specific type or instance. I would propose to instead implement it slightly differently: `Object.keepAspectRatio`, a boolean value that prevents an object from being scaled non-uniformly, irregardless from if `Canvas.uniScaleKey` is being pressed or the value of `Canvas.uniformScaling`.

**Comment by asturur** [comment]
but what is wrong with just removing the middle scaling controls and avoid the free-form scaling on the corner`s one?

**Comment by Niels-NTG** [comment]
I would like to lock my users out of free-form scaling all together for certain type of objects.
