### ISSUE TITLE
customized contols apllied to Object prototype

### ISSUE THREAD

**Issue by Rad1calDreamer** [fabricjs/fabric.js#6860]
## Version
4.3.0

## Test Case
https://codepen.io/Rad1calDreamer/pen/VwmmpqR

## Information about environment
browser

## Steps to reproduce
create object and set it some custom control.
Create another object
## Expected Behavior
custom control has applied onlly for target object
## Actual Behavior
custom control has applied for all objects

**Comment by asturur** [comment]
Hi @Rad1calDreamer , this is standard JS class/objects mutation feature or issue as someone prefers to call it.
Mutation is part of JS.

Now in the case i have seen in your codepen, you are doing this:

```
rect.controls.myControls = something.
```

Now if you don't set anything specific to rect before, rect.controls is a reference to  fabric.Rect.prototybe.controls, right?
So adding a property to rect.controls, is adding a property to fabric.Rect.prototybe.controls, to all objects.

If you want to create a new control set, you can do this:

var controlSet = `{ ...fabric.Rect.prototype.controls }`  or ` Object.assign({}. fabric.Rect.prototype.controls)` this will create a new object with references to the same controls. Adding a new control to controlSet will modify only this controlSet and so the object to which you assigned it.
```
rect.controls = controlSet
```

Be aware that each control is still a reference, so changing `rect.controls.tl` equals to changing any `tl` controls to every object. But removing tl from rect, won't. Because you will be removing the reference to tl in your new control set and not removing tl itself.

I hope this clarify a bit things.

I'll flag this as `docs` related, and hope that maybe someone will extend our custom control guide with this topic.
