### ISSUE TITLE
How to change the zIndex of objects,b for example, to put some objects in the bottom layer.

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#6952]
I tried using 'canvas. sendToBack (obj)' ,but it didn't work

**Comment by melchiar** [comment]
Hi. The correct syntax is `canvas.sentToBack(obj)` as indicated in the docs 
http://fabricjs.com/docs/fabric.Canvas.html#sendToBack

If you've found a bug or it's not working as you expect please follow the issue template and provide a jsfiddle demonstrating the issue so that we can help. I'm going to close the issue but feel free to update it if you can provide more information.
