### ISSUE TITLE
Adding Freehand with ClipPath to Object Group

### ISSUE THREAD

**Issue by Neuroforge** [fabricjs/fabric.js#6955]
Hello,

I am working with Fabricjs and i'd like to draw inside of a circle and have the path constrained to the circle. This includes the selection area of the group.

UPDATE:

Seem to have solved the first point

http://jsfiddle.net/42snph1d/14/

**However, the selection are is too big. Anyway to reduce it so it is the side of the circle and not the path?**

**Is it possible to truncate the PATH to only include points inside the circle?**

--------------------------------------------------------------------------------------------------------------

http://jsfiddle.net/42snph1d/12/

I am seeing weird artefacts when moving the object around. 

1) The freehand drawing can be seen in the canvas outside of the circle when moving
2) The group selection is large, includes the entire freehand drawing. I'd like the selection area to only contain the circle.

Any obvious fixes here?

![circle](https://user-images.githubusercontent.com/1474186/112420682-bca29000-8d81-11eb-84c6-7f8a7ca5ed3c.gif)

Any advice would be appreciated.

**Comment by asturur** [comment]
today there isn't. But is something we want to solve since long, together with clipPath blurryness.
The issue could be solve at multiple levels, but i think the easiest is when we draw the control box and controls.

If you do not need much editing you can still clone you circle + drawing to image with the proper method, cutting away transparent pixels.

If that would work for you i can try to write an example.
The object would become an image then, and wouldn't be a circle anymore.

**Comment by ShaMan123** [comment]
I have solved this issue. It is related to progress made by #6994. Though I should PR this new functionality but wasn't sure it was needed

**Comment by ShaMan123** [comment]
My approach consists of creating a group that contains the circle and the path and a clip path identical to the circle. This way only the area of the circle will be visible. To make this work properly I have patched `fabric.Group` to calculate it's size according to the given object (circle in your case). This issue was exactly something I needed.
@asturur are you interested?

**Comment by ShaMan123** [comment]
BTW I've patched the brush as well and applied a clip path to it as well to create an effect that the brush draws only on the desired object

**Comment by ShaMan123** [comment]
duplicate #5431

**Comment by asturur** [comment]
Yes is a duplicate.
