### ISSUE TITLE
Simple zoom question

### ISSUE THREAD

**Issue by clenemt** [fabricjs/fabric.js#7016]
Can a smart person explain or point me in the right direction as to what this is doing `zoom *= 0.999 ** delta;`?

Taken from the zoom and pan intro: http://fabricjs.com/fabric-intro-part-5
```js
canvas.on('mouse:wheel', function(opt) {
  var delta = opt.e.deltaY;
  var zoom = canvas.getZoom();
  zoom *= 0.999 ** delta;
  if (zoom > 20) zoom = 20;
  if (zoom < 0.01) zoom = 0.01;
  canvas.setZoom(zoom);
  opt.e.preventDefault();
  opt.e.stopPropagation();
})
```

Thanks 🙏

**Comment by melchiar** [comment]
It's a way of translating a scroll event into a zoom adjustment. 

deltaY represents the amount and direction being scrolled (can be positive or negative depending on whether scrolling down or up)

`0.999 ** delta`
** is an exponential operator which raises 0.999 to the power of delta. 0.999 is just a number slightly less than 1 so that based on the direction of scrolling, the zoom amount is multiplied to be either slightly bigger or slightly smaller than it is currently. If you changed this number to say 0.99 you'd notice the zooming change from scrolling greatly increase.

**Comment by asturur** [comment]
I think it was corrected by someone in this way in order to accomodate the fact that trackpads scroll why differently from wheels.

**Comment by clenemt** [comment]
Thanks for the nice answer !
