### ISSUE TITLE
Object scaling stops after event handling

### ISSUE THREAD

**Issue by sparklesprod** [fabricjs/fabric.js#7132]
Hey,

I am trying to implement handling the zoom event to make it slower. I have attached an example of the problem. It seems that I manage to make the scaling slower, but I get an incomprehensible behavior. At one point, the scaling stops and I have to deselect the object, and then select it again. After re-selection, I can again scale to a certain value, and then stop again.

jsfiddle: http://jsfiddle.net/sparklesprod/bz0on8ge/

**Comment by asturur** [comment]
hi @sparklesprod , it stops scaling because you hit the point of the lockScalingFlip that you disable.
I think the only way to get a full custom behaviour is to use the custom control api and not events.
Think of events like something you can use to do something outside fabricJS when scaling happen, but not to modify the scaling itself.
