### ISSUE TITLE
Selection highlighting smudges canvas while animating

### ISSUE THREAD

**Issue by vpanichkin** [fabricjs/fabric.js#7216]
## Version
4.5.1

## Test Case
http://jsfiddle.net/m0jpr3Ld/

## Information about environment
Chrome 91.0.4472.114

## Steps to reproduce
1. Double click on the word "text" to select it
2. If the word it selected, the text will move to the top

## Expected Behavior
Selection highlighting does not smudge the canvas
![image](https://user-images.githubusercontent.com/16993030/125945684-14d8ea60-238a-4ab3-af41-15a40a04d847.png)

## Actual Behavior
Selection highlighting is drawn "a path" while animation
![image](https://user-images.githubusercontent.com/16993030/125945335-9f921b07-3696-429c-baf4-083f8a1f24c7.png)

P.S. Same happens with a cursor 
![image](https://user-images.githubusercontent.com/16993030/125945410-4c39b227-2eb8-42f2-b2a1-8e3e4c39e6e7.png)

**Comment by Hammer-Inc** [comment]
Looks like the root cause is `IText.clearContextTop` only clears the area inside of the text box, a little bit of whatever is drawn gets left behind if the object moves before the next render cycle.

Would it be safe to clear the entire top context? Or would the preferred option be to store the last known coords of a selection/cursor during the render cycle and clear that area next time around.

I'd love to help out and this seems like a straightforward bug to dip my toes into, would love to hear what the preferred approach would be.

**Comment by asturur** [comment]
Alternatively is maybe possible to do a better sync of the request animation frame with the current object position

**Comment by Hammer-Inc** [comment]
I'll take a shot at option #2 and raise a pr when it's done. ☺️

**Comment by asturur** [comment]
yes please! if you have questions ask
