### ISSUE TITLE
Selectable attribute removed on serialization

### ISSUE THREAD

**Issue by gregdaynes** [fabricjs/fabric.js#7221]
## Version
4.5.1

## Test Case
http://jsfiddle.net/gregdaynes/L3mzykb2/7/

## Information about environment
Nodejs or browser? Both
Which browsers? All

## Steps to reproduce

1. Create a canvas
2. Add an object to the canvas (jsfiddle above uses circle)
3. set `selectable = false` on the new object 
3. Call `toJSON()`, `toObject()`, or `JSON.stringify` on canvas
4. Inspect the results - notice the object does not have a `selectable` attribute 

## Expected Behavior

serialized canvas objects should have `selectable` attribute

## Actual Behavior

`selectable` attribute is removed during serialization

**Comment by melchiar** [comment]
Hi! Not every property is included by default in an object's serialization. This is by design since having every property causes JSON bloat that is unnecessary for most applications. For the selectable property there are 2 approaches I'd recommend.

First, if selectable is something that should either always be `false` for all objects or for a specific type of object, you can change the default setting like this:

`//for all types of objects`
`fabric.Object.prototype.selectable = false;`

Or

`//for a specific object type (eg. rect, textbox, etc.)`
`fabric.Rect.prototype.selectable = false;`

Alternatively, if you really do need to store the `selectable` property in JSON, the `toJSON` method lets you pass in an array of extra properties to include.

`JSON.stringify(canvas.toJSON(['selectable']));`

**Comment by gregdaynes** [comment]
@melchiar thank you for your reply! each of those solutions works well with how I'm working with Fabric, and now that I've gone back to re-read the tutorial and docs, I understand what I was reading.

**Comment by melchiar** [comment]
Glad it helped! The PR is still appreciated.

**Comment by asturur** [comment]
So in theory the defaults are putting in JSON only the values that represent the canvas content, but not application properties and interactivity. That is the default. Graphic yes / interactivity no.
