### ISSUE TITLE
Global canvas zooming [$1,091 awarded]

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#731]
Posibility to zoom canvas (+/-) and all it's objects.

Here are some ideas from @kangax:
1. Programmatic canvas zooming
   One zoom level property (1 by default = normal zoom)
2. UI for canvas zooming
   UI is a secondary thing; we can do it _after_ implementing programmatic zooming. For this, we'll probably need to introduce another canvas mode, similar to free drawing mode. When in that mode, canvas would zoom on click or dblclick or whatever. You wouldn't be able to select objects (similar to free drawing mode).

I like how zoom works in google docs. I think we should base off of that.

Other ideas:
- Touch device compatibility: Zoom in/out with touch
##

**Comment by saran110313** [comment]
image zooming function server and client same function.

**Comment by ajck** [comment]
@kangax @asturur I guess this ( @twffy 's solution) got implemented in Fabric as the setZoom (etc) and absolute/relativePan in Fabric.Canvas. But wondering how to make these work with touch and mouse events? Do we have to implement out own mouse/touch event tracking then use the pan and zoom commands to update the canvas accordingly? Or is there anything like a mode built into Fabric whereby objects are disabled momentarily and the end user can zoom and pan with mouse or touch?
Thanks!

**Comment by jafferhaider** [comment]
@ajck In my app we use a 3 finger pan gesture to allow the user to pan the entire canvas. You can attach a listener for complicated gestures like this using EventJS that comes bundled with FabricJS if you build it with the Gestures module.

You could write custom code to make all items unselectable, and lock their movement rotation etc. when a pan gesture starts. Just loop over each object in the canvas and set their `selectable`, `hasControls`, `lockScalingX` etc. flags.

**Comment by ajck** [comment]
Thanks @jafferhaider that's helpful - do you know of any publicly available code that would give a head start on this? Many thanks.

**Comment by hichem147** [comment]
hello all, Pan and Zoom and getting the good mouse coordinates 
for the pan  I used : 
------------------------------------------
canvas.on('mouse:move', function (e) {
	if (panning && e && e.e && PanMode) {				
		var delta = new fabric.Point(e.e.movementX, e.e.movementY);
		canvas.relativePan(delta);
	}
});
------------------------------------------
for the zoom I used : 
$(canvas.wrapperEl).on('mousewheel', function(e) {
	var delta = e.originalEvent.wheelDelta / 6000; // to get +/- 2% 
	var pointer = canvas.getPointer(event.e);			
	var posX = pointer.x;
	var posY = pointer.y;			
	var zoomCenter = new fabric.Point(posX,posY);
	var zoomValue = canvas.getZoom() + delta;
	canvas.zoomToPoint(zoomCenter, zoomValue);
});
------------------------------------------
I draw a grid by 20/20 to know where I am in the canvas.


and when I pan, then, I zoom, the mouse position, is not anymore the zoom center
the same thing happens when I zoom, and I change the mouse position to have another zoom center

my knowledge about this kind of problems is 
we have the view coordinates of the mouse
and the "canvas" coordinates of the canvas content (objects)
and between the two coordinates, there is the zoom scale, and the origin coordinates (x0, y0)

you find here the source code used 

the test case is the following
I add some rectangles, I zoom with the wheel
all is fine, 
I move the mouse, I zoom with the weel, nothing goes as expected
what is expected ? that the mouse position is the zoom center

to pan, I just click the Pan Button

could you help me ?
I thank you for this wonderfull graphics library :+1: 
[Pan_Zoom.zip](https://github.com/kangax/fabric.js/files/299412/Pan_Zoom.zip)

**Comment by hichem147** [comment]
Finally I found that the necessary coordinates I need, 
            are e.offsetX, and e.offsetY
and it works fine
and the coordinates that I get whith getPointer are in the real system

$(canvas.wrapperEl).on('mousewheel', function(e) {
	var target = canvas.findTarget(e);
	var delta = e.originalEvent.wheelDelta / 6000; // to get +/- 2% 
	if (e.altKey) delta = e.originalEvent.wheelDelta / 1200;
			
	var pointer = canvas.getPointer(event.e);			
	var posXobj = pointer.x;
	var posYobj = pointer.y;
			
	var posXview = e.offsetX;
	var posYview = e.offsetY;
			
	var zoomCenter = new fabric.Point(posXview,posYview);
	var zoomValue = canvas.getZoom() + delta;
			
	canvas.zoomToPoint(zoomCenter, zoomValue);
});
