### ISSUE TITLE
textPath total length doesn't consider charSpacing

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#7333]
## Version
4.5.1

## Test Case
https://jsfiddle.net/melchiar/y2rdwskL/

## Information about environment
Browser

## Description

Looks like we forgot to consider `charSpacing` in the total width calculation. Here's a centered text path with a `charSpacing` value of 200 (the text is offset to the left)

![image](https://user-images.githubusercontent.com/9057412/131190257-20517477-1ea0-4e7b-89f5-b3accff1dbe1.png)

**Comment by yengAbe** [comment]
Hello. If you change the character spacing, it will move like a movie.
Focusing on the left draws the character out of bounds.
And The area drawn on the right side becomes narrower.
Is it because the total length of textPath doesn't consider charSpacing?
Any progress on this issue?

https://codesandbox.io/s/github/yengAbe/pathTxt

https://user-images.githubusercontent.com/66228369/189582734-c589c3c4-eb97-4581-8ac6-1794f1ee0ff4.mp4
