### ISSUE TITLE
Skewing bug when destroying group or removing elements from group

### ISSUE THREAD

**Issue by aastefian** [fabricjs/fabric.js#7501]
## Version
4.6.0 - but happens since 1.6.0

## Test Case
http://jsfiddle.net/aastefian/6dv5b1pq/80/

## Information about environment
Browser: Version 95.0.4638.69 (Official Build) (64-bit)

## Steps to reproduce
Create a shape element (maybe all elements have the bug but didnt test yet), add skewY to it (lets say 20), create a group with that element and then call `destroy()` on the group or `removeWIthUpdate()` on every element in the group.

## Expected Behavior
skewY should stay 20. Angle and skewX should not be modified. We depent on this because we have a web editor in which all attributes are very visible and it is very bad UX to see all values shifting around when ungrouping.

## Actual Behavior
The element's state gets modified and skewY is set to 0 and skewX and angle are given values which visually makes the shape look same(almost identical) but the attributes are set incorrectly (skewY is reset to 0, skewX and angle get a value).

This bug seems to have been introduced when going from version 1.5.0 to 1.6.0 with the introduction of `qrDecompose ` function which seems to decompose the transform matrix into different transformations but always extracts skewY as 0. this might be a down side using QR decomposition which only extracts angle, scaleX/Y skewX but **not** skewY. I am thinking maybe a combination of LU decomposition and QR decomposition might give us all transforms (but this is just a theory, not sure if its mathematically possible even). Also, not sure if the 2x3 matrix actually stores all transformations including skewY or not.

I already worked on a small fix but I didn't figured it out quite yet, i will let you know if i can propose a PR.

Check: https://github.com/fabricjs/fabric.js/compare/v1.5.0...v1.6.0# on line 523 of misc.js, this is where the function was added.

**Comment by asturur** [comment]
Hi @aastefian this is by design, i'm sorry.
If you manage to fix it, great.
When objects are grouped, all the properties of the object and parents get saved in a single transform matrix of 6 numbers.
From those 6 numbers we need to pull out:

- top
- left
- angle
- skewX
- skewY
- scaleX
- scaleY

7 informations.

7 variables, less equations, we need to fix one of those to a constant.
The only working math formula i found requires skewY to be set at 0.

**Comment by aastefian** [comment]
I see. But when you apply skewing on a group do you apply on the matrix both skewX and skewY or not?

I want to understand if the information is even there in the first place and it's only a matter of exctracting it with the right math.

**Comment by asturur** [comment]
is in the matrix or you wouldn't be able to visualize it.

WIth 7 variables and less equations you have more than one solution available and you have to pick one.
In order to maintain skewY for example you should say, i know angle is 30 and i keep that as a reference, but the math to figure that out is out of my reach. Writing the current one was already hard.

Another example is that you use the same logic on something has has flipX and flipY you will get no flipping but a rotation of 180degree.
