### ISSUE TITLE
Image getting clipped (`objectCaching`?)

### ISSUE THREAD

**Issue by kimgyucheol** [fabricjs/fabric.js#7547]
## Version
3.6.0

## Information about environment
Nodejs or browser?
Which browsers?
> Chrome

If you move(draging) it, part of the image disappears.
It seems to be a cache, but I don't know where to fix it.
**Please tell me how to properly update a distorted Caching image.**

* when not moving.
![image](https://user-images.githubusercontent.com/24641518/145921237-9474d421-946b-44b9-bcf7-3a05d4207272.png)

*When you grab an image and move it.
![image](https://user-images.githubusercontent.com/24641518/145921029-1e278e3f-a448-4799-9aae-d6df24706188.png)

Look at the area circled in purple.
image is cropped.

I tried hard to find a solution, but to no avail.

**Comment by kimgyucheol** [comment]
when not moving.
![image](https://user-images.githubusercontent.com/24641518/146329745-c1909e79-538e-4f4f-81c5-8c44ae0c71fb.png)

when moving or add apply clipPath
![image](https://user-images.githubusercontent.com/24641518/146329895-a8cbb811-8db0-4f97-8e3a-8be9bf4a071b.png)

**Comment by ShaMan123** [comment]
Beautiful controls!
You should provide a working repro or else it's impossible to help.
Try the following:
1. set `img.dirty=true`, then `canvas.requestRenderAll`
2. `objectCaching=false` is a bad idea but it will help to determine if caching is the problem.
3. If your image is nested inside a custom object this makes sense because the parent doesn't know about the change in position of the image
