### ISSUE TITLE
Straight line blurry when rendering JPEG/PNG with toDataURL

### ISSUE THREAD

**Issue by septemberjustin** [fabricjs/fabric.js#7548]
I just render jpeg/png by canvas.toDataURL with quality 1. 
I always got some unnecessary expansion besides the straight line, and I don't know why? 

See the comparison of 400*400 px rectangle with 3 px stroke:
Sketch exports the left one; 
Fabric.js export the right one.
![image](https://user-images.githubusercontent.com/4484980/145921747-e4274d70-82b8-4360-98d9-540dce95f47a.png)

PS: the objectCaching has been disabled. 
Are there any suggestions?

**Comment by cosoc** [comment]
最近我也用他写了一个项目,可能是高分屏幕,解决方法我使用了导出toSVG()

**Comment by ShaMan123** [comment]
please provide a working repro

**Comment by septemberjustin** [comment]
I tried to position objects in pixels.
Zoom canvas, scale and move with only integers, and then this issue got fixed. 
So, the problem may because cross pixels.

**Comment by asturur** [comment]
the problem is for sure cross pixels.
Probably sketch fixes that under the hood.
Sometimes the problem can be retina scaling.
A 3 pixel border is bound to be blurry because it will 1.5 pixels inside and 1.5 pixels outside, but when you work on a mac or on a device that has twice real pixles compared to css pixels you won't notice it.
