### ISSUE TITLE
SVG Export files does not open in Corel Draw

### ISSUE THREAD

**Issue by dean555** [fabricjs/fabric.js#758]
When we try and open the SVG files in Corel Draw 14 then it does not show any design. But the SVG files opens file in Adobe Illustrator

**Comment by Omid-Heydarzadeh** [comment]
@kangax another issue with corel draw is related to rectangle objects with rx/ry equal to zero. I have to manually remove rx="0" and ry="0" from SVG export to be able to import the file into corel draw correctly.

**Comment by asturur** [comment]
Hi @Omid-Heydarzadeh, are rx and ry equal to 0 a violation of some spec?
If they aren't we can't really maintain a series of edge cases for supporting proprietary softwares that do not support the svg specs.
I think it would be easier if you overwrite the rect toSVG method in order to fix that in your application
