### ISSUE TITLE
vue3 error

### ISSUE THREAD

**Issue by listener-dong** [fabricjs/fabric.js#7618]
vue3+vite2
编译环境没有报错，打包后出现警告，导致画图经常不显示也不能操作
`[Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function.`

**Comment by asturur** [comment]
Hi @listener-dong we don't have many VUE3 experts here, probably none.
In order to eventually help you we need:
- a reproducible small case
- we need to rule out which is the broken combination (vue3 or vite2)

Also please look into older vue3 questions, there was some issue about using raw variables or something like that.
