### ISSUE TITLE
Text's control box doesn't match the text when it follows a path.

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [fabricjs/fabric.js#7679]
Is it a bug or I did something wrong?

https://jsfiddle.net/Neimeg/4cxsv7mz/1/

![image](https://user-images.githubusercontent.com/6233059/153922809-ef0155a5-c123-4a04-820f-9fa273864f83.png)

**Comment by asturur** [comment]
@EdnaldoNeimeg Also consider that the feature has been introduced, is not bad, but also is not perfect.
I m sure the cursor is still messed up

**Comment by EdnaldoNeimeg** [comment]
> The control box for text on a path is drawn to the dimensions of the path itself. This is the done the same way in other design suites such as InDesign and Illustrator.
> 
> ![image](https://user-images.githubusercontent.com/9057412/153926668-aca1997e-a1ac-42d6-9054-83855f612a9f.png)
> 
> How do you envision the control box for text on a path?

@melchiar and @asturur Thank you for your answer.

 I think that one big problem here is that I can't click on the text outside de control box (I'm using perPixelTargetFind for texts).

**Comment by melchiar** [comment]
There are a couple options. You can put padding on the text to expand the control box. You can also set pathAlign to center on the text so that the text draws on the middle of the path rather than above it.

I wouldn't recommend using perPixelTargetFind on text though... it'll make selection more difficult when using narrower fonts.
