### ISSUE TITLE
Keyboard does not open on iOS when called `enterEditing`

### ISSUE THREAD

**Issue by sunsetninja** [fabricjs/fabric.js#7734]
## Version
5.2.1

## Test Case
https://codesandbox.io/s/fabric-safari-keyboard-issue-cbj0tb

## Information about environment
Chrome 98.0.4758.102

## Steps To Reproduce
In the test case above

1. Open sandbox on mobile safari

## Expected Behavior
Keyboard is open

## Actual Behavior
Keyboard is not open

![telegram-cloud-photo-size-2-5237827783181318338-y](https://user-images.githubusercontent.com/13559663/155286373-63b5c096-f7b1-49ba-a498-e857de08c1a8.jpg)

**Comment by asturur** [comment]
Yes IOS and Android often change behaviour when you try to programmatically focus a text, especially if is an hidden input.
You can try to:
- set the canvas to focus first
- use the `hiddenTextareaContainer` property of the textbox, to specify a dom element where the hidden textarea should be attached and try to circumvent this limitation (if the textarea is visible it should work )

**Comment by todor996** [comment]
Incase anyone still has this issue, solution is this:
1) created a basic input with `height 1px; width 1px; visibility: hidden; position: fixed; top: 0; left: 0; font-size: 1px`, type text.
2) on whichever div/button where you want to call enterEditing, you need to find your hidden input, set visibility: visible,
trigger hiddenInput.focus(); and set visibility back to visibility: hidden. This way you will have opened keyboard, so you can call enterEditing/focus on specific canvas .
3) thing is you need to trigger show + focus + hide of a hidden input on user-invoked input, since iOS by default won't open keyboard when you call focus programatically, you have to call it on onClick event, onMove or something like that, so you need to first call it directly in some button onClick, or to add a shadow wrapper div that will just call this onClick and propagate event further.
This is how i fixed this issue on fabric.js version 4.4.0
