### ISSUE TITLE
deprecate `_getNonTransformedDimensions`

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#7919]
@asturur I think we should deprecate `_getNonTransformedDimensions` - it doesn't conform to `strokeUniform` and is barely used by fabric.
https://github.com/fabricjs/fabric.js/search?q=_getNonTransformedDimensions&type=code

It is used by `renderBackground` and seems to introduce a bug there if I am not mistaken.
Eraser doesn't need it (object size is needed, no stroke) and Line should be deprecated as well.
Beside that it is not used.

I pushed a [fix to the website](https://github.com/fabricjs/fabricjs.com/commit/42bfe987a3898b09f14d14d59ec3a67a7a37d8a1) that proves this is bad thanks to #7639 .
Thoughts?

**Comment by asturur** [comment]
It does not conform to strokeUniform, because the non transformedDImension is the size with no scaling or skewing or nothing.
So strokeUniform does not matter. I can see how renderBackground with stroke uniform could have some issue with that.
Before introduction of strokeUniform it was the input to get to transformedDimensions, but that is now not true anymore.
Is an internal function, should be very small, if we deprecate it we still need to copy it somewhere where is used.
It can be done, i wouldn't get distracted too much with that tho.

And as usual strokeUniform was a feture added without thinking too much ( that does not work with text and still generates issues with other elements )
