### ISSUE TITLE
Get absolute position

### ISSUE THREAD

**Issue by paulocheque** [fabricjs/fabric.js#801]
I have a component inside of a group. Its coordinates is relative to the group. How can I get its absolute position, or, in another words, the relative position to the canvas?

Maybe a element.getParent() could help too. Any suggestion?

Sorry by the too newbie question and thanks in advance.

**Comment by AshtonRoute** [comment]
can we have a function like getAbsolutePosition(obj) which returns {x: x, y: y}. or add absoluteLeft and absoluteTop properties to objects, because I need to get absolute position of every object in the group and calculating everything myself with fabric.util.rotationPoint is kinda annoying.

**Comment by asturur** [comment]
What do you mean by absolute position of object in group? if you explain me with a drawing ( paper + pen + picture is ok ) i will tell you how to do it. there is no builtin method but you can write your own easily

**Comment by AshtonRoute** [comment]
by absolute I mean relative to canvas

**Comment by asturur** [comment]
Top Left of object or top left of bounding box of object? ( imagine a rect rotated of 45°, what is top left for you? )

**Comment by AshtonRoute** [comment]
Top left of object

**Comment by AshtonRoute** [comment]
thx to @asturur 

```javascript
function getAbsolutePosition(obj) {
        var m = obj.calcTransformMatrix();

        return {left: m[4], top: m[5]};
    }
}
```

**Comment by asturur** [comment]
i think that  m4 and m5 represent the translate effect that gets applied to -width/2 and -height/2 of the object.... i'm not sure they are actually top and left.

**Comment by NoelBaron** [comment]
@AshtonRoute and @asturur: You are correct, it is not exactly top and left. Using the code from AshtonRoute, is there an alternative that would give top & left?  It's super close and works as intended, but it's not actually correct :( 

FYI: I am doing remote sync with a 2nd client (other browser). This was the best solution to perform updates to objects without worrying about groups, but the m4/m5 combo is still a few yards from a touchdown.  Any ideas?

**Comment by NoelBaron** [comment]
FYI: @AshtonRoute and @asturur : This did the trick: [How to get the canvas relative position of an object that is in a group](http://stackoverflow.com/questions/29829475/how-to-get-the-canvas-relative-position-of-an-object-that-is-in-a-group)

```
o.set('left',o.left + o.group.left + o.group.width/2);
o.set('top',o.top + o.group.top + o.group.height/2);
```

**Comment by lakemalcom** [comment]
I just wanted to add a +1 on to here. I definitely have the need to obtain canvas-relative coordinates while multiple objects are selected. 

I find it difficult to manage when the coordinate system changes for a given object while it is in a group -- I would prefer a mode/setting where the coordinates are always canvas relative, like when an object is not selected.

An example use case -- I am drawing a selectable object that has a non-selectable object follow it along. I position this second object using events ('moving', 'modified') and calculate its position relative to the selectable object. This works great for single selections.

But, if I have two of those selected, now none of my code works because if I try to calculate the position of the 'following' object, the selectable objects both return group-relative positions.

**Comment by prinsherbert** [comment]
Wouldn't it make sense for objects to have some method that returns x- and y-coordinates, widths and heights with respect to the canvas, which is that most developers will be interested in. Now developers need to code all the nested scaling and translating that is done in groups, highly likely resulting in buggy code, since most developers are users and not experts of `fabric.js`.

**Comment by nickasd** [comment]
I would also welcome an easy way of getting canvas relative positions. I have been struggling for many hours because the coordinates of selected objects were different than from the others, until I finally found out. Currently when I have to read those coordinates I empty the selection, which is not optimal. 

I also think that most developers would expect all coordinates to be relative to the canvas. Besides, it's only mentioned very briefly in the tutorial, which makes it hard for developers new to fabric.js to remember or even pay attention to this particular behaviour.

**Comment by asturur** [comment]
I agree than an extend tutorial on coordinates and transformations is needed.

**Comment by victor-ponamariov** [comment]
I'm building a "look" constructor, where you can drop some clothing on canvas and save it. Plus I save all geometry to server, since the same look can be displayed on mobile.

Each time object is modified I update a special property "geometry" which I send to the server. 

All I need is absolute left/top, but there is no method for this. Of course it is possible to calculate them but this is definitely is not convenient :(

**Comment by victor-ponamariov** [comment]
Yeah, but I also need scale and other stuff as well. Though I decided just to re-read coordinates after selection is cleared, kind of workaround :)

**Comment by Chienle** [comment]
> o.set('left',o.left + o.group.left + o.group.width/2);
> o.set('top',o.top + o.group.top + o.group.height/2);

Your solution working well, thank bro!

**Comment by onejae** [comment]
> FYI: @AshtonRoute and @asturur : This did the trick: [How to get the canvas relative position of an object that is in a group](http://stackoverflow.com/questions/29829475/how-to-get-the-canvas-relative-position-of-an-object-that-is-in-a-group)
> 
> ```
> o.set('left',o.left + o.group.left + o.group.width/2);
> o.set('top',o.top + o.group.top + o.group.height/2);
> ```

thanks man, I've been looking for this solution..

**Comment by asturur** [comment]
This won't work outside the very simple cases.

for the object that is any group, the position of the top left corner is, for example:

```js
// 1. get the matrix for the object.
var matrix = ObjectInGroup.calcTransformMatrix();
// 2. choose the point you want, fro example top, left.
var point = { x: -ObjectInGroup.width/2, y: ObjectInGroup.height/2 };
// 3. transform the point
var pointOnCanvas = fabric.util.transformPoint(point, matrix)
```

**Comment by rwillett** [comment]
@asturur 

Thanks for this code. Why do you divide the width and height? I know it works, but can't see thereason for this.

Thanks

Rob

**Comment by asturur** [comment]
because the object transform matrix you obtain with the first function is based on object center, top left corner, view from the center, is half width and half height away from the center.

Is this what you were asking?

**Comment by rwillett** [comment]
@asturur 

That explains it. Thats the explanation from the code. Wondered why that is the case. but as it works not too bothered.

many thanks

Rob

**Comment by asturur** [comment]
We use the center transform because rotation and scaling are easier then to accomplish separated from translations.
Is something that makes calculations a little bit easier and symmetrical, at least for me.

**Comment by rwillett** [comment]
Thats good enough for me. 

Appreciate the quick response,

Rob

**Comment by NoelBaron** [comment]
Y'all, it's been forever since I worked in this lib. Has anyone in the community produced a whiteboard+toolbar demo that handles most of what we were trying to accomplish 4 years ago? I'm running a project that could use something like that, just wondering. Hope y'all are well!

**Comment by rwillett** [comment]
If somebody has produced it, I haven't found it.

This was opened 22 Aug 2013, that's a long time ago.

I need to find the absolute positions of vertices in different shapes, so I'm going to have to write something to do this. My fabric.js knowledge is limited but if we put heads together (virtually), we could come up with a few functions taht do the job. 

Rob

**Comment by asturur** [comment]
If you mean a client to client web socket syncronizes drawing app, not that i can reference one. Since 2016 many things have improved but still i would suggest transferring the fabricObject.toObject() output on the network, it will save you headaches.

**Comment by rwillett** [comment]
I don't want anything complicated, just a function to get all the absolute points of a polygon/rectangle/triangle. 

I have to do it so will start on it, but if anybody wants to help...

**Comment by asturur** [comment]
@rwillett you and @noelbaron are talking about 2 different things entirely.

Your use case should be solved in this issue
https://github.com/fabricjs/fabric.js/issues/6522
That can be found searching the issue tracker for `polygon points`

**Comment by rwillett** [comment]
OK, I had assumed that @NoelBaron  was looking for absolute points as I was :) You know when you assume something....

Thanks for this, I'll look at #6522 as that might well solve the problem.

My use case is generating tool paths for CNC machines. I need to track whats inside a polygon and generate a series of gcode commands to cut out the interior using a CNC bit of a certain diameter. I think we've worked out how to generate the cutting paths for polygons, both convex, concave and complex (crossing each other). This is not quite a scanline fill but is close to it.  We need the points of a the polygon to pass into the service now, at the moment we just have an outline dinosaur for testing :)

![image](https://user-images.githubusercontent.com/668923/106355595-eb0b6e00-62f0-11eb-858a-36896809b0de.png)

The black is the area we cut in a scanline, the blue is a different that traces the outline.

Rob

**Comment by kiran-venugopal** [comment]
Also how do we get absolute coordinates after rotating a selection?

**Comment by YoussefArrari** [comment]
> height

its been 8 years since u made this comment and ur still saving people hours thank u i wasted 9 hours in this dump problem thank you for saving my ass xd

**Comment by YoussefArrari** [comment]
> FYI: @AshtonRoute and @asturur : This did the trick: [How to get the canvas relative position of an object that is in a group](http://stackoverflow.com/questions/29829475/how-to-get-the-canvas-relative-position-of-an-object-that-is-in-a-group)
> 
> ```
> o.set('left',o.left + o.group.left + o.group.width/2);
> o.set('top',o.top + o.group.top + o.group.height/2);
> ```

It's been 8 years since you made this comment, and you're still saving people hours. Thank you! I wasted 9 hours on this problem i know silly me xd , but you saved me. Thank you so much!

**Comment by asturur** [comment]
Things may have changed a little bit to be honest. Please check also modern answers
