### ISSUE TITLE
Text transformatiion should be like this

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [fabricjs/fabric.js#8195]
As you can see, the image shows a very fancy way to distort/transform text, there should be a way to do something like that.

(They are using Fabric 5.2.1)

![image](https://user-images.githubusercontent.com/6233059/186951321-c65775dc-3330-4292-9cbc-7b916f489623.png)

**Comment by neopheus** [comment]
what is the url ?

**Comment by EdnaldoNeimeg** [comment]
> what is the url ?

https://app.kittl.com/

**Comment by ShaMan123** [comment]
this is not an issue and is quite useless
should be?

**Comment by EdnaldoNeimeg** [comment]
USELESS? Really?
This is one of the most desired features.
Text on path was just a kick off. Text warping should be the main goal.

**Comment by ShaMan123** [comment]
your description is useless
so little effort in writing a decent ticket

> Text warping should be the main goal.

Should be? 
This is open source.
Get to work and PR.

**Comment by ShaMan123** [comment]
https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md

I will back you if you invest true grit

**Comment by EdnaldoNeimeg** [comment]
USELESS? Really?
This is one of the most desired feateores

> your description is useless so little effort in writing a decent ticket
> 
> > Text warping should be the main goal.
> 
> Should be? This is open source. Get to work and PR.

1 - English is not my native language
2 - So, what you're saying is "If you want a feature go do it yourself, i don't give a damm"

The world would be a better place without stupid answers.

**Comment by ShaMan123** [comment]
You have violated the code of conduct
Refrain of doing so in the future

**Comment by asturur** [comment]
@EdnaldoNeimeg if you think a feature is needed or missing present it in the correct way. Don't assume we have time to interpret every new issue and understand if it is a feature request, a thank you post, a bug, or a start of a discussion.

Said so useless was probably refered to the issue and not the feature, since it has no indication of how the feature work, only a screenshot of a generic ui, and the use of should that seems to imply the feature is expected.

We are people not answering bots and we need a bit more of polite interaction to work best.
