### ISSUE TITLE
[Bug]: Transformation incorrect after rotation using the code from tutorials transformations

### ISSUE THREAD

**Issue by universeroc** [fabricjs/fabric.js#8576]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

http://fabricjs.com/using-transformations

### Steps To Reproduce

1. open http://fabricjs.com/using-transformations
2. bind minion to boss
3. rotate the boss for several times and stop at a specific angle

### Expected Behavior

the minion 's left and top is aligned to the boss
<img width="357" alt="Screen Shot 2023-01-08 at 18 27 10" src="https://user-images.githubusercontent.com/3518853/211191484-61f7ff20-610a-4e62-9d92-d98ed0af0f7a.png">

### Actual Behavior

the top / left is not aligned to the boss
<img width="354" alt="Screen Shot 2023-01-08 at 18 26 58" src="https://user-images.githubusercontent.com/3518853/211191479-2815d3c1-c9c7-413d-bd32-ccaa3d3bcb9d.png">

**Comment by iocoker** [comment]
@universeroc I don't think this is a bug, the article is just a proof of concept on what's possible and not a definitive or an exact implementation.

In this particular case to solve the issue you raised, I would also add `modified` to the event to listen for, so as to cover every possible instance when the object is changed. And also updateMinions on canvas' `mouse:up` so that when the user releases his mouse, the minions are updated to the last known transforms.

Finally, instead of doing all these `var minions = canvas.getObjects().filter(o => o !== boss);` repetitively, I would do that once, just `before:transform` since the array never changes during transformations.

**Comment by universeroc** [comment]
> 



> @universeroc I don't think this is a bug, the article is just a proof of concept on what's possible and not a definitive or an exact implementation.
> 
> In this particular case to solve the issue you raised, I would also add `modified` to the event to listen for, so as to cover every possible instance when the object is changed. And also updateMinions on canvas' `mouse:up` so that when the user releases his mouse, the minions are updated to the last known transforms.
> 
> Finally, instead of doing all these `var minions = canvas.getObjects().filter(o => o !== boss);` repetitively, I would do that once, just `before:transform` since the array never changes during transformations.

Yeah, thanks for your reply! I've tested your suggestion and it works for me :)
