### ISSUE TITLE
chore(Types): export types

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#8868]
@asturur we need to address this
The community is starting to complain and use types in a wrong way via VSCODE importing scheme.
As mentioned before, I suggest to remove all the T prefixes and export all types as a named export
`import { types } from 'fabric'`
What do you think?

**Comment by ShaMan123** [comment]
Of course we can leave the T prefix for now.
The main thing is the exporting.
No types are currently exported. 
Why BTW?

**Comment by asturur** [comment]
aren't type exported automatically from the build, all the one that are used in the functions?

**Comment by asturur** [comment]
Or link the complains if the information is there.
I gave a quick look at newer discussion but didn't find much

**Comment by asturur** [comment]
> Of course we can leave the T prefix discussion for now. The main thing is the exporting. No types are currently exported. Why BTW?

I think the WHY is becuase we discoverd doing.
We didn't have a TS long term plan to act upon.
As far as i can see we generate a fabric.d.ts file that exports all the types and package.json knows about it. So i m not sure we are not exporting them.

You can't export types from a generated JS file because i don't think such thing exists.

**Comment by gloriousjob** [comment]
Thanks, @ShaMan123! This is addressing the concern I had.

So I wouldnt' say no types are exported. For example, in my subclass example, import { Rect } from 'fabric' works. However, I can't get to the other exports inside of Rect to use the parts in my subclass.

The reason for this issue appears to be because index.d.ts references fabric.d.ts, which only has a subset of items (e.g., Rect is listed in there but not the other exports in Rect). These two files are basically copies of their normal counterparts (index.ts and fabric.ts). These aren't autogenerated.

**Comment by ShaMan123** [comment]
Notice that no types are exported from the index files, that is what I mean
I will PR soon

**Comment by bladerunner2020** [comment]
Any update on this? We need other types (like GroupProps).
