### ISSUE TITLE
[Bug]: Overlay disappears when panned out of the canvas, even if overlayVpt is set to false

### ISSUE THREAD

**Issue by JPLassala-bix** [fabricjs/fabric.js#8887]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari

### Node Version (if applicable)

None

### Link To Reproduction

Overlay disappears when panning even with overlayVpt set to false

### Steps To Reproduce

1. Create a new canvas
2. Create a new shape
3. Add the shape as an overlay, making sure it is displayed on the canvas
4. Pan on the canvas using `relativePan()` until the internal overlay coordinates get out of the screen.

I made a working demo reproducing the error:
https://codesandbox.io/s/long-frost-2dp3u4?file=/src/index.js

To pan in that canvas, one should press and hold the space bar, and then click and drag to any direction. When dragging, a clone of the circle and a blue square (used as a guide) will move until the circle goes out of the screen.
When that happens, the overlay disappears.

I included some console output that indicates when the overlay ends up disappearing.

### Expected Behavior

When `overlayVpt` is set to `false`, the overlay shouldn't be affected by viewPort transformations.

### Actual Behavior

When panning on the canvas enough that the viewport transform goes beyond the supposed overlay location, the overlay is counted as `isOffScreen` and it doesn't render anymore 

### Error Message & Stack Trace

```bash
When the console says:

> Overlay in screen:  false

The object disappears.
```

**Comment by ShaMan123** [comment]
v6 working: https://codesandbox.io/s/keen-shannon-eigcee?file=/src/index.js
I believe the error is in your code.
You shouldn't add `circle` to canvas. But there is something else there.

**Comment by ShaMan123** [comment]
I think there is a bug here regarding bbox calc.
Since ignoreVpt is flagged I am guessing that `isOnScreen` is wrong because it should use (0,0) as tl and not the vpt coords

I might try to handle this in #8767 but I tend not to because I think bg/overlay is an obsolete concept that should be removed
@asturur  thoughts?

**Comment by ShaMan123** [comment]
Yes, seems I am correct. It is bad design.

**Comment by asturur** [comment]
I don't think #8767 is the place for this.
Redoing how we calculate the coordinates does not change how we use isOnScreen, so definitely no.

background and overlay are 2 simple concepts that developers can choose to ignore entirely, while who wants something that is completely outside of the stack has a place to go, i don't see harm in those, nor obsolescense.
Can you try to explain why they seem obsolete to you?

Regarding the bug we should try to fix it as possible, i don't think an interaction between isOnscreen and overlayVpt was ever planned.

@JPLassala-bix removing the error of adding the same object both to canvas and overlay or background, the bug remains, so is definetely a legit bug to fix.
Just to understand, can you describe how are you using overlay in your app? I supposed you simplified the fiddle for the sake of debugging, but i would like to understand why you had an object that was both on canvas and on the overlay, if that was something happened while making the codepen or your design.

**Comment by ShaMan123** [comment]
> Regarding the bug we should try to fix it as possible, i don't think an interaction between isOnscreen and overlayVpt was ever planned.

This is why I think it is not well designed. Since geometry methods are exposed on these objects they should work out of the box. Anything else is considered a bug in my opinion. But such an ugly workaround to make it work.

> Can you try to explain why they seem obsolete to you?
Apart form this geometry bug:
Since we moved to a strict object tree whe need to check bg/overlay don't exist elsewhere as well.
Brush is very weird when used with overlay since it draw on top of it when active but adds the path under it.
You can't control the order of bg/overlay color/image - it is fixed.
It requires a lot of code in fabric but we have concepts to control the stack.
With Group (and eventually Layer) I don't see a need for bg/overlay. You can manage the stack however you want.
Things like #7738 #8834 are not welcome features IMO since they are solved in the object level so it is basically redundant work and noise that can be handled easily by using a group.
Ignoring vpt can be achieved on the object level (if we fire an event it will be even easier)

I am sure I missed a few things.
In general it is a redundant concept IMO.

**Comment by asturur** [comment]
This bug is here since we added isOnScreen and no one noticed it i guess

the bug right now is caused from the fact that isOnScreen is checked inside the object, and so it can't be optional because bg and overlay aren't special object.

isOnScreen could be moved as a sibling the Object.render function, in canvas and group. Shouldn't influence anything else, but would eventually break subclasses or things that trust render to do that job.

**Comment by asturur** [comment]
> Since we moved to a strict object tree

What do you mean here? there haven't been any changes to the object tree since the beginning

**Comment by ShaMan123** [comment]
Every object can belong to a single parent, right?
So we have checks for that and they don't include bg/overlay, we forgot that.

**Comment by asturur** [comment]
Oh yes but that was always the case, was never different

**Comment by ShaMan123** [comment]
isOnScreen is one thing, but truth is all geometry is affected
If you want to check overlapping it will be wrong as well since the 2 object exist on different planes. That is why I suggested #8767 . Because it provides a mechanism to perform geometry on objects that don't belong to the same plane with ease.

**Comment by asturur** [comment]
so to actually fix the bug we need to go with something as simple as this, unless there is something simpler that i can't see.
And as sideeffect-less as possible
https://github.com/fabricjs/fabric.js/pull/8896

**Comment by ShaMan123** [comment]
This fixes a symptom not the problem

**Comment by asturur** [comment]
> This fixes a symptom not the problem
The same can be said for any fix it just depends on where you place the symptom and the problem and is opinion based.


I was expecting this comment, but there is a clear bug and i want to fix it.
overlayVpt is doing what it says it does, same as offscreen check, and is clear that his actual result doesn't make sense.
You probably see this as a `dirty patch` but it does what it needs to do and is scoped to the exact issue we see reported.

**Comment by ShaMan123** [comment]
- I can try to split #8767, I didn't because I don't want to waste efforts before we agree on a way forward
- I am just stating that we can expect a bug to raised from a dev using the rest of geometry in this context so for me it is a partial fix

Anyways I do not use bg/overlay for all the reasons I have stated so truth is I don't care so much

**Comment by asturur** [comment]
i care because this is how i want the project to move.
There is a small bug, it gets a small fix, till there is enough need for a different rework of the existing code that needs to cut or change features.

I ll tell you how i want to split #8767 since i m the one with the issue with the size and coverage

**Comment by ShaMan123** [comment]
To clarify, I see it as you see `strokeUniform`

**Comment by asturur** [comment]
yes, but none of them are going away for 6.0 so we have to deal with them.
And if i put them in scale, this is just a bit more useful than strokeUniform.
Because everyone knows what a background does, not everyone gets what strokeUniform does.

**Comment by JPLassala-bix** [comment]
@asturur 
> Just to understand, can you describe how are you using overlay in your app? I supposed you simplified the fiddle for the sake of debugging, but i would like to understand why you had an object that was both on canvas and on the overlay, if that was something happened while making the codepen or your design.

It was my bad by adding it on the fiddle canvas. I just wanted to show a visual representation on how the overlay disappears when the supposed shape that represents goes off the screen. If you remove the line where the circle is added as a shape, and add it only as an overlay, the exact bug happens.

In the app I'm developing, I just want an overlay that stays displayed no matter how far I scrolled.

**Comment by JPLassala-bix** [comment]
@asturur I'm testing the `5.x` branch with #8896 merged.

I have an updated sandbox
https://codesandbox.io/s/long-frost-2dp3u4?file=/src/index.js
With the package from the latest code from that branch as a dependency, and with the `canvas.add(circle)` line removed.

The overlay still disappears and isOnScreen still changes to `false`.
Either I'm wrong with the package.json definition or the bug still persists.
