### ISSUE TITLE
[BUG]: text style onInput

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#9028]
@asturur please help if you can

**It seems that when text is wrapped styles is not updated correctly from onInput**

I have to say, I do understand why styles was chosen to be a map but I don't think that was a good choice.
So much easier to maintain and update it as a flat array corresponding to char offset.
Then wrapping is not related and syncing char changes from `onInput` to styles or where ever is as simple as splicing 
I do think that fixing this bug or making it an array will cost the same amount of time.
I understand it is breaking so you will probably not want this now.
The logic for me is unapproachable.

Suspected `insertNewlineStyleObject` and `removeStyleFromTo`:

https://github.com/fabricjs/fabric.js/assets/34343793/35b086e7-7ae3-4858-b471-01a4bb91b890

https://github.com/fabricjs/fabric.js/assets/34343793/a66cc38a-b33e-4a5f-9b51-18d6c70abb5a

**Comment by ShaMan123** [comment]
BTW this is not a regression, it is reproduced in v3 by a client

**Comment by ShaMan123** [comment]
I am waiting your input to move forward with this

**Comment by ShaMan123** [comment]
Earlier I saw usage of get2DCursorLocation in style methods not using the unwrapped chars
That might be the bug
What a mess

**Comment by asturur** [comment]
note:
In the first video i don't understand what you do.
In the second video i understand but i don't know if you are pressing forward deleted or back delete.

**Comment by ShaMan123** [comment]
First video:
- copy
- paste
- press enter
- style is broken

Second video:
I don't know if delete or backdelete - but I am not sure it makes a difference - logic is bad

**Comment by asturur** [comment]
note: also this bug is for splitByGrapheme: true only

**Comment by asturur** [comment]
Looking at https://github.com/fabricjs/fabric.js/pull/9192 the current breakdown of the bug is as follow
(i ll edit this message in steps as soon as i discover)

Given an object like this

<img width="345" alt="image" src="https://github.com/fabricjs/fabric.js/assets/1194048/a3c0d335-b076-4459-8057-1d0e4f7d15dd">

Where `fabric.js sandbox` and `awesome textbox item` are 2 hard lines:

## splitByGrapheme: false

I can't find bugs.
i can break and rejoin lines that are in the same position of the hard line, or soft wrapped one or more time.
I can copy past across the same line, soft wrapped or not, and across multiple lines, starting or ending on soft wrapped lines.
