### ISSUE TITLE
[Bug]: Erased path gets blurry after resize the object

### ISSUE THREAD

**Issue by frankgalindo-briteris** [fabricjs/fabric.js#9095]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome, Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-k6n7rt

### Steps To Reproduce

1. Click on "Erase" button
2. Erase part of the square
3. Click on "Drag" button
4. Select the square and resize it
5. Click on "Erase" button
6. Erase part of the square again

![image](https://github.com/fabricjs/fabric.js/assets/127247073/4772452a-07f7-492b-a53a-82283c66a5bd)

Note: this also happens on the erasing demo (http://fabricjs.com/erasing)

### Expected Behavior

The path that was erased should not be blurry

### Actual Behavior

The path that was erased became blurry, and if I erase it again the path will also be blurry.

### Error Message & Stack Trace

```bash
N/A
```

**Comment by ShaMan123** [comment]
Hmm...
First eraser needs to migrate to v6 #8499 
Then I can look into this
I think it will also need #8298 for context isolation - meaning the problem might be that because eraser clips the object currently caching is used. Caching renders in a different scale than the visible outcome and that might be causing the blur.
Another problem is that the eraser is unaware of the object so it doesn't know that it might be rendering on a cache `isOnACache` but actually since eraser is clipped by the paths that doesn't matter but adds more complexity to the problem

A solution might be to reverse the rendering order with context isolation. Rendering the eraser paths, using globalCompositeOperation and then rendering the object on top - but that doesn't sound a solution to me with the current state of caching and rendering.

**Comment by ShaMan123** [comment]
An ugly workaround would be to fiddle with th escaling values and force caching to invalidate properly but i don't think it is feasible

Seems that the eraser should not be part of the cached object canvas but an independant one

**Comment by ShaMan123** [comment]
Correct

**Comment by ShaMan123** [comment]
please try this with the new package [erase2d](https://github.com/ShaMan123/erase2d) and report there for issue

I expect it to be blurry still because of caching but I plan to fix this soon, already tested a solution that remove caching
