### ISSUE TITLE
[Bug]: Cross-Origin Request Blocked Error with fabric.loadSVGFromURL for SVGs uploaded to S3 Bucket

### ISSUE THREAD

**Issue by ab-etemadi** [fabricjs/fabric.js#9723]
### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Opera, Microsoft Edge, Node.js

### Node Version (if applicable)

18.18.0

### Link To Reproduction

https://jsfiddle.net/abetemadi/sn98qugr/2/

### Steps To Reproduce

1. Upload SVGs to S3 Bucket:
- Upload SVG files to an S3 Bucket, ensuring they are publicly accessible.
2. Configure CORS Settings:
- Set CORS settings on the S3 Bucket to allow requests from your domain.
3. Initial add:
- Use fabric.loadSVGFromURL to load SVGs from S3 Bucket URLs.
- Verify successful loading without CORS errors.
4. Add that SVG after 5 or 6 hours later

### Expected Behavior

SVG files load successfully using fabric.loadSVGFromURL without encountering CORS errors, given that CORS settings are correctly configured on the S3 Bucket.

### Actual Behavior

After an initial successful load, "Cross-Origin Request Blocked" errors occur inconsistently when retrying SVG loading, even though SVG files and CORS settings remain unchanged.

**Comment by asturur** [comment]
@ab-etemadi  are you able to request the same svg as a string using fetch from jsfiddle in the same way? we could then inspect what is going wrong.
The current loadSVGFromURL of fabricJS does not set any header for the request as far as i can remember.
We are not even using fetch yet.

**Comment by ab-etemadi** [comment]
Thanks, @asturur, for getting back to me quickly. It seems like there's a problem with the S3 Bucket. Sometimes it works fine, but other times it doesn't. I've noticed that when I try to fetch an image I uploaded five hours ago, it doesn't work. However, if I upload the same image again, it fetches without any issues.

**Comment by asturur** [comment]
i have sometimes the same issue with buckets at work.
There may be some issues like:

- fetching the svg inside an image tag in your browser session without crossorigin set will create a cache in your browser that will return the request with no headers when you try to fetch it elsewehere
- sometimes you have lambdas in front of the bucket ( that someone else added or you added and you forgot about them ) that are supposed to do nothing harmful but then they do
- other things that happen in the edge/cloud domain that i don't full grasp because is not my primary domain

**Comment by asturur** [comment]
We will reopen if you find the issue and is still related to fabric
