### ISSUE TITLE
[Bug]: Active Selectin has wrong bounding box when the children set storkeUniform to true and scaling it.

### ISSUE THREAD

**Issue by ritali4912** [fabricjs/fabric.js#9744]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta19

### In What environments are you experiencing the problem?

Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/ritali4912/jtL2mg6p/8/

### Steps To Reproduce

1. Add 2 fabric objects with strokeUniform to true, also I set canvas.uniformScaling to false
2. Active Selection them
3. Scaling the Active Selection

The Active Selection bounding box is wrong. It seems not consider the strokeUniform as true.

### Expected Behavior

The Active Selection bounding box should correct

### Actual Behavior

When scaling the active selection, it seems not consider the strokeUniform as true.

**Before scaling the active selection, it is correct**
![image](https://github.com/fabricjs/fabric.js/assets/67466090/c750821b-8f51-40cc-bafb-aac680e0b453)

**After scaling, the active selection bounding box larger than expected**
![image](https://github.com/fabricjs/fabric.js/assets/67466090/01021e30-4e14-41d2-a23c-6cdfced8b42f)

**Comment by asturur** [comment]
This is a known issue.
You have now the performLayout that probably can help you keep it fixed.
My personal opinion is that stroke uniform is a wrong feature and should be removed.
We are tracking this bug here:
https://github.com/fabricjs/fabric.js/issues/6705
and here too
https://github.com/fabricjs/fabric.js/issues/6441

Maybe there is a way you can attach the performLayout so that it will fix the gap at the cost of a scaling that doesn't follow the mouse cursor exactly.

Why stroke uniform is wrong? Because is used wrongly.
Developers use strokeuniform so that they can scale an object instead of changing its's size. i see there 2 ellipses or 2 circles that have been squeezed ( i can't distinguish ).
If you SCALE them you are scaling everything the circle/ellipses has including the stroke. If you want to just change the size of them you should act on radius or rx and ry for the ellipse, or on all the path commands for more complex shape.

Stroke uniform is nice for a single geometric shape but quickly loose usability when you have a group of shapes mixed together or when you scale down something its behaviour becomes more odd.

But anyway can you transfer that example in a jsfiddle so that i can try to apply the performLayout to it and see if it makes the situation nicer?

**Comment by ritali4912** [comment]
@asturur 
Thanks so much. I have transfer the example to jsfiddle: [strokeUniform under Active Selection](https://jsfiddle.net/ritali4912/jtL2mg6p/8/)
Please have a try.

BTW, I have a question for the strokeUniform.
1. If the strokeUniform is wrongly used, then how to fix the strokeWidth during scaling? We have several this kind cases in our scenarios.
2. If a polyline, is there way to fix the strokeWidth during scaline it?

**Comment by asturur** [comment]
Can you setup a fiddle with 2 polylines with stroke uniform in a group?
both that have a stroke of 5 ( or something that is visible, not 1 ) and one that has a scaled positively and one that is scaled below 1? so that we can experiment with group layout on the fiddle and exchange ideas.

I have been venting that strokeUniform was rushed mistake but we are trying to see if is fixable at least in those evident issues, while we understand if rewriting all the geometric functionalities will solve it at the root

**Comment by asturur** [comment]
I have also to say the bug you picture in the image is not really a bug, is just a bit of space, correct?
the bug starts when you squeeze the group and the stroke starts to come out of the group border

**Comment by asturur** [comment]
Sorry i didn't see from the email you posted a link.

**Comment by asturur** [comment]
This is what i could sketch:
https://jsfiddle.net/asturur/6oLsc45v/9/

I made a wrapWithLayouting that takes the standard action handler of a control and force a group layout if if the target has it.
It kind of duplicate the work of wrapWithFixedAnchor and probably should replace it and not wrap it again, but i just wanted to make an example and also make a point that with the current api you can still have a decent experience.

```
const wrapWithLayouting = (actionHandler) => {
	return (eventData, transform, x, y) => {
      const { target, originX, originY } = transform;

        const centerPoint = target.getRelativeCenterPoint(),
      constraint = target.translateToOriginPoint(centerPoint, originX, originY),
      actionPerformed = actionHandler(eventData, transform, x, y);
			if (target.triggerLayout) {
        target.triggerLayout();
        target.setPositionByOrigin(
          constraint,
          transform.originX,
          transform.originY
        );
      } 
    return actionPerformed;
  };
};
const controlSet = fabric.controlsUtils.createObjectDefaultControls()
const brControl = controlSet.br;
brControl.actionHandler = wrapWithLayouting(brControl.actionHandler);

const utahActiveSelectionDefaults = {
  lockScalingFlip: true,
  perPixelTargetFind: true,
  controls: {
    br: brControl
  }
  /* padding: 2 */
};
```

Now is this the perfect way to handle it? maybe no but it works.

Can this be made recursive for every nested group inside? yes with some legwork you can dive into targets and perform layouts from the most nested to the upper one, wasting some calculation.

So this works fine probably up to a certain number of objects

**Comment by ritali4912** [comment]
@asturur 
Thanks for your suggestion. 

According to your comment below,
> If you SCALE them you are scaling everything the circle/ellipses has including the stroke. If you want to just change the size of them you should act on radius or rx and ry for the ellipse, or on all the path commands for more complex shape.
> Stroke uniform is nice for a single geometric shape but quickly loose usability when you have a group of shapes mixed together or when you scale down something its behaviour becomes more odd.

May I say, If my control like 'tl', 'bl', 'tr', 'br' want to change everything except the strokeWidth, I need to overwrite its actionHandle - scaleObjectFromCorner.
The strokeUniform is not suggest to be used as above purpose?

**Comment by asturur** [comment]
I think that depending your use case my example is good enough.
Writing a full new action handler that changes radius ellipsis, rects and what not may be very complicated.
The function i provided you, does it solve your issue? the jsfiddle behaves nicely in my opinion
