### ISSUE TITLE
[Feature]: Will Fabric v6 support user-defined Object properties? 

### ISSUE THREAD

**Issue by wangrongding** [fabricjs/fabric.js#9845]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Will Fabric v6 support user-defined Object properties?   

For example, when I want to create an element, I can embed an Id in the object for convenient future use. Currently, Fabric v5 does not support this due to ts type restrictions, so I am currently using Object.assign to merge the ID with the target object.

### Current State

<img width="730" alt="image" src="https://github.com/fabricjs/fabric.js/assets/42437658/e2b60485-3206-47f5-888e-f204a6deef5f">

**Comment by asturur** [comment]
fabric v6 sort of supports that but the definition of types are hard to do.
This should definitely be explained in some doc.

**Comment by ouyoungs** [comment]
mean this? 
https://juejin.cn/post/7153068432303325220

```ts
let canvas = new fabric.Canvas('c')

let rect = new fabric.Rect({
  width: 30,
  height: 30,
  top: 10,
  left: 10,
  my_id: 'rect01'
})

canvas.add(rect)

function handleToJSON() {
  console.log(canvas.toJSON(['my_id'])) // 序列化，输出JSON
}
```

**Comment by wangrongding** [comment]
I know this, I'm talking about the official api and support for Typescript type.

**Comment by asturur** [comment]
i think today you can do:

```
const newText = new FabricText<{ id: string } & Partial<TextProps>>('myText', {
  id: 'hello',
  fontFamily: 'Arial',
});
```
But i m sure there will be some kind of hiccups here and there, is not as smooth as we want, is also hard to do because of mixins and everything.

Slowly mixin will go away and hopefully will be simple

**Comment by vadimcoder** [comment]
I ended up using this so far (I'm using v 6.0.0-rc2):

```javascript
interface ICustomData {
  entry: ...; // my custom prop
  isDirty: ...;  // my custom prop
}

// custom PathProps
interface IMyPathProps extends TOptions<PathProps> {
  customData: ICustomData;
}

// custom Path with custom data based on fabric Path
export class MyPath extends Path<IMyPathProps> {
  customData!: ICustomData;
}

// using:
fabricCanvas.add(
  new MyPath("M 0,0 ..." , {
    fill: 'transparent',
    customData: { // TS does type checking here
      entry: ...
      isDirty: ...,
    },
  }),
);

// or:
const path = fabricCanvas.getActiveObject() as MyPath;
console.log(path?.customData);
```

**Comment by zhe-he** [comment]
Let's solve it by rewriting...

```typescript
/** fabric.d.ts */
import "fabric";
declare module "fabric" {
    interface FabricObjectProps {
        /** mark 1 */
        someAttr?: string | number;
    }
    interface FabricObject {
         /** mark 2 */
        someAttr?: string | number;
    }
}
```
```typescript
/** patch.ts */
const lastToObject = FabricObject.prototype.toObject;
FabricObject.prototype.toObject = function (arr: string[] = []) {
     return lastToObject.call(this, arr.concat(["someAttr"]));
}
```
<img width="693" alt="image" src="https://github.com/fabricjs/fabric.js/assets/11306583/e70d3ebb-7a68-466a-afa8-fc45fadd21b3">
<img width="475" alt="image" src="https://github.com/fabricjs/fabric.js/assets/11306583/54ada689-edf6-4160-a2a2-b14b8faafd40">

**Comment by asturur** [comment]
#10071
Made the export of plain custom properties as simple as possible.
Deep objects won't be cloned.
I m also going to cover this topic on a specif doc on the website

**Comment by asturur** [comment]
https://fabricjs.github.io/docs/using-custom-properties/

**Comment by Smrtnyk** [comment]
I am having issues with properly typing classes that are extending from Group.
For example here https://github.com/Smrtnyk/Firetable/blob/master/packages/floor-creator/src/elements/Table.ts#L104
Group is not a generic so I cannot pass the unique table props to it

**Comment by asturur** [comment]
I forgot about that mixin there. I think we should make it Generic

**Comment by asturur** [comment]
I played a bit with it and while Props and SProps can still be made generic, i don't think eventSpec can.

**Comment by Smrtnyk** [comment]
I guess at least passing Props and SProps is better than nothing
it would solve my issue at least to not have ugly ts-expect-error

**Comment by asturur** [comment]
@Smrtnyk check if some of this code helps: https://github.com/fabricjs/fabric.js/pull/10092 i m still working on it didn't do deep testing

**Comment by Smrtnyk** [comment]
hm, it is still not really working
there is an error for Props not being assignable to Group props
because Props from documentation refer to serialized props of the group, which includes serialized layout manager, but props in group accept only layout manager.
I guess easiest for you is to add a test in fabric that is extending the group and make sure that there are no ts errors.
if you need test inspiration you can have a look at the link I posted above
https://github.com/Smrtnyk/Firetable/blob/master/packages/floor-creator/src/elements/Table.ts#L104
in my case I am extending the table class on a second level as well
https://github.com/Smrtnyk/Firetable/blob/master/packages/floor-creator/src/elements/RectTable.ts#L24
where I had to add another ts-expect-error.
I assume that `fromObject` also needs to be more flexible, not just toObject

**Comment by asturur** [comment]
Yes is not fixable as it is today.
I really spent 10+ hours on this and the correct way is to drop the collection mixin and duplicate the collection code for canvas and group.
But is like extra 5KB or more of code added to the library and makes me mad.

I'll probably try to resort to the older method in which the methods were copied over the class at runtime and i will duplicate the declarations only. But is time consuming.

For now the best thing you can do is just use the extend on the actual group and use declare and the constructor to add all of your props.

I checked your examples, where is that you are having issues with those? What is not working?

**Comment by shawngustaw** [comment]
@asturur would be nice if the docs for v6 could be improved with better examples of subclassing/adding custom data. They just vaguely say `"Subclassing is easier but is not always possible"`. When is it possible? When is it not possible? v6 has been out for 10 months now - are there docs that migrate the previous examples from v5 to v6? As someone new to fabric the docs have been terribly unhelpful and I've needed to learn how to do things in v5 and then convert everything to v6...

**Comment by asturur** [comment]
It is true that the docs suck and should be done better. It require time and concentration that i struggle to apply there.

For the custom data there isn't much else to say on top of the example that has been written there, if something is not clear it would be nice you tell me what is it that is confusing and i go and fix it with a clarification.\
What example would you like to see for custom data?


For subclassing, maybe we should find a subclassing need that is not just for exporting more data, since the addition of the customProperties static array, subclassing just to export more data is unnecessary complicated.

You would go and subclass  a shape when you want to create that behaves differently or has additional behaviors.
Were you looking at subclassing for some need in particular?

**Comment by shawngustaw** [comment]
@asturur 

so essentially I just have a couple elements that share the same shape (i.e. different types of circles that have different sets of custom data) and I was hoping to subclass so it's a bit easier to serialize/deserialize. If this isn't the right approach lmk though. I mostly was just struggling with the types from the examples and went in a couple different directions trying to resolve them. Here's an updated version of the example with all the type errors addressed:

```
import {
  ObjectEvents,
  Path,
  PathProps,
  SerializedPathProps,
  TClassProperties,
  TOptions,
} from "fabric";

interface UniquePathPlusProps {
  id?: string;
  name?: string;
}

export interface SerializedPathPlusProps
  extends SerializedPathProps,
    UniquePathPlusProps {}

export interface PathPlusProps
  extends SerializedPathProps,
    UniquePathPlusProps {}

export class PathPlus<
  Props extends TOptions<PathProps> = Partial<PathProps>,
  SProps extends SerializedPathPlusProps = SerializedPathPlusProps,
  EventSpec extends ObjectEvents = ObjectEvents
> extends Path<Props, SProps, EventSpec> {
  static type: "path"; // if you want it to override Path completely

  declare id?: string;
  declare name?: string;

  toObject<
    T extends Omit<Props & TClassProperties<this>, keyof SProps>,
    K extends keyof T = never
  >(propertiesToInclude: K[] = []): Pick<T, K> & SProps {
    return super.toObject([...propertiesToInclude, "id", "name"] as K[]);
  }
}

```

Only things I changed were adding all the correct imports, fixing the typo on `extend` -> `extends`, and then in the `toObject` fn adding the `as K[]` to make TS happy. Was curious if you knew a better way to do this without type coercion? Would love to use `satisfies` instead of `as` but TS doesn't like that atm. 

Also, are the current docs in this repo? I'd be happy to help start chipping away at migrating the v5 docs to v6, or at least updating that example to try to help out the next person. Let me know!

**Comment by asturur** [comment]
The docs are in the fabricjs.github.io repository is an astro website with md files.
You are welcome to propose improvement or even just pick up specific doc files and say this doc should also talk about this and this.

The data you want to serialize how does it look like?
