### ISSUE TITLE
Documentation on how clipTo works.

### ISSUE THREAD

**Issue by mikebronner** [fabricjs/fabric.js#985]
Some documentation and examples would be incredibly useful to demonstrate the various uses and application an implementations of clipTo on various fabric objects, from canvas, to paths, etc.

Description of various behaviors, like top and left, and how they work would be useful as well. (From what I understand now, top really means VerticalOffsetFromCenter, and left really means HorizontalOffsetFromCenter?)

Thanks!
##

**Comment by PaRoxUs** [comment]
Is clipTo Fabrics similar function to SVG's viewBox for the Canvas?

**Comment by asturur** [comment]
No, absolutely not.
Clip to is a function called before rendering.
fabricjs does:
ctx.save();
ctx.beginPath();
exec clipTo functions;
ctx.clip();


Untill the next ctx.restore(); the canvas is clipped to the path you drawn in clipTo functions.

Consider that any ctx.beginPath(); called in the function reset the first one called.
Canvas can clip to one path only.
This is why using group.render() as clipTo function does not work properly.
And this is also why clipping like an svg, with a complex shape is not a simple task.

**Comment by asturur** [comment]
You can ofcourse emulate a viewbox functionality with a clipTo function using 

ctx.scale();
and clipping by a rect.

**Comment by Aubron** [comment]
As someone who just finished creating a fabric.js project that needed to use clipto to do work in the canvas context, I would like to hopefully take on doing some example documentation to this. Would the source for http://fabricjs.com/clipping be the best place to provide additional examples?

I think that fabric has the interesting problem that, since it solves having to work in the CanvasRenderingContext2D directly, people will often be unprepared for being dropped into anything with a raw, object-centric context, while the situation seems obvious to folks who work/worked with the 2D context regularly.

**Comment by Aubron** [comment]
Sorry, one more aside, as I've noticed I can't immediately find the source for fabricjs.com, is that Open Source?

**Comment by Aubron** [comment]
(Would recommend closing this, as it's really a fabricjs.com problem)

**Comment by asturur** [comment]
I agree, but i tend to do all the things here so i get lost less easily.
Regarding just do it, i would give you an advice. I just deprectated clipTo because i want introduce something better.

If you are a clipTo user wit some experience and want to have a chat about that, let's do it.

**Comment by SpadarShut** [comment]
@asturur since clipTo is deprecated, what is the proposed way to do clipping currently?

**Comment by asturur** [comment]
clipPath. Please give a look at fabricjs.com and click on tutorial, then scroll down to last part.

**Comment by asturur** [comment]
i think i have to close this. i m planning to delete the clipTo code with release 4, since it has been deprecated long enough now.
